import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "mem.desc": "AI 记住了什么：跨对话的提示词画像、工作区共同记忆与学习内容档案。",
    "mem.tab.procedural": "程序性记忆",
    "mem.tab.audit": "历史审计（只读）",
    "mem.error": "记忆数据加载失败，请检查后端服务后重试。",
    "mem.disabled": "该智能层已被环境开关关闭，记忆模块未启用。",
    "mem.episodes.empty": "暂无历史情景记录",
    "mem.episodes.emptyDesc": "旧版情景记忆已停产：这里只陈列停产前的审计数据，不再新增。你的学习动态现在记录在学习内容档案与学习总览中。",
    "mem.loadMore": "加载更多",
    "mem.loadingMore": "加载中…",
    "mem.importance": "重要度",
    "mem.semantic.empty": "暂无历史语义事实",
    "mem.semantic.emptyDesc": "旧版语义巩固已停产：这里只陈列停产前的审计数据，不再新增，也不会注入提示词。",
    "mem.superseded": "已被新事实取代",
    "mem.supersededBy": "取代者 ID",
    "mem.evidence": "条证据",
    "mem.confidence": "置信度",
    "mem.procedural.empty": "暂无教学策略记录",
    "mem.procedural.emptyDesc": "程序性记忆记录各教学策略对该学生的成功率，需在真实教学中积累试用后产生。",
    "mem.trials": "次试用",
    "mem.trialsNote": "试用不足 3 次的策略不会注入教学提示，避免小样本噪音误导教学决策。",

    "pm.title": "提示词记忆（跨对话）",
    "pm.desc": "AI 在每次对话中实际携带的精简画像",
    "pm.note": "这就是 AI 跨对话记住你的内容：仅保留总体学习情况、当前水平、语气与讲解偏好四项，不存对话原文。觉得不准确？直接在对话中说明偏好，画像会随之更新。",
    "pm.inject": "每轮注入约",
    "pm.chars": "字",
    "pm.field.learning_summary": "总体学习情况",
    "pm.field.current_level": "当前水平",
    "pm.field.tone_preference": "语气偏好",
    "pm.field.explanation_preference": "讲解偏好",
    "pm.field.empty": "（暂无内容——完成几轮对话后自动生成）",
    "pm.window": "记忆窗口（最近会话数 5–30）",
    "pm.compacted": "已压缩 %n 个旧会话贡献",
    "pm.generation": "压缩第 %n 代",
    "pm.sessions": "记忆窗口内会话",
    "pm.sessions.empty": "窗口内暂无会话。",
    "pm.contributed": "有贡献",
    "pm.nocontrib": "无贡献",
    "pm.inWorkspace": "工作区",
    "pm.untitled": "（未命名会话）",
    "pm.compacted.note": "窗口外的会话贡献已折叠进画像汇总，不可按单个会话撤销；归档窗口内会话可即时撤销其贡献。",

    "ws.title": "工作区共同记忆",
    "ws.desc": "同一工作区的对话共享一份学习情况摘要，仅在该工作区内读取",
    "ws.loading": "加载中…",
    "ws.empty": "还没有工作区",
    "ws.empty.desc": "创建学习区后，同区对话会共享一份学习情况记忆，换对话也不用重新交代背景。",
    "ws.hasMemory": "有记忆",
    "ws.noMemory": "暂无记忆",
    "ws.noMemory.desc": "该工作区还没有形成共同记忆：完成一轮对话后会自动生成。",
    "ws.updated": "更新于",

    "ar.title": "学习内容档案",
    "ar.desc": "维护你的掌握度与计划，不会被注入对话提示词",
    "ar.boundary": "这些档案（学习账本、教学记录、编排计划）用于计算掌握度与生成计划，属于业务数据，不进入跨对话提示词记忆。",
    "ar.teaching": "教学档案（知识谱系）",
    "ar.orchestration": "编排档案（学习编排）",
    "ar.recent": "学习账本 · 最近作答",
    "ar.recent.empty": "还没有作答记录——在对话中做题或参加测评后产生。",
    "ar.correct": "对",
    "ar.partial": "部分对",
    "ar.wrong": "错",
    "ar.ungraded": "未判分",

    "audit.note": "以下为旧版系统留存数据，仅审计用途：情景/语义记忆已停产，不再新增，也不会注入提示词。新用户这里为空是正常的。",
  },
  en: {
    "mem.desc": "What the AI remembers: the cross-chat prompt profile, workspace shared memory, and learning archives.",
    "mem.tab.procedural": "Procedural",
    "mem.tab.audit": "Legacy audit (read-only)",
    "mem.error": "Failed to load memory data. Check the backend and retry.",
    "mem.disabled": "This intelligence layer is turned off via an environment switch; the memory module is not enabled.",
    "mem.episodes.empty": "No legacy episodic records",
    "mem.episodes.emptyDesc": "The legacy episodic log is retired: this lists audit data frozen before retirement. Your live learning activity now shows on the dashboard and in the learning archive.",
    "mem.loadMore": "Load more",
    "mem.loadingMore": "Loading…",
    "mem.importance": "Importance",
    "mem.semantic.empty": "No legacy semantic facts",
    "mem.semantic.emptyDesc": "The legacy semantic consolidation is retired: this lists audit data frozen before retirement — never injected into prompts.",
    "mem.superseded": "Superseded by a newer fact",
    "mem.supersededBy": "Superseded-by ID",
    "mem.evidence": "evidence",
    "mem.confidence": "Confidence",
    "mem.procedural.empty": "No strategy records yet",
    "mem.procedural.emptyDesc": "Procedural memory tracks each teaching strategy's success rate for this student; it accrues through real teaching trials.",
    "mem.trials": "trials",
    "mem.trialsNote": "Strategies with fewer than 3 trials are not injected into teaching prompts, keeping small-sample noise out of decisions.",

    "pm.title": "Prompt memory (cross-chat)",
    "pm.desc": "The bounded profile the AI actually carries into every chat",
    "pm.note": "This is what the AI remembers about you across chats: only four fields — overall learning status, current level, tone and explanation preferences. No chat transcripts. Inaccurate? Just say your preference in a chat and the profile updates.",
    "pm.inject": "≈",
    "pm.chars": "chars injected per turn",
    "pm.field.learning_summary": "Overall learning status",
    "pm.field.current_level": "Current level",
    "pm.field.tone_preference": "Tone preference",
    "pm.field.explanation_preference": "Explanation preference",
    "pm.field.empty": "(empty — generated automatically after a few chats)",
    "pm.window": "Memory window (recent chats 5–30)",
    "pm.compacted": "%n older session contributions compacted",
    "pm.generation": "compaction generation %n",
    "pm.sessions": "Chats inside the window",
    "pm.sessions.empty": "No chats inside the window yet.",
    "pm.contributed": "contributed",
    "pm.nocontrib": "no contribution",
    "pm.inWorkspace": "workspace",
    "pm.untitled": "(untitled chat)",
    "pm.compacted.note": "Contributions from chats outside the window are folded into the aggregate and cannot be undone per chat; archiving an in-window chat revokes its contribution immediately.",

    "ws.title": "Workspace shared memory",
    "ws.desc": "Chats in the same workspace share one learning-summary memory, readable only inside that workspace",
    "ws.loading": "Loading…",
    "ws.empty": "No workspaces yet",
    "ws.empty.desc": "Create a workspace and its chats will share a learning memory — no re-explaining context in every conversation.",
    "ws.hasMemory": "has memory",
    "ws.noMemory": "no memory yet",
    "ws.noMemory.desc": "This workspace has no shared memory yet: it is generated after the first chat turn.",
    "ws.updated": "Updated",

    "ar.title": "Learning archives",
    "ar.desc": "Maintains mastery and plans; never injected into chat prompts",
    "ar.boundary": "These archives (learning ledger, teaching log, orchestration plan) drive mastery and planning. They are business data and never enter the cross-chat prompt memory.",
    "ar.teaching": "Teaching archive (genealogy)",
    "ar.orchestration": "Plan archive (orchestration)",
    "ar.recent": "Learning ledger · recent answers",
    "ar.recent.empty": "No answers yet — produced by chat quizzes and assessments.",
    "ar.correct": "Correct",
    "ar.partial": "Partial",
    "ar.wrong": "Wrong",
    "ar.ungraded": "Ungraded",

    "audit.note": "Legacy system data kept for audit only: the episodic/semantic memory is retired — nothing new is appended and nothing here is injected into prompts. Empty is normal for new users.",
  },
} satisfies PageStrings;
