// 课堂模式页面词条（zh/en）。列表/详情/播放器共用；模式条等全局组件
// 的词条在 lib/i18n.ts。组件级词条（cls.phase.*/cls.regen.*/cls.voice.* 等）
// 以 components/classroom/strings.ts 为唯一来源，在此展开供本页 tr 使用
// （/course Hub 再展开本词典，两处文案保持一致）。
import type { PageStrings } from "@/lib/i18n-page";
import { STRINGS as CLS_COMPONENT_STRINGS } from "@/components/classroom/strings";

export const STRINGS: PageStrings = {
  zh: {
    "cls.export.title": "导出课件",
    ...CLS_COMPONENT_STRINGS.zh,
    "cls.list.title.suffix": "课堂",
    "cls.list.subtitle": "把学习区教材变成可讲授的课件",
    "cls.create": "一键备课",
    "cls.filter.all": "全部",
    "cls.filter.ready": "可上课",
    "cls.filter.generating": "生成中",
    "cls.card.pages": "%n 页",
    "cls.card.minutes": "%n 分钟",
    "cls.card.revision": "版本 %n",
    "cls.card.open": "打开课件",
    "cls.card.view": "查看进度",
    "cls.card.retry": "重试并重置额度",
    "cls.card.archive": "归档课程",
    "cls.archive.center": "归档中心",
    "cls.archive.title": "归档这门课程？",
    "cls.archive.desc": "「%s」将从课堂列表移入归档中心。正在生成的任务会停止；课件版本和课堂记录会一起保存，之后可以恢复或彻底删除。",
    "cls.archive.cancel": "取消",
    "cls.action.error": "操作失败，请重试",
    "cls.status.generating": "生成中",
    "cls.status.ready": "可上课",
    "cls.status.needs_attention": "需检查",
    "cls.status.failed": "失败",
    "cls.empty.title": "还没有课程",
    "cls.empty.desc": "选择本学习区的教材章节，或直接输入想学的主题——一键生成可讲授的课件。",
    "cls.empty.textbook": "从教材章节开始",
    "cls.empty.topic": "按主题备课",
    "cls.empty.general.hint": "没有教材也可以用「通识资料」生成主题课程。",
    "cls.empty.filtered": "该筛选下暂无课程",
    "cls.error.load": "课程列表加载失败",
    "cls.disabled.title": "课堂功能未开放",
    "cls.disabled.desc": "该账号当前不在课堂功能的开放范围内；已生成的课程不受影响。",
    "cls.retry": "重试",
    "cls.back.to.list": "返回课程列表",
    "cls.detail.preview": "课件预览",
    "cls.detail.noready.title": "课程尚未生成完成",
    "cls.detail.draft.open": "预览已生成的草稿页（带草稿水印）",
    "cls.export.zip": "下载课件",
    "cls.export.notes": "下载讲稿",
    "cls.detail.noready.desc": "生成完成后这里会展示可预览的课件。",
    "cls.detail.phase": "当前阶段",
    "cls.detail.notfound": "课程不存在或已被删除",
    "cls.detail.start": "开始上课",
    "cls.detail.continue": "继续上课",
    "cls.edit.unsaved": "课件编辑有未保存的修改，离开将丢失这些内容。选择「确定」放弃修改并前往，选择「取消」留在此页。",
    "cls.detail.starting": "正在准备课堂…",
    "cls.list.resume": "继续上课",
    "cls.list.resume.restart": "从头开始",
    "cls.list.resume.page": "第 %n / %t 页",
    "cls.learn.player.title": "课堂播放",
    "cls.learn.script": "本课讲稿",
    "cls.learn.coming.title": "播放器准备中",
    "cls.learn.coming.desc": "课堂播放器将在后续版本上线；当前可以回到课件预览查看内容。",
    "cls.learn.run": "课堂记录",
    "ws.notfound.title": "学习区不存在",
    "ws.notfound.desc": "这个学习区可能已被删除，或链接有误。",
  },
  en: {
    "cls.export.title": "Export",
    ...CLS_COMPONENT_STRINGS.en,
    "cls.list.title.suffix": "Classroom",
    "cls.list.subtitle": "Turn workspace textbooks into teachable lessons",
    "cls.create": "Quick lesson",
    "cls.filter.all": "All",
    "cls.filter.ready": "Ready",
    "cls.filter.generating": "Generating",
    "cls.card.pages": "%n slides",
    "cls.card.minutes": "%n min",
    "cls.card.revision": "Revision %n",
    "cls.card.open": "Open lesson",
    "cls.card.view": "View progress",
    "cls.card.retry": "Retry with fresh budget",
    "cls.card.archive": "Archive lesson",
    "cls.archive.center": "Archive",
    "cls.archive.title": "Archive this lesson?",
    "cls.archive.desc": "“%s” will move from the classroom list to the Archive Center. Active generation stops; revisions and class records are saved for restoration or permanent deletion.",
    "cls.archive.cancel": "Cancel",
    "cls.action.error": "Action failed. Please retry.",
    "cls.status.generating": "Generating",
    "cls.status.ready": "Ready",
    "cls.status.needs_attention": "Needs review",
    "cls.status.failed": "Failed",
    "cls.empty.title": "No lessons yet",
    "cls.empty.desc": "Pick textbook chapters from this workspace, or just type a topic — a teachable lesson is one click away.",
    "cls.empty.textbook": "Start from a chapter",
    "cls.empty.topic": "By topic",
    "cls.empty.general.hint": "No textbook? Topic lessons can still be generated from general knowledge.",
    "cls.empty.filtered": "No lessons under this filter",
    "cls.error.load": "Failed to load lessons",
    "cls.disabled.title": "Classroom not available",
    "cls.disabled.desc": "This account is not in the classroom rollout yet; existing lessons are unaffected.",
    "cls.retry": "Retry",
    "cls.back.to.list": "Back to lessons",
    "cls.detail.preview": "Lesson preview",
    "cls.detail.noready.title": "Lesson not ready yet",
    "cls.detail.draft.open": "Preview generated draft slides (watermarked)",
    "cls.export.zip": "Download deck",
    "cls.export.notes": "Download notes",
    "cls.detail.noready.desc": "The preview will appear once generation finishes.",
    "cls.detail.phase": "Current stage",
    "cls.detail.notfound": "Lesson not found or deleted",
    "cls.detail.start": "Start lesson",
    "cls.detail.continue": "Continue lesson",
    "cls.edit.unsaved": "The lesson editor has unsaved changes that will be lost. Choose OK to discard them and continue, or Cancel to stay.",
    "cls.detail.starting": "Preparing classroom…",
    "cls.list.resume": "Continue lesson",
    "cls.list.resume.restart": "Start over",
    "cls.list.resume.page": "Page %n of %t",
    "cls.learn.player.title": "Classroom",
    "cls.learn.script": "Full narration",
    "cls.learn.coming.title": "Player coming soon",
    "cls.learn.coming.desc": "The classroom player arrives in an upcoming release; preview the lesson content for now.",
    "cls.learn.run": "Session",
    "ws.notfound.title": "Workspace not found",
    "ws.notfound.desc": "This workspace may have been deleted, or the link is wrong.",
  },
};
