import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    "notes.title": "笔记仓库",
    "notes.desc": "Obsidian 式学习笔记 · AI 助手沉淀对话、教材与错题",
    "notes.all": "全部笔记",
    "notes.unfiled": "未分类",
    "notes.tags": "标签",
    "notes.search": "搜索笔记…",
    "notes.new": "新建笔记",
    "notes.newBlank": "空白笔记",
    "notes.generate": "AI 生成笔记",
    "notes.templates": "从模板新建",
    "notes.exportAll": "导出全部 (zip)",
    "notes.exportFolder": "导出此文件夹",
    "notes.newFolder": "新建文件夹",
    "notes.renameFolder": "重命名文件夹",
    "notes.rename": "重命名",
    "notes.export": "导出",
    "notes.delete": "删除",
    "notes.deleteFolder": "删除文件夹",
    "notes.deleteFolder.confirm": "删除文件夹后，其中的笔记会移入「未分类」，确认删除？",
    "notes.count": "{n} 篇",
    "notes.empty.title": "还没有笔记",
    "notes.empty.desc": "新建空白笔记、选择模板，或让 AI 根据对话/教材/错题生成一篇",
    "notes.open": "打开",
    // notes center（居中弹窗：文件夹/标签/列表/新建）
    "center.title": "笔记中心",
    "center.stats": "{n} 篇 · {m} 个文件夹",
    "center.folder.newChild": "创建子文件夹",
    "center.selected": "已选 {n} 篇",
    "center.move": "移动到",
    "center.empty": "没有符合条件的笔记",
    "center.clearFilters": "清除筛选",
    "center.selectAll": "全选",
    "center.bulkDelete": "删除 {n} 篇笔记",
    // toolbar
    "tb.untitled": "未命名笔记",
    "tb.center": "笔记总览",
    "tb.folder": "文件夹",
    "tb.tags": "标签",
    "tb.tagsPlaceholder": "回车添加标签",
    "tb.history": "历史版本",
    "tb.export": "导出 .md",
    "tb.delete": "删除笔记",
    "tb.delete.confirm": "笔记将移入回收站（可恢复），确认删除？",
    "tb.draft": "草稿",
    "tb.words": "{n} 字",
    "tb.saved": "已保存",
    "tb.saving": "保存中…",
    "tb.dirty": "未保存",
    "tb.error": "保存失败",
    "tb.conflict": "助手已更新此笔记",
    "tb.conflict.desc": "笔记助手在你编辑期间修改了这篇笔记。选择「载入最新」查看助手版本，或「覆盖保存」以你的版本为准（助手改动仍可在历史版本中找回）。",
    "tb.conflict.load": "载入最新",
    "tb.conflict.overwrite": "覆盖保存",
    "tb.autosaveHint": "自动保存已开启",
    "tb.toggleAi": "收起/展开笔记助手",
    "tb.settings": "笔记设置",
    "tb.focus": "专注模式",
    "tb.focus.exit": "退出专注 (Esc)",
    // editor
    "ed.edit": "编辑",
    "ed.preview": "预览",
    "ed.split": "分屏",
    "ed.placeholder": "开始书写笔记…支持 [[双链]]、$公式$、#标签、GFM 表格",
    "ed.bold": "加粗",
    "ed.italic": "斜体",
    "ed.strike": "删除线",
    "ed.code": "行内代码",
    "ed.codeblock": "代码块",
    "ed.h1": "标题一",
    "ed.h2": "标题二",
    "ed.h3": "标题三",
    "ed.quote": "引用",
    "ed.ul": "无序列表",
    "ed.ol": "有序列表",
    "ed.task": "任务列表",
    "ed.table": "表格",
    "ed.hr": "分割线",
    "ed.link": "链接",
    "ed.image": "图片",
    "ed.math": "行内公式",
    "ed.mathblock": "块级公式",
    "ed.wikilink": "笔记链接",
    "ed.createWiki": "新建笔记「{title}」",
    "ed.wikiPlaceholder": "输入笔记标题过滤…",
    "ed.backlinks": "反向链接",
    "ed.backlinks.empty": "暂无其他笔记链接到本篇",
    "ed.linkUnresolved": "未解析：点击创建",
    // AI panel（每笔记专属智能体：问答/计划/授权三模式）
    "ai.title": "笔记助手",
    "ai.context.note": "当前笔记",
    "ai.context.vault": "仓库助手",
    "ai.mode.pick": "助手模式",
    "ai.mode.ask": "问答",
    "ai.mode.ask.desc": "只回答问题，可读其他笔记与教材，不改动任何笔记",
    "ai.mode.plan": "计划",
    "ai.mode.plan.desc": "讨论并产出修改计划卡；批复后自动进入授权执行",
    "ai.mode.authorize": "授权",
    "ai.mode.authorize.desc": "直接修改当前笔记（不能新建、不能改其他笔记，进历史版本可回滚）",
    "ai.placeholder": "向这篇笔记的专属助手提问或安排整理…",
    "ai.empty": "还没有对话。每篇笔记的助手互相独立，切换笔记即切换对话。",
    "ai.send": "发送",
    "ai.stop": "停止",
    "ai.upload": "上传图片（OCR + 视觉理解）",
    "ai.upload.ocr": "正在识别图片…",
    "ai.upload.limit": "最多 {n} 张图片",
    "ai.upload.unsupported": "仅支持图片文件",
    "ai.ocr.preview": "图片内容预览",
    "ai.img.default": "请结合图片内容回答。",
    "ai.clear": "清空对话",
    "ai.clear.confirm": "清空与这篇笔记助手的对话记录？（模式选择保留）",
    "ai.plan.card": "修改计划",
    "ai.plan.pending": "有计划待批复",
    "ai.plan.approve": "批准并执行",
    "ai.plan.reject": "拒绝",
    "ai.plan.status.pending": "待批复",
    "ai.plan.status.approved": "执行中",
    "ai.plan.status.executed": "已执行",
    "ai.plan.status.rejected": "已驳回",
    "ai.plan.steps": "步骤",
    "ai.plan.approving": "正在按计划执行…",
    "ai.plan.rejected.toast": "已驳回该计划，可继续讨论新方案",
    "ai.updated": "助手已更新《{title}》",
    "ai.remote.banner": "助手已更新本笔记，你的编辑尚未保存",
    "ai.remote.loadLatest": "载入最新",
    "ai.remote.keepMine": "保留我的",
    "ai.thinking": "深度思考",
    "ai.tool": "执行 {name}…",
    "ai.copy": "复制",
    "ai.copied": "已复制",
    "ai.error": "助手出错",
    // generate wizard
    "gw.title": "AI 生成笔记",
    "gw.step.template": "选择模板",
    "gw.step.sources": "选择来源",
    "gw.step.confirm": "确认生成",
    "gw.template.mistake_correction": "错题修正",
    "gw.template.knowledge_summary": "知识点总结",
    "gw.template.review_note": "学习温故",
    "gw.template.chapter_notes": "章节笔记",
    "gw.template.conversation_digest": "对话总结",
    "gw.next": "下一步",
    "gw.back": "上一步",
    "gw.generate": "开始生成",
    "gw.sessions": "对话历史",
    "gw.sessions.desc": "选择要沉淀的辅导对话（可多选）；教材与文件自动取对话中引用的内容",
    "gw.textbooks": "教材",
    "gw.textbooks.desc": "选择作为知识来源的教材（可多选）",
    "gw.workspace": "工作区",
    "gw.sourceMode": "来源类型",
    "gw.sourceMode.sessions": "从对话生成",
    "gw.sourceMode.sessions.desc": "选一个或几个对话，教材与文件直接用对话中引用的",
    "gw.sourceMode.workspace": "从工作区生成",
    "gw.sourceMode.workspace.desc": "用工作区的教材；可限定工作区下的某些对话或整个工作区",
    "gw.sourceMode.textbooks": "从教材生成",
    "gw.sourceMode.textbooks.desc": "直接对一本或几本教材写笔记",
    "gw.workspace.pick": "选择工作区",
    "gw.workspace.sessions": "限定对话（可选）",
    "gw.workspace.sessions.desc": "不选 = 整个工作区；所选对话额外引用的教材也会纳入",
    "gw.retrieve.hint": "生成时会自动检索所选来源中的相关片段作为依据",
    "gw.errorNotebook": "错题本",
    "gw.errorNotebook.desc": "从最近错题中提炼（M4/M7 错题记录）",
    "gw.instructions": "补充要求（可选）",
    "gw.instructions.placeholder": "例如：只总结前两章、重点记录我答错的部分…",
    "gw.selectAtLeastOne": "请至少选择一个来源",
    "gw.generating": "正在生成…",
    "gw.collected": "已收集 {sessions} 个对话 · {textbooks} 本教材 · 检索到 {retrieved} 个相关片段",
    "gw.done": "已生成",
    "gw.openNote": "打开笔记",
    "gw.error": "生成失败",
    // revisions
    "rev.title": "历史版本",
    "rev.author.user": "我",
    "rev.author.agent": "助手",
    "rev.restore": "恢复此版本",
    "rev.view": "查看",
    "rev.empty": "暂无历史版本",
    "rev.restore.confirm": "用版本 {n} 的内容替换当前正文？",
    "rev.current": "当前",
    // graph
    "graph.title": "笔记关系图",
    "graph.empty": "还没有笔记或链接",
    "graph.loading": "正在加载关系图…",
    "graph.toggle.chats": "聊天",
    "graph.toggle.textbooks": "教材",
    "graph.hint": "拖拽平移 · 滚轮缩放 · 点按文字跳转",
    "graph.zoom.out": "缩小",
    "graph.zoom.in": "放大",
    "graph.zoom.fit": "适应画布",
    "graph.zoom.reset": "重置视图",
    "graph.kind.note": "笔记",
    "graph.kind.session": "聊天",
    "graph.kind.notes_thread": "助手线程",
    "graph.kind.textbook": "教材",
    "graph.kind.ghost": "未解析",
    "graph.info.kind": "类型",
    "graph.info.degree": "关联",
    "graph.info.folder": "文件夹",
    "graph.info.messages": "消息",
    "graph.status.deleted": "已删除",
    "graph.status.missing": "无法解析",
    "graph.alert.deleted": "该资源已被删除",
    "graph.alert.missing": "该资源不存在或无法访问",
    // misc
    "notes.error.load": "笔记仓库加载失败",
    "notes.retry": "重试",
    "notes.cancel": "取消",
    "notes.deleted": "已移入回收站",
    "notes.confirmDelete": "删除后将移入回收站，可从归档中心恢复",
  },
  en: {
    "notes.title": "Notes Vault",
    "notes.desc": "Obsidian-style study notes · AI distills chats, textbooks & mistakes",
    "notes.all": "All notes",
    "notes.unfiled": "Unfiled",
    "notes.tags": "Tags",
    "notes.search": "Search notes…",
    "notes.new": "New note",
    "notes.newBlank": "Blank note",
    "notes.generate": "Generate with AI",
    "notes.templates": "From template",
    "notes.exportAll": "Export all (zip)",
    "notes.exportFolder": "Export this folder",
    "notes.newFolder": "New folder",
    "notes.renameFolder": "Rename folder",
    "notes.rename": "Rename",
    "notes.export": "Export",
    "notes.delete": "Delete",
    "notes.deleteFolder": "Delete folder",
    "notes.deleteFolder.confirm": "Notes in this folder will move to Unfiled. Delete?",
    "notes.count": "{n} notes",
    "notes.empty.title": "No notes yet",
    "notes.empty.desc": "Create a blank note, pick a template, or let AI generate one from chats/textbooks/mistakes",
    "notes.open": "Open",
    "center.title": "Notes center",
    "center.stats": "{n} notes · {m} folders",
    "center.folder.newChild": "New subfolder",
    "center.selected": "{n} selected",
    "center.move": "Move to",
    "center.empty": "No notes match",
    "center.clearFilters": "Clear filters",
    "center.selectAll": "Select all",
    "center.bulkDelete": "Delete {n} notes",
    "tb.untitled": "Untitled",
    "tb.center": "Notes overview",
    "tb.folder": "Folder",
    "tb.tags": "Tags",
    "tb.tagsPlaceholder": "Enter to add tag",
    "tb.history": "History",
    "tb.export": "Export .md",
    "tb.delete": "Delete note",
    "tb.delete.confirm": "The note will be moved to trash (recoverable). Delete?",
    "tb.draft": "Draft",
    "tb.words": "{n} chars",
    "tb.saved": "Saved",
    "tb.saving": "Saving…",
    "tb.dirty": "Unsaved",
    "tb.error": "Save failed",
    "tb.conflict": "Assistant updated this note",
    "tb.conflict.desc": "The notes agent modified this note while you were editing. Load the latest, or overwrite with your version (the agent's edit stays recoverable in history).",
    "tb.conflict.load": "Load latest",
    "tb.conflict.overwrite": "Overwrite",
    "tb.autosaveHint": "Autosave on",
    "tb.toggleAi": "Toggle notes assistant",
    "tb.settings": "Note settings",
    "tb.focus": "Focus mode",
    "tb.focus.exit": "Exit focus (Esc)",
    "ed.edit": "Edit",
    "ed.preview": "Preview",
    "ed.split": "Split",
    "ed.placeholder": "Start writing… supports [[wikilinks]], $math$, #tags, GFM tables",
    "ed.bold": "Bold",
    "ed.italic": "Italic",
    "ed.strike": "Strikethrough",
    "ed.code": "Inline code",
    "ed.codeblock": "Code block",
    "ed.h1": "Heading 1",
    "ed.h2": "Heading 2",
    "ed.h3": "Heading 3",
    "ed.quote": "Quote",
    "ed.ul": "Bullet list",
    "ed.ol": "Numbered list",
    "ed.task": "Task list",
    "ed.table": "Table",
    "ed.hr": "Divider",
    "ed.link": "Link",
    "ed.image": "Image",
    "ed.math": "Inline math",
    "ed.mathblock": "Math block",
    "ed.wikilink": "Note link",
    "ed.createWiki": "Create note “{title}”",
    "ed.wikiPlaceholder": "Filter note titles…",
    "ed.backlinks": "Backlinks",
    "ed.backlinks.empty": "No notes link here yet",
    "ed.linkUnresolved": "Unresolved: click to create",
    "ai.title": "Notes assistant",
    "ai.context.note": "Current note",
    "ai.context.vault": "Vault assistant",
    "ai.mode.pick": "Assistant mode",
    "ai.mode.ask": "Ask",
    "ai.mode.ask.desc": "Answers only; may read other notes and textbooks, never edits",
    "ai.mode.plan": "Plan",
    "ai.mode.plan.desc": "Discusses and produces a plan card; approving switches to authorized execution",
    "ai.mode.authorize": "Authorize",
    "ai.mode.authorize.desc": "Edits this note directly (no creating or touching other notes; versioned and revertible)",
    "ai.placeholder": "Ask this note's dedicated assistant…",
    "ai.empty": "No messages yet. Each note has its own assistant; switching notes switches the chat.",
    "ai.send": "Send",
    "ai.stop": "Stop",
    "ai.upload": "Upload image (OCR + vision)",
    "ai.upload.ocr": "Reading image…",
    "ai.upload.limit": "Up to {n} images",
    "ai.upload.unsupported": "Image files only",
    "ai.ocr.preview": "OCR preview",
    "ai.img.default": "Please answer based on the image.",
    "ai.clear": "Clear chat",
    "ai.clear.confirm": "Clear this note's assistant conversation? (mode is kept)",
    "ai.plan.card": "Change plan",
    "ai.plan.pending": "Plan awaiting approval",
    "ai.plan.approve": "Approve & run",
    "ai.plan.reject": "Reject",
    "ai.plan.status.pending": "Awaiting approval",
    "ai.plan.status.approved": "Running",
    "ai.plan.status.executed": "Executed",
    "ai.plan.status.rejected": "Rejected",
    "ai.plan.steps": "Steps",
    "ai.plan.approving": "Executing the approved plan…",
    "ai.plan.rejected.toast": "Plan rejected — keep discussing a new approach",
    "ai.updated": "Assistant updated “{title}”",
    "ai.remote.banner": "Assistant updated this note; your edits are unsaved",
    "ai.remote.loadLatest": "Load latest",
    "ai.remote.keepMine": "Keep mine",
    "ai.thinking": "Deep thinking",
    "ai.tool": "Running {name}…",
    "ai.copy": "Copy",
    "ai.copied": "Copied",
    "ai.error": "Assistant error",
    "gw.title": "Generate note with AI",
    "gw.step.template": "Template",
    "gw.step.sources": "Sources",
    "gw.step.confirm": "Confirm",
    "gw.template.mistake_correction": "Mistake correction",
    "gw.template.knowledge_summary": "Knowledge summary",
    "gw.template.review_note": "Review note",
    "gw.template.chapter_notes": "Chapter notes",
    "gw.template.conversation_digest": "Chat digest",
    "gw.next": "Next",
    "gw.back": "Back",
    "gw.generate": "Generate",
    "gw.sessions": "Conversations",
    "gw.sessions.desc": "Pick chats to distill (multi-select); textbooks and files come from what those chats referenced",
    "gw.textbooks": "Textbooks",
    "gw.textbooks.desc": "Pick textbook sources (multi-select)",
    "gw.workspace": "Workspace",
    "gw.sourceMode": "Source type",
    "gw.sourceMode.sessions": "From conversations",
    "gw.sourceMode.sessions.desc": "Pick one or more chats; textbooks/files follow what they referenced",
    "gw.sourceMode.workspace": "From workspace",
    "gw.sourceMode.workspace.desc": "Use workspace textbooks; limit to selected chats or the whole workspace",
    "gw.sourceMode.textbooks": "From textbooks",
    "gw.sourceMode.textbooks.desc": "Write notes directly against one or more textbooks",
    "gw.workspace.pick": "Pick a workspace",
    "gw.workspace.sessions": "Limit to chats (optional)",
    "gw.workspace.sessions.desc": "None = the whole workspace; extra textbooks referenced by selected chats are included",
    "gw.retrieve.hint": "Relevant passages from the chosen sources are retrieved automatically",
    "gw.errorNotebook": "Error notebook",
    "gw.errorNotebook.desc": "Distill from recent mistakes (M4/M7 records)",
    "gw.instructions": "Extra instructions (optional)",
    "gw.instructions.placeholder": "e.g. only chapters 1-2, focus on what I got wrong…",
    "gw.selectAtLeastOne": "Pick at least one source",
    "gw.generating": "Generating…",
    "gw.collected": "Collected {sessions} chats · {textbooks} textbooks · retrieved {retrieved} passages",
    "gw.done": "Generated",
    "gw.openNote": "Open note",
    "gw.error": "Generation failed",
    "rev.title": "History",
    "rev.author.user": "Me",
    "rev.author.agent": "Assistant",
    "rev.restore": "Restore",
    "rev.view": "View",
    "rev.empty": "No revisions yet",
    "rev.restore.confirm": "Replace current content with revision {n}?",
    "rev.current": "Current",
    "graph.title": "Notes graph",
    "graph.empty": "No notes or links yet",
    "graph.loading": "Loading graph…",
    "graph.toggle.chats": "Chats",
    "graph.toggle.textbooks": "Textbooks",
    "graph.hint": "Drag to pan · scroll to zoom · click a label to open",
    "graph.zoom.out": "Zoom out",
    "graph.zoom.in": "Zoom in",
    "graph.zoom.fit": "Fit to canvas",
    "graph.zoom.reset": "Reset view",
    "graph.kind.note": "Note",
    "graph.kind.session": "Chat",
    "graph.kind.notes_thread": "Assistant thread",
    "graph.kind.textbook": "Textbook",
    "graph.kind.ghost": "Unresolved",
    "graph.info.kind": "Type",
    "graph.info.degree": "Links",
    "graph.info.folder": "Folder",
    "graph.info.messages": "Messages",
    "graph.status.deleted": "Deleted",
    "graph.status.missing": "Unavailable",
    "graph.alert.deleted": "This resource has been deleted",
    "graph.alert.missing": "This resource is missing or inaccessible",
    "notes.error.load": "Failed to load the notes vault",
    "notes.retry": "Retry",
    "notes.cancel": "Cancel",
    "notes.deleted": "Moved to trash",
    "notes.confirmDelete": "The note will be moved to trash and can be restored from the archive",
  },
};
