#!/usr/bin/env python3
"""从 services/api/app/schemas/* 生成共享 TypeScript 契约类型（见 scripts/contracts/README.md）。

事实源是服务端 Pydantic 模型；本脚本把每个 schema 模块的
PUBLIC_TYPE_MODELS / PUBLIC_TYPE_UNIONS 确定性渲染为
packages/contracts/src/generated/*.ts，供 Web 与 Mobile 共同消费。
生成文件禁止手改；CI 用 `--check` 比较生成结果，漂移即阻断合并。

本脚本是仓库唯一的类型生成器：classroom/assistant 的旧生成脚本已合并到
这里并被删除，不允许再出现第二套生成路径。

用法：
  python scripts/contracts/generate_types.py            # 生成/覆盖全部目标
  python scripts/contracts/generate_types.py --check    # 只比较，不一致退出 1
  python scripts/contracts/generate_types.py illustration   # 仅生成单个目标
"""
from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "packages" / "contracts" / "src" / "generated"

# 目标注册表：schema 模块 -> 输出文件。新领域契约在此登记。
TARGETS: dict[str, str] = {
    "classroom": "app.schemas.classroom",
    "assistant": "app.schemas.assistant",
    "illustration": "app.schemas.illustration",
    "worksheet": "app.schemas.worksheet",
}

_REF_RE = re.compile(r"^#/(?:definitions|\$defs)/(.+)$")


def _ref_name(ref: str) -> str:
    m = _REF_RE.match(ref)
    if not m:
        raise ValueError(f"无法解析 $ref: {ref}")
    return m.group(1)


def _ts_type(prop: dict) -> str:
    if "$ref" in prop:
        return _ref_name(prop["$ref"])
    if "oneOf" in prop:
        return " | ".join(_ts_type(sub) for sub in prop["oneOf"])
    if "anyOf" in prop:
        parts: list[str] = []
        for sub in prop["anyOf"]:
            t = _ts_type(sub)
            if t not in parts:
                parts.append(t)
        return " | ".join(parts)
    if "enum" in prop:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in prop["enum"])
    if "const" in prop:
        return json.dumps(prop["const"], ensure_ascii=False)
    t = prop.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in prop:
            return "[" + ", ".join(_ts_type(p) for p in prop["prefixItems"]) + "]"
        item = prop.get("items", {})
        return f"Array<{_ts_type(item)}>"
    if t == "object" or "additionalProperties" in prop:
        ap = prop.get("additionalProperties", True)
        if isinstance(ap, dict):
            return f"Record<string, {_ts_type(ap)}>"
        return "Record<string, unknown>"
    return "unknown"


def _render_model(name: str, defn: dict) -> str:
    if "enum" in defn:
        values = " | ".join(json.dumps(v, ensure_ascii=False) for v in defn["enum"])
        return f"export type {name} = {values};"
    if "oneOf" in defn or "anyOf" in defn:
        return f"export type {name} = {_ts_type(defn)};"
    props = defn.get("properties", {})
    required = set(defn.get("required", []))
    lines = [f"export interface {name} {{"]
    for fname, fprop in props.items():
        opt = "" if fname in required else "?"
        lines.append(f"  {fname}{opt}: {_ts_type(fprop)};")
    lines.append("}")
    return "\n".join(lines)


def generate_target(name: str, schema_module: str) -> str:
    sys.path.insert(0, str(ROOT / "services" / "api"))
    import pydantic

    try:
        sc = importlib.import_module(schema_module)
    except ImportError as exc:  # pragma: no cover - environment guard
        raise SystemExit(f"[contracts] 无法导入 {schema_module}: {exc}")

    models = []
    for model_name in sc.PUBLIC_TYPE_MODELS:
        model = getattr(sc, model_name, None)
        if model is None:
            raise ValueError(f"{schema_module}.PUBLIC_TYPE_MODELS 引用了不存在的模型: {model_name}")
        models.append(model)
    namespace = pydantic.create_model(
        "_ContractTypeNamespace", **{m.__name__: (m, ...) for m in models})
    schema = namespace.model_json_schema(ref_template="#/definitions/{model}")
    defs = schema.get("$defs", {})

    header = (
        f"// AUTO-GENERATED by scripts/contracts/generate_types.py — DO NOT EDIT.\n"
        f"// Source of truth: services/api/{schema_module.replace('.', '/')}.py\n"
        f"// Regenerate with: pnpm contracts:generate (repo root)\n"
    )
    blocks = [header]
    for model in models:
        if model.__name__ not in defs:
            raise ValueError(f"模型 {model.__name__} 未出现在 JSON schema defs 中")
        blocks.append(_render_model(model.__name__, defs[model.__name__]))
    for alias, members in sc.PUBLIC_TYPE_UNIONS.items():
        missing = [m for m in members if m not in defs]
        if missing:
            raise ValueError(f"联合类型 {alias} 引用了未导出的模型: {missing}")
        blocks.append(f"export type {alias} = {' | '.join(members)};")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="只比较生成结果与现有文件，不写入")
    parser.add_argument("target", nargs="?", choices=sorted(TARGETS),
                        help="仅处理单个目标（缺省全部）")
    args = parser.parse_args()

    names = [args.target] if args.target else sorted(TARGETS)
    failed = False
    for name in names:
        content = generate_target(name, TARGETS[name])
        out_path = OUT_DIR / f"{name}.ts"
        if args.check:
            if not out_path.exists():
                print(f"[contracts] 缺少生成文件: {out_path}", file=sys.stderr)
                failed = True
                continue
            if out_path.read_text(encoding="utf-8") != content:
                print(f"[contracts] 生成结果与 {out_path} 不一致，请运行 `pnpm contracts:generate`",
                      file=sys.stderr)
                failed = True
                continue
            print(f"[contracts] OK: {out_path} 与 schema 一致")
        else:
            OUT_DIR.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            print(f"[contracts] 已生成 {out_path}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
