import type { PageStrings } from "@/lib/i18n-page";

/**
 * 落地页（/）页面级词条：zh/en 双语。
 * 通过 makePageT 与全局词典合并（本文件优先），无需改动 lib/i18n.ts。
 */
export const LANDING_STRINGS: PageStrings = {
  zh: {
    "landing.nav.features": "功能",
    "landing.nav.modules": "模块",
    "landing.nav.how": "如何开始",
    "landing.nav.docs": "使用文档",
    "landing.nav.login": "登录",
    "landing.nav.start": "注册",
    "landing.nav.workspace": "进入工作区",

    "landing.hero.kicker": "M0–M10 · 多智能体辅导系统",
    "landing.hero.title.a": "Next Tutor Agent",
    "landing.hero.title.b": "你的专属教育智能体",
    "landing.hero.subtitle":
      "讲解、出题、答疑，全部基于真实教材。十层智能模块协同编排，记住你学过什么，知道下一步该怎么教。",
    "landing.hero.primary": "免费开始",
    "landing.hero.secondary": "已有账号，登录",
    "landing.hero.workspace": "进入工作区",
    "landing.hero.scroll": "向下滚动",
    "landing.hero.vertical": "因材施教 · 有教无类",

    "landing.marquee.1": "苏格拉底式讲解",
    "landing.marquee.2": "CAT 自适应测评",
    "landing.marquee.3": "教材 RAG 检索",
    "landing.marquee.4": "BKT 掌握度追踪",
    "landing.marquee.5": "SM-2 间隔重复",
    "landing.marquee.6": "教材知识图谱",
    "landing.marquee.7": "六模式教学引擎",
    "landing.marquee.8": "长期学习记忆",

    "landing.features.kicker": "功能 / Features",
    "landing.features.title": "一位真正懂教学的 AI",
    "landing.features.subtitle":
      "不只是聊天机器人——每一轮对话背后，都有教学策略、掌握度追踪与教材依据。",
    "landing.features.f1.title": "苏格拉底式讲解",
    "landing.features.f1.desc": "循循善诱的对话式讲解，引导你自己想明白，而不是直接给出答案。",
    "landing.features.f1.more":
      "六模式教学引擎（M3）会根据你的基础与当前状态，在讲解、引导、追问、纠错等模式间切换。苏格拉底模式下，它用一连串递进的小问题带你推出答案，卡住时给分级提示——先思路、再关键步骤、最后才是结论。",
    "landing.features.f1.p1": "六模式状态机 + 跨轮教学记忆，教学策略随对话推进",
    "landing.features.f1.p2": "分级提示：先给思路，再给关键步骤，最后才是答案",
    "landing.features.f1.p3": "每轮讲解自动关联教材概念，出处可溯源",
    "landing.features.f2.title": "智能出题测评",
    "landing.features.f2.desc": "约束出题、三级评分与 CAT 自适应测试，真实检验「学会了没有」。",
    "landing.features.f2.more":
      "M4 测评智能在出题时施加教材与知识点约束，杜绝超纲题；作答按三级评分精细判定；CAT 自适应测试根据你的作答实时调整下一题难度，用更少的题精确定位真实水平，结果直接回写掌握度模型。",
    "landing.features.f2.p1": "约束出题：题目严格限定在所选教材与知识点内",
    "landing.features.f2.p2": "三级评分：完全正确 / 部分正确 / 错误，精细回写掌握度",
    "landing.features.f2.p3": "CAT 自适应：难度随作答动态调整，短测验也有高信度",
    "landing.features.f3.title": "教材 RAG 检索",
    "landing.features.f3.desc": "回答基于你选用的教材内容，概念出处可溯源，拒绝凭空发挥。",
    "landing.features.f3.more":
      "每轮回答前，系统先从你关联的教材中检索最相关的片段（检索增强生成），再基于检索结果组织作答，从机制上抑制凭空发挥；概念与出处随回答呈现，可随时回到教材原文核对。",
    "landing.features.f3.p1": "上传教材自动解析、分块与向量化入库",
    "landing.features.f3.p2": "回答附带教材出处，概念可溯源",
    "landing.features.f3.p3": "公共教材全员可读，私有上传仅自己可见",
    "landing.features.f4.title": "学习笔记",
    "landing.features.f4.desc": "边学边记，笔记与对话联动，把知识沉淀成你自己的资料库。",
    "landing.features.f4.more":
      "笔记仓库是一个 Obsidian 式双链知识库：[[双链]] 把概念连成网络，AI 可以从辅导对话、教材或错题本一键生成笔记；开启 SM-2 温故后，到期笔记自动进入复习安排，配合关系图总览全局。",
    "landing.features.f4.p1": "[[双链]] + 标签 + 文件夹，未解析链接一键成篇",
    "landing.features.f4.p2": "AI 从对话 / 教材 / 错题生成：总结、修正、温故",
    "landing.features.f4.p3": "SM-2 间隔复习 + 力导向关系图，笔记与对话联动",
    "landing.features.f5.title": "学情画像",
    "landing.features.f5.desc": "BKT 掌握度追踪与知识图谱可视化，强项弱项一目了然。",
    "landing.features.f5.more":
      "M2 学生模型用 BKT（贝叶斯知识追踪）从你的作答序列持续估计每个概念的掌握概率；学习总览与我的画像把掌握度、概念状态与学习风格画成可读的图谱与曲线，强项弱项一目了然。",
    "landing.features.f5.p1": "BKT 按概念估计掌握概率，作答越多越准",
    "landing.features.f5.p2": "教材知识图谱叠加掌握度着色，弱项一眼可见",
    "landing.features.f5.p3": "画像透明可查：系统对你的理解全部展示",
    "landing.features.f6.title": "长期学习编排",
    "landing.features.f6.desc": "从学期目标到今日任务，SM-2 间隔重复帮你对抗遗忘。",
    "landing.features.f6.more":
      "设定一个或多个学期目标后，M9 编排智能把它们分解为周任务 → 今日任务，并把 SM-2 到期复习织进每日安排；完成情况回流掌握度模型，下一周的计划随之自动调整。",
    "landing.features.f6.p1": "多目标 → 周 → 今日，任务自动分解",
    "landing.features.f6.p2": "SM-2 间隔重复对抗遗忘，复习自动排期",
    "landing.features.f6.p3": "任务完成回流掌握度，计划动态调整",
    "landing.features.f7.title": "语音通话讲解",
    "landing.features.f7.desc": "像打电话一样开口提问，公式也能听得懂、看得清。",
    "landing.features.f7.more":
      "打开语音通话，说题即答，回答逐句转成语音播报。回答里的分数、根号、上下标、求和与积分会自动转成自然的中文口语读法，不再是念不出来的符号串；同时板书区把正在讲解的公式实时写成排版好的 LaTeX，听不清时抬眼就能对照。",
    "landing.features.f7.p1": "实时语音对话：说题即答，适合口算演练与长题推导",
    "landing.features.f7.p2": "公式朗读：分数、根号、上下标、积分求和自动转中文读法",
    "landing.features.f7.p3": "板书同步：讲到哪个公式，黑板就实时写出哪个公式",

    "landing.modules.kicker": "架构 / Architecture",
    "landing.modules.title": "M0–M10 · 十层智能模块",
    "landing.modules.subtitle": "每一轮对话，都经过一条完整的多智能体编排流水线。",
    "landing.modules.m0.name": "身份基础设施",
    "landing.modules.m0.desc": "用户是谁、数据属于谁、如何安全访问",
    "landing.modules.m1.name": "任务智能",
    "landing.modules.m1.desc": "理解 → 规划 → 工具执行 → 状态更新",
    "landing.modules.m2.name": "学生模型",
    "landing.modules.m2.desc": "学习画像 + BKT 掌握度 + 概念状态",
    "landing.modules.m3.name": "教学引擎",
    "landing.modules.m3.desc": "六模式状态机 + 跨轮教学记忆",
    "landing.modules.m4.name": "测评智能",
    "landing.modules.m4.desc": "三级评分 + 约束出题 + CAT 自适应测试",
    "landing.modules.m5.name": "知识智能",
    "landing.modules.m5.desc": "教材知识图谱 + 概念检索",
    "landing.modules.m6.name": "记忆智能",
    "landing.modules.m6.desc": "有界画像 + 策略聚合，越用越懂你",
    "landing.modules.m7.name": "评估改进",
    "landing.modules.m7.desc": "教学自诊断，让学习智能体越教越好",
    "landing.modules.m8.name": "交互体验",
    "landing.modules.m8.desc": "表达方式适配每个学生的偏好",
    "landing.modules.m9.name": "学习编排",
    "landing.modules.m9.desc": "多目标 → 周任务 → 今日任务",
    "landing.modules.m10.name": "能力运行时",
    "landing.modules.m10.desc": "技能调用契约与学习证据门",

    "landing.how.kicker": "开始使用 / Getting started",
    "landing.how.title": "三步，开始你的第一课",
    "landing.how.s1.title": "创建账号",
    "landing.how.s1.desc": "注册即得专属学习空间，所有数据完全隔离。",
    "landing.how.s2.title": "提问或选教材",
    "landing.how.s2.desc": "直接使用公共教材，或上传你自己的资料，然后尽管提问。",
    "landing.how.s3.title": "持续进步",
    "landing.how.s3.desc": "系统追踪你的掌握度，自动安排复习与测评。",

    "landing.cta.title": "准备好开始了吗？",
    "landing.cta.subtitle": "免费创建账号，让学习智能体为你定制第一课。",
    "landing.cta.button": "免费开始",
    "landing.cta.workspace": "进入工作区",

    "landing.footer.docs": "文档",
    "landing.footer.login": "登录",
    "landing.footer.register": "注册",
  },
  en: {
    "landing.nav.features": "Features",
    "landing.nav.modules": "Modules",
    "landing.nav.how": "How it works",
    "landing.nav.docs": "Usage docs",
    "landing.nav.login": "Sign in",
    "landing.nav.start": "Sign up",
    "landing.nav.workspace": "Open workspace",

    "landing.hero.kicker": "M0–M10 · Multi-agent tutoring",
    "landing.hero.title.a": "Next Tutor Agent",
    "landing.hero.title.b": "Your personal tutor agent",
    "landing.hero.subtitle":
      "Explain, quiz, and Q&A — all grounded in real textbooks. Ten intelligence modules work in concert, remember what you've learned, and know how to teach next.",
    "landing.hero.primary": "Get started free",
    "landing.hero.secondary": "Sign in",
    "landing.hero.workspace": "Open workspace",
    "landing.hero.scroll": "Scroll",
    "landing.hero.vertical": "EVERY STUDENT · A TUTOR",

    "landing.marquee.1": "Socratic Tutoring",
    "landing.marquee.2": "CAT Adaptive Testing",
    "landing.marquee.3": "Textbook RAG",
    "landing.marquee.4": "BKT Mastery Tracking",
    "landing.marquee.5": "SM-2 Spaced Repetition",
    "landing.marquee.6": "Knowledge Graph",
    "landing.marquee.7": "Six-Mode Teaching Engine",
    "landing.marquee.8": "Long-Term Memory",

    "landing.features.kicker": "Features",
    "landing.features.title": "An AI that actually teaches",
    "landing.features.subtitle":
      "Not just a chatbot — behind every turn there is pedagogy, mastery tracking, and textbook evidence.",
    "landing.features.f1.title": "Socratic explaining",
    "landing.features.f1.desc":
      "Guided dialogue that helps you figure things out yourself instead of handing you answers.",
    "landing.features.f1.more":
      "A six-mode teaching engine (M3) switches between explaining, guiding, probing and correcting based on your state. In Socratic mode it walks you through progressive questions with tiered hints — approach first, key steps next, the answer last.",
    "landing.features.f1.p1": "Six-mode state machine with cross-turn teaching memory",
    "landing.features.f1.p2": "Tiered hints: approach first, key steps next, answer last",
    "landing.features.f1.p3": "Every explanation links back to textbook concepts",
    "landing.features.f2.title": "Smart assessment",
    "landing.features.f2.desc":
      "Constrained quiz generation, three-level grading, and CAT adaptive testing that verify real mastery.",
    "landing.features.f2.more":
      "M4 constrains question generation to your chosen textbooks and topics — no out-of-scope items. Answers are graded on three levels, and CAT adaptive testing adjusts difficulty after every answer to pinpoint your level with fewer questions, writing results straight into the mastery model.",
    "landing.features.f2.p1": "Constrained generation — strictly within selected textbooks and topics",
    "landing.features.f2.p2": "Three-level grading writes fine-grained mastery updates",
    "landing.features.f2.p3": "CAT adapts difficulty live for precise, shorter tests",
    "landing.features.f3.title": "Textbook RAG",
    "landing.features.f3.desc":
      "Answers grounded in your chosen textbooks, with traceable concept sources — no hallucinated facts.",
    "landing.features.f3.more":
      "Before every answer the system retrieves the most relevant passages from your textbooks (retrieval-augmented generation) and grounds the response in them — hallucination is suppressed by design. Sources are shown alongside so you can verify against the original text.",
    "landing.features.f3.p1": "Uploads are parsed, chunked and vectorized automatically",
    "landing.features.f3.p2": "Answers carry textbook sources — traceable concepts",
    "landing.features.f3.p3": "Public textbooks for everyone; private uploads stay private",
    "landing.features.f4.title": "Study notes",
    "landing.features.f4.desc":
      "Take notes as you learn, linked to your conversations, building your own knowledge base.",
    "landing.features.f4.more":
      "The notes vault is an Obsidian-style linked knowledge base: [[wikilinks]] connect concepts, AI drafts notes from conversations, textbooks or your error notebook, and SM-2 spaced review brings due notes back on schedule — with a force-directed graph for the big picture.",
    "landing.features.f4.p1": "[[Wikilinks]], tags and folders; unresolved links create notes in one click",
    "landing.features.f4.p2": "AI generates summaries, corrections and reviews from your sources",
    "landing.features.f4.p3": "SM-2 spaced repetition plus a live relationship graph",
    "landing.features.f5.title": "Mastery profile",
    "landing.features.f5.desc":
      "BKT mastery tracking and knowledge-graph visualization make strengths and gaps obvious.",
    "landing.features.f5.more":
      "The M2 student model runs BKT (Bayesian Knowledge Tracing) over your answer history to estimate mastery per concept. The dashboard and profile turn mastery, concept states and learning style into readable graphs — strengths and gaps at a glance.",
    "landing.features.f5.p1": "BKT estimates mastery per concept, sharpening with every answer",
    "landing.features.f5.p2": "Knowledge graph colored by mastery makes weak spots obvious",
    "landing.features.f5.p3": "The profile is transparent — see everything the system knows",
    "landing.features.f6.title": "Long-term planning",
    "landing.features.f6.desc":
      "From semester goals down to today's tasks, with SM-2 spaced repetition against forgetting.",
    "landing.features.f6.more":
      "Set one or more semester goals and M9 breaks them into weekly → today's tasks, weaving SM-2 due reviews into each day. Completions flow back into the mastery model and next week's plan adjusts automatically.",
    "landing.features.f6.p1": "Multiple goals cascade into weekly and daily tasks",
    "landing.features.f6.p2": "SM-2 spaced repetition schedules reviews automatically",
    "landing.features.f6.p3": "Completions feed mastery; plans adapt dynamically",
    "landing.features.f7.title": "Voice call tutoring",
    "landing.features.f7.desc": "Ask out loud like a phone call — formulas you can both hear and see.",
    "landing.features.f7.more":
      "Start a voice call and get spoken answers sentence by sentence. Fractions, roots, subscripts, superscripts, sums and integrals in the answer are automatically converted into natural spoken readings instead of unreadable symbol strings, while the blackboard renders each formula as typeset LaTeX in sync with the speech — look up whenever you miss a word.",
    "landing.features.f7.p1": "Real-time voice conversation — ask out loud, answers stream back as speech",
    "landing.features.f7.p2": "Formula read-aloud: fractions, roots, subscripts and integrals become natural spoken Chinese",
    "landing.features.f7.p3": "Synced blackboard: every spoken formula is written live in typeset LaTeX",

    "landing.modules.kicker": "Architecture",
    "landing.modules.title": "M0–M10 · Ten intelligence modules",
    "landing.modules.subtitle": "Every turn runs through a complete multi-agent orchestration pipeline.",
    "landing.modules.m0.name": "Identity",
    "landing.modules.m0.desc": "Who the user is, who owns the data, secure access",
    "landing.modules.m1.name": "Task intelligence",
    "landing.modules.m1.desc": "Understand → plan → execute tools → update state",
    "landing.modules.m2.name": "Student model",
    "landing.modules.m2.desc": "Profile + BKT mastery + concept states",
    "landing.modules.m3.name": "Teaching engine",
    "landing.modules.m3.desc": "Six-mode state machine + cross-turn teaching memory",
    "landing.modules.m4.name": "Assessment",
    "landing.modules.m4.desc": "Three-level grading + constrained quizzing + CAT",
    "landing.modules.m5.name": "Knowledge intelligence",
    "landing.modules.m5.desc": "Textbook knowledge graph + concept retrieval",
    "landing.modules.m6.name": "Memory intelligence",
    "landing.modules.m6.desc": "Bounded profiles + strategy aggregation — knows you better over time",
    "landing.modules.m7.name": "Self-evaluation",
    "landing.modules.m7.desc": "Teaching self-diagnostics so the tutor keeps improving",
    "landing.modules.m8.name": "UX intelligence",
    "landing.modules.m8.desc": "Expression adapted to each student's preferences",
    "landing.modules.m9.name": "Learning orchestration",
    "landing.modules.m9.desc": "Goals → weekly tasks → today's tasks",
    "landing.modules.m10.name": "Skill runtime",
    "landing.modules.m10.desc": "Skill contracts and the learning-evidence gate",

    "landing.how.kicker": "Getting started",
    "landing.how.title": "Three steps to your first lesson",
    "landing.how.s1.title": "Create an account",
    "landing.how.s1.desc": "Sign up for a private learning space — all data fully isolated.",
    "landing.how.s2.title": "Ask or pick a textbook",
    "landing.how.s2.desc":
      "Use the public textbooks or upload your own materials, then ask anything.",
    "landing.how.s3.title": "Keep improving",
    "landing.how.s3.desc":
      "The system tracks your mastery and schedules reviews and quizzes automatically.",

    "landing.cta.title": "Ready to start?",
    "landing.cta.subtitle": "Create a free account and let your tutor agent tailor the first lesson.",
    "landing.cta.button": "Get started free",
    "landing.cta.workspace": "Open workspace",

    "landing.footer.docs": "Docs",
    "landing.footer.login": "Sign in",
    "landing.footer.register": "Sign up",
  },
};
