import type { PageStrings } from "@/lib/i18n-page";

/** 首页产品介绍，与当前学习功能保持一致。 */
export const LANDING_STRINGS = {
  "zh": {
    "landing.nav.features": "功能体验",
    "landing.nav.modules": "设计理念",
    "landing.nav.how": "如何开始",
    "landing.nav.docs": "使用手册",
    "landing.nav.login": "登录",
    "landing.nav.start": "注册",
    "landing.nav.workspace": "进入工作区",
    "landing.hero.kicker": "从教材出发 · 让理解发生",
    "landing.hero.title.a": "Next Tutor Agent",
    "landing.hero.title.b": "你的专属教育智能体",
    "landing.hero.subtitle": "读懂一个概念，问清一个为什么。从教材讲解、备课上课，到练习与复习，让每一次学习都有下一步。",
    "landing.hero.primary": "开始学习",
    "landing.hero.secondary": "已有账号，登录",
    "landing.hero.workspace": "继续学习",
    "landing.hero.scroll": "探索学习的更多可能",
    "landing.hero.vertical": "因材施教 · 有教无类",
    "landing.features.example": "辅导对话示例",
    "landing.features.question": "导数为什么可以表示瞬时变化率？",
    "landing.features.answer": "先想象一辆正在加速的车：平均速度描述一段路程，那某一瞬间的速度呢？",
    "landing.features.source": "从直观例子开始，再回到概念",
    "landing.features.lessonExample": "课件示意",
    "landing.features.lessonTitle": "从变化，理解导数",
    "landing.features.lessonTopic": "概念 · 图像 · 应用",
    "landing.features.kicker": "01 / 学习的不同打开方式",
    "landing.features.title": "一个空间，承接学习的每一步。",
    "landing.features.subtitle": "从“这里没看懂”，到“让我自己试试”。选择此刻需要的方式，让学习顺着你的问题展开。",
    "landing.features.f1.title": "把问题，聊明白",
    "landing.features.f1.desc": "围绕教材追问概念、拆解推导。需要时给你一个例子、一点提示，或留出自己思考的空间。",
    "landing.features.f1.detail": "对话辅导 / 图片提问 / 可选语音",
    "landing.features.f2.title": "把章节，变成课堂",
    "landing.features.f2.desc": "从教材章节或主题准备课件与讲稿。预览、调整，再开始 AI 讲授；下次回来，可以接着学。",
    "landing.features.f2.detail": "一键备课 / 课件与讲稿 / 继续上课",
    "landing.features.f3.title": "让理解，经得起练习",
    "landing.features.f3.desc": "做一道针对性练习，或尝试参考题的变式。在测评中结合你的作答调整难度，回看反馈与错题。",
    "landing.features.f3.detail": "变式出题 / 自适应测评 / 错题回顾",
    "landing.features.f4.title": "让知识，有处安放",
    "landing.features.f4.desc": "把对话里的好解释、教材中的重点和自己的解题思路留下来。用双向链接，把零散笔记连起来。",
    "landing.features.f4.detail": "Markdown / 双向链接 / 到期复习",
    "landing.features.f5.title": "看见知识，也看见进展",
    "landing.features.f5.desc": "沿着知识图谱认识概念之间的联系。结合真实作答查看学习记录，找到还需要讲解或验证的地方。",
    "landing.features.f5.detail": "教材资料 / 知识图谱 / 学习总览",
    "landing.features.f6.title": "给下一步，一个方向",
    "landing.features.f6.desc": "把长期目标拆成周计划与今日任务，让新内容和到期复习都各有安排，逐步建立自己的学习节奏。",
    "landing.features.f6.detail": "学习目标 / 每日任务 / 复习安排",
    "landing.features.extra": "还可以用场景插图工具把抽象概念画出来、在图示库中管理生成的图，站内学习助手帮你寻找入口、查看学习近况。课堂、语音与助手以实例开放的能力为准。",
    "landing.features.guide": "阅读使用手册",
    "landing.modules.kicker": "02 / 我们如何理解学习",
    "landing.modules.title": "每一步，都有来处。",
    "landing.modules.subtitle": "教材提供依据，作答留下线索。把讲解、练习与下一次学习连接起来，也让你看清建议从何而来。",
    "landing.modules.1.title": "从你正在读的教材出发",
    "landing.modules.1.desc": "选择公共教材或上传个人材料，围绕相关原文讲解和出题。教材依据不足时，明确说明边界。",
    "landing.modules.2.title": "关注你实际表现出的理解",
    "landing.modules.2.desc": "参考你的回答、解题过程和获得的帮助，形成有条件的评价。一句“懂了”，不会直接变成“已掌握”。",
    "landing.modules.3.title": "把下一次学习接起来",
    "landing.modules.3.desc": "课程可以继续，笔记可以回顾，任务可以逐步完成。把每一次的小进展，留给下一次的自己。",
    "landing.modules.artLabel": "一段学习，如何继续",
    "landing.modules.source": "你的教材与问题",
    "landing.modules.sourceDesc": "从具体章节、概念或困惑开始",
    "landing.modules.center": "讲解 · 尝试 · 反馈",
    "landing.modules.centerDesc": "让自己的理解，有机会被看见",
    "landing.modules.chip1": "教材依据",
    "landing.modules.chip2": "真实作答",
    "landing.modules.chip3": "帮助条件",
    "landing.modules.next": "下一步，适合你的学习",
    "landing.modules.nextDesc": "继续讲解、针对练习，或稍后复习",
    "landing.modules.caption": "学习过程示意 · 评价以实际学习记录为依据",
    "landing.how.kicker": "03 / 从这里开始",
    "landing.how.title": "不用准备好一切，先开始。",
    "landing.how.subtitle": "一本教材、一个问题就够了。其余的，在学习中慢慢展开。",
    "landing.how.s1.title": "建立自己的学习空间",
    "landing.how.s1.desc": "注册登录，按学科或目标创建工作学习区，让教材、会话与课程各有归属。",
    "landing.how.s2.title": "选一本教材，问一个问题",
    "landing.how.s2.desc": "关联公共教材或个人材料，开始聊天；想系统地学，也可以从一个章节准备课程。",
    "landing.how.s3.title": "试着作答，留下积累",
    "landing.how.s3.desc": "用一道练习检查理解，把关键内容整理成笔记，再为下一次学习留一个小目标。",
    "landing.cta.title": "下一次理解，从你的问题开始。",
    "landing.cta.subtitle": "带上一本教材，或一个还没想明白的问题。今天，就从这里开始。",
    "landing.cta.button": "开始我的学习",
    "landing.cta.workspace": "回到学习空间",
    "landing.footer.docs": "使用手册",
    "landing.footer.login": "登录",
    "landing.footer.register": "注册"
  },
  "en": {
    "landing.nav.features": "Features",
    "landing.nav.modules": "Our approach",
    "landing.nav.how": "Get started",
    "landing.nav.docs": "User guide",
    "landing.nav.login": "Sign in",
    "landing.nav.start": "Sign up",
    "landing.nav.workspace": "Open workspace",
    "landing.hero.kicker": "TEXTBOOKS AT HEART · CURIOSITY IN MOTION",
    "landing.hero.title.a": "Next Tutor Agent",
    "landing.hero.title.b": "Your personal learning companion",
    "landing.hero.subtitle": "Understand a concept. Follow a question. Bring textbooks, lessons, practice, and review together — with a next step for every learning session.",
    "landing.hero.primary": "Start learning",
    "landing.hero.secondary": "Sign in",
    "landing.hero.workspace": "Continue learning",
    "landing.hero.scroll": "Explore what you can do",
    "landing.hero.vertical": "EVERY STUDENT · A TUTOR",
    "landing.features.example": "TUTORING EXAMPLE",
    "landing.features.question": "Why does a derivative describe instantaneous change?",
    "landing.features.answer": "Think of a car accelerating. Average speed describes a journey — but what about its speed at a single instant?",
    "landing.features.source": "Begin with an example, then return to the concept",
    "landing.features.lessonExample": "LESSON PREVIEW",
    "landing.features.lessonTitle": "Understanding change",
    "landing.features.lessonTopic": "Concept · Graph · Application",
    "landing.features.kicker": "01 / ROOM TO EXPLORE",
    "landing.features.title": "One space. Every step of learning.",
    "landing.features.subtitle": "From “I don’t follow” to “let me try.” Find the right way forward, wherever your curiosity takes you.",
    "landing.features.f1.title": "Talk it through",
    "landing.features.f1.desc": "Explore concepts and work through derivations with your textbook. Ask for an example, a hint, or room to work it out yourself.",
    "landing.features.f1.detail": "TUTORING / IMAGE QUESTIONS / OPTIONAL VOICE",
    "landing.features.f2.title": "A chapter becomes a lesson",
    "landing.features.f2.desc": "Turn a chapter or topic into slides and a teaching script. Preview, refine, and start an AI-led lesson. Come back to continue.",
    "landing.features.f2.detail": "LESSON PREPARATION / SLIDES & SCRIPTS / RESUME",
    "landing.features.f3.title": "Put understanding to work",
    "landing.features.f3.desc": "Try a focused exercise or a variation on a reference problem. Assessments adapt difficulty to your answers, with feedback and mistakes to revisit.",
    "landing.features.f3.detail": "QUESTION VARIATIONS / ASSESSMENT / REVIEW",
    "landing.features.f4.title": "Keep what clicks",
    "landing.features.f4.desc": "Save useful explanations, textbook highlights, and your own reasoning. Connect individual notes with backlinks.",
    "landing.features.f4.detail": "MARKDOWN / BACKLINKS / SCHEDULED REVIEW",
    "landing.features.f5.title": "See the connections",
    "landing.features.f5.desc": "Explore relationships between concepts. Use your actual answers and learning records to find what needs more explanation or practice.",
    "landing.features.f5.detail": "TEXTBOOKS / KNOWLEDGE MAP / DASHBOARD",
    "landing.features.f6.title": "Make room for what’s next",
    "landing.features.f6.desc": "Break a longer-term goal into weekly plans and daily tasks. Make room for new material and due reviews, at your own pace.",
    "landing.features.f6.detail": "GOALS / DAILY TASKS / REVIEW SCHEDULE",
    "landing.features.extra": "Illustration tools turn abstract ideas into pictures, the diagram library keeps them organized, and the site assistant helps you find features and review recent learning. Classroom, voice, and assistant availability depends on the instance.",
    "landing.features.guide": "Explore the user guide",
    "landing.modules.kicker": "02 / OUR APPROACH",
    "landing.modules.title": "Every next step has a starting point.",
    "landing.modules.subtitle": "Textbooks provide grounding. Your answers provide evidence. Connect explanations and practice to what comes next — and see why.",
    "landing.modules.1.title": "Begin with your textbook",
    "landing.modules.1.desc": "Choose public textbooks or upload your own materials. Relevant passages ground explanations and questions; missing evidence stays an explicit limitation.",
    "landing.modules.2.title": "Look at what your work shows",
    "landing.modules.2.desc": "Answers, reasoning, and assistance received inform a scoped evaluation. Saying “I get it” alone does not establish mastery.",
    "landing.modules.3.title": "Keep the thread of learning",
    "landing.modules.3.desc": "Resume a lesson, revisit a note, or work through your next task. Small steps today become a starting point tomorrow.",
    "landing.modules.artLabel": "HOW LEARNING CONTINUES",
    "landing.modules.source": "Your textbook & question",
    "landing.modules.sourceDesc": "A chapter, a concept, a point of confusion",
    "landing.modules.center": "Explore · Try · Reflect",
    "landing.modules.centerDesc": "Give your understanding a chance to show",
    "landing.modules.chip1": "Grounding",
    "landing.modules.chip2": "Your answers",
    "landing.modules.chip3": "Support received",
    "landing.modules.next": "Your next learning step",
    "landing.modules.nextDesc": "Explain further, practice, or review later",
    "landing.modules.caption": "LEARNING FLOW · EVALUATIONS RELY ON ACTUAL RECORDS",
    "landing.how.kicker": "03 / YOUR STARTING POINT",
    "landing.how.title": "Start where you are.",
    "landing.how.subtitle": "A textbook and a question are enough. Let the rest unfold as you learn.",
    "landing.how.s1.title": "Make a space for learning",
    "landing.how.s1.desc": "Sign in and create a workspace for a subject or goal. Keep materials, conversations, and courses together.",
    "landing.how.s2.title": "Choose a book. Ask a question.",
    "landing.how.s2.desc": "Associate public or personal materials and start a conversation. For a structured session, prepare a lesson from a chapter.",
    "landing.how.s3.title": "Try it. Keep what you learn.",
    "landing.how.s3.desc": "Check your understanding with an exercise, save the key ideas in a note, and set a small goal for next time.",
    "landing.cta.title": "Your next discovery starts with a question.",
    "landing.cta.subtitle": "Bring a textbook, or a question you haven’t quite figured out. Start there.",
    "landing.cta.button": "Start learning",
    "landing.cta.workspace": "Return to your workspace",
    "landing.footer.docs": "User guide",
    "landing.footer.login": "Sign in",
    "landing.footer.register": "Sign up"
  }
} satisfies PageStrings;
