import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    // catalog / preparation
    labTitle: "模拟实验室 · 化学",
    labIntro: "用器材、试剂和可回溯规则理解化学现象：每个现象都能追问证据，每条分支都能对比。",
    catalogEmpty: "还没有可用的实验。",
    backToCatalog: "返回实验目录",
    backToTools: "返回工具助手",
    fidelity: "教学半定量模型",
    "audience.middle_school": "初中",
    "audience.high_school_intro": "高中入门",
    "mode.guided": "引导实验",
    "mode.explore": "探索实验",
    "mode.self_check": "自检实验",
    "mode.guidedDesc": "给出当前目标与分级提示；允许多条合理路径，不机械对照唯一步骤。",
    "mode.exploreDesc": "在已建模的试剂与器材范围内自由组合；界面会标明模型覆盖范围，不模拟未知体系。",
    "mode.self_checkDesc": "先预测、再操作、最后对照解释；只输出本次表现，不是正式考试。",
    modeTitle: "选择使用模式",
    goals: "实验目标",
    procedure: "步骤概览",
    reagents: "试剂",
    safety: "安全说明",
    modelScope: "模型范围",
    predictTitle: "先写下你的预测",
    predictDesc: "开始实验前选出你预计会出现的现象；实验后可以对照观察记录修正解释。",
    predictFirst: "请先完成所有预测再开始",
    start: "开始实验",
    starting: "正在创建会话…",

    // workspace chrome
    switchExperiment: "更换实验",
    sessions: "我的实验会话",
    noSessions: "还没有实验会话",
    unnamed: "未命名实验",
    phaseCompleted: "已完成",
    loadFailed: "加载失败，请重试。",
    retry: "重试",
    disabled: "模拟实验台暂不可用。",
    sessionMissing: "会话不存在或没有权限访问。",
    experimentMissing: "没有找到这个实验。",
    delete: "删除",
    deleteTitle: "删除实验会话",
    deleteDesc: "将删除这个会话及其检查点与分支，不能恢复。",
    cancel: "取消",
    save: "保存",
    close: "关闭",
    resetTitle: "从起点重新开始",
    resetDesc: "将创建一个回到初始状态的新分支，当前会话保留在会话列表中。",
    resetConfirm: "创建重置分支",
    resultTitle: "实验结果卡",
    resultObservations: "记录到的现象",
    resultPredictions: "你的预测",
    resultGoals: "目标达成",
    resultFinished: "完成时间",
    resultNote: "结果卡只谈本次实验，不推断知识掌握。",
    atBanner: "正在只读查看版本 %n：画面为该历史时刻的重放，不能操作。",
    atBranch: "从版本 %n 创建分支",
    backToLatest: "回到最新状态",
    historyLoading: "正在载入历史版本…",
    historyTip: "只读 · 最新版本 %n",
    historyPrev: "上一版本",
    historyNext: "下一版本",
    dismiss: "知道了",

    // trays / palette
    trayTitle: "器材",
    trayEmpty: "本实验没有额外器材。",
    trayClean: "洁净",
    trayDirty: "待清洗",
    trayLoaded: "装有 %n mL",
    trayConnected: "已连接",
    trayWash: "清洗",
    trayMeasure: "测量",
    paletteTitle: "试剂",
    paletteSearch: "搜索试剂",
    paletteEmpty: "本实验没有可添加的试剂。",
    paletteNoMatch: "没有匹配的试剂。",
    remaining: "余量 %n mL",
    measureOut: "量取",
    pour: "倾倒",

    // toolbar / operations
    selectHint: "点击或拖拽实验台上的器材与试剂开始操作",
    heldHint: "该器材处于手持状态 — 可直接拖拽到其它位置，或取消持有。",
    releaseHold: "取消持有",
    deselect: "取消选择",
    operationSuffix: "",
    stir: "搅拌",
    measure: "测量",
    filter: "过滤",
    dispose: "丢弃",
    heat: "加热",
    aspirate: "吸取",
    dispense: "排出",
    wash: "清洗",
    connect: "连接导管",
    wait: "等待",
    confirm: "执行",
    back: "返回",
    choose: "请选择",
    instrument: "仪器",
    sourceVessel: "来源容器",
    targetVessel: "目标容器",
    vessel: "容器",
    device: "加热设备",
    tubing: "导管",
    filterInto: "过滤到",
    amount: "用量",
    amountMl: "用量（mL）",
    rate: "倾倒速度",
    rateSlow: "缓慢",
    rateNormal: "正常",
    power: "功率",
    speed: "搅拌速度",
    duration: "时长（模拟）",
    quantity: "测量量",
    "quantity.temperature": "温度",
    "quantity.ph": "pH",
    "quantity.volume": "体积",
    "quantity.mass": "质量",
    disposeNote: "废液进入废物容器账本，物质不会无声消失。",

    // measurement popover
    noReading: "还没有读数",
    loaded: "装有 %n mL",
    dirty: "待清洗",
    connected: "已连接",
    ready: "就绪",

    // sync / status
    "sync.synced": "已保存",
    "sync.predicting": "本地预览中",
    "sync.pending": "待同步 %n 条",
    "sync.conflict": "同步冲突",
    "sync.offline": "网络中断 · 本地预览不会保存",
    "sync.safety": "安全锁定",
    syncedFromServer: "已同步服务器结果",
    retrySync: "重新同步",
    conflictTitle: "实验状态与服务器不一致",
    conflictDesc: "服务器已保存了不同的结果。可以查看并采纳服务器状态，未确认的操作已保留在下方供诊断。",
    conflictCommands: "未确认的操作",
    offlineTitle: "网络连接中断",
    offlineDesc: "当前为本地预览，恢复连接后可以继续同步。",
    safetyTitle: "安全锁定",
    safetyDesc: "虚拟安全条件已触发，操作已锁定。可以查看原因、从检查点创建分支或从起点重来。",

    // guidance
    guidance: "当前指导",
    noGuidance: "开始操作后，这里会给出与你步骤相关的提示。",
    "level.on_track": "进展顺利",
    "level.try_again": "再试一次",
    "level.hint": "提示",
    "level.explain": "解释",
    "level.safety": "安全",
    "level.complete": "已完成",
    rejected: "上一步未执行",
    evidenceSeq: "根据你的第 %n 条事件",
    concepts: "相关概念",

    // observations
    observationsTab: "观察",
    guidanceTab: "指导",
    equipmentTab: "器材",
    noObservations: "还没有记录到现象。",
    rejectedEntry: "一条操作未被执行（可在指导栏查看原因）",
    myNote: "我的记录",
    notePlaceholder: "用自己的话记下观察…",
    addNote: "记录",
    openEvidence: "查看证据链",
    simTime: "模拟时间",
    "obs.bubbles_visible": "出现气泡",
    "obs.color_changed": "颜色发生变化",
    "obs.color_faded": "颜色变浅",
    "obs.color_visible": "颜色可见",
    "obs.filtered": "完成过滤",
    "obs.gas_collected": "收集到气体",
    "obs.indicator_present": "指示剂已加入",
    "obs.measured_ph": "测得 pH",
    "obs.measured_temperature": "测得温度",
    "obs.measured_volume": "测得体积",
    "obs.precipitate_dissolved": "沉淀溶解",
    "obs.precipitate_visible": "出现沉淀",
    "obs.sediment_layer": "沉淀沉降分层",
    "obs.steam_visible": "出现水汽",
    "obs.tubing_connected": "导管已连接",

    // evidence drawer
    evidenceTitle: "证据链",
    evidenceEmpty: "选择一条观察记录，查看它背后的操作、规则与概念。",
    evidenceObservation: "观察到的现象",
    evidenceOperations: "相关操作与状态变化",
    evidenceNoEvents: "没有更多相关事件。",
    evidenceRule: "依据的规则",
    evidenceModelNote: "解释来自版本固定的实验包与事件日志，不生成新内容。",

    // timeline
    checkpoint: "检查点",
    checkpointLabel: "检查点名称",
    reset: "从起点重来",
    compare: "分支对比",
    finish: "完成实验",
    revisionLabel: "版本 %n",
    serverRevision: "服务器 %n",
    timelineTrack: "操作时间轴",
    checkpointHint: "点击菱形标记，从该检查点创建分支继续探索。",
    forkFromHere: "从此处分支",

    // branch compare
    compareTitle: "分支对比",
    compareEmpty: "选择另一条同实验的分支会话进行对比。",
    comparePick: "选择要对比的分支",
    compareVariables: "两分支中发生变化的操作类别",
    compareMultiVariable: "两分支同时改变了多个变量，无法仅由此对比归因于单一变量。",
    compareVersionDiff: "两分支的实验包版本不同，现象差异可能来自模型更新。",
    "variable.amount": "加入量",
    "variable.heat": "加热",
    "variable.stir": "搅拌",
    "variable.connection": "连接",
    "variable.none": "（没有可比较的变量变化）",
    empty: "空",
    hasPrecipitate: "有沉淀",
    hasBubbles: "有气泡",
    thisSession: "当前会话",

    // scene / stage
    sceneAria: "虚拟化学实验台",
    sceneMove: "移动",
    cameraOverview: "总览",
    cameraFocus: "聚焦",
    chooseTarget: "选择一个目标位置",
    "drop.move": "松开移动到该位置",
    "drop.operation": "松开选择操作",
    "drop.none": "未移动",
    "drop.occupied": "该位置已被占用",
    "drop.unsupported": "这两个器材没有可组合的操作",
    "drop.locked": "当前状态不可移动（先解除持有或等待同步）",
    "drop.out_of_bounds": "超出实验台范围",
    "sum.steam": "有水汽",
    "sum.hot": "温度高",
    "sum.warm": "温热",
    "chip.safety": "注意安全",
    "chip.precipitate": "产生沉淀",
    "chip.gas": "产生气体",
    "chip.crystal": "析出晶体",
    unknownKind: "未知器材 %s",
    spotOccupied: "位置 %s（已被 %o 占用）",
    moveToSpot: "移动到位置 %s",

    // event kinds
    "evt.checkpoint_created": "创建检查点",
    "evt.command_rejected": "操作未执行",
    "evt.contamination_changed": "污染变化",
    "evt.crystal_formed": "晶体析出",
    "evt.gas_released": "气体逸出",
    "evt.heating_started": "开始加热",
    "evt.instrument_connected": "连接仪器",
    "evt.instrument_washed": "清洗仪器",
    "evt.material_poured": "倾倒液体",
    "evt.measurement_taken": "完成测量",
    "evt.mixing_changed": "混合状态变化",
    "evt.object_picked_up": "拿起器材",
    "evt.object_placed": "放下器材",
    "evt.observation_emitted": "记录现象",
    "evt.phase_changed": "阶段变化",
    "evt.precipitate_formed": "生成沉淀",
    "evt.procedure_step_completed": "完成一个步骤",
    "evt.reagent_aspirated": "吸取试剂",
    "evt.reagent_dispensed": "排出试剂",
    "evt.rule_limit_reached": "达到反应上限",
    "evt.safety_locked": "安全锁定",
    "evt.safety_warning": "安全提示",
    "evt.species_consumed": "物质被消耗",
    "evt.species_produced": "生成新物质",
    "evt.temperature_changed": "温度变化",
    "evt.volume_changed": "体积变化",
  },
  en: {
    labTitle: "Virtual lab · Chemistry",
    labIntro: "Understand chemistry through equipment, reagents and traceable rules: every phenomenon has an evidence chain, every branch can be compared.",
    catalogEmpty: "No experiments available yet.",
    backToCatalog: "Back to experiment catalog",
    backToTools: "Back to tool assistants",
    fidelity: "Teaching semi-quantitative model",
    "audience.middle_school": "Middle school",
    "audience.high_school_intro": "High-school intro",
    "mode.guided": "Guided",
    "mode.explore": "Explore",
    "mode.self_check": "Self-check",
    "mode.guidedDesc": "Shows the current goal with tiered hints; multiple reasonable paths are accepted.",
    "mode.exploreDesc": "Combine any modeled reagents and equipment freely; the UI states the modeled scope and never simulates unknown systems.",
    "mode.self_checkDesc": "Predict first, operate, then compare and explain; only this run's performance is shown.",
    modeTitle: "Choose a mode",
    goals: "Goals",
    procedure: "Procedure overview",
    reagents: "Reagents",
    safety: "Safety notes",
    modelScope: "Model scope",
    predictTitle: "Write down your predictions",
    predictDesc: "Choose what you expect to see before starting; afterwards you can revise your explanation against the observation log.",
    predictFirst: "Answer all predictions before starting",
    start: "Start experiment",
    starting: "Creating session…",

    switchExperiment: "Change experiment",
    sessions: "My lab sessions",
    noSessions: "No lab sessions yet",
    unnamed: "Untitled experiment",
    phaseCompleted: "Completed",
    loadFailed: "Could not load. Please retry.",
    retry: "Retry",
    disabled: "The virtual lab is currently unavailable.",
    sessionMissing: "This session does not exist or is not visible to you.",
    experimentMissing: "Experiment not found.",
    delete: "Delete",
    deleteTitle: "Delete lab session",
    deleteDesc: "This deletes the session with its checkpoints and branches. It cannot be undone.",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    resetTitle: "Restart from the beginning",
    resetDesc: "This creates a new branch back at the initial state; the current session stays in your session list.",
    resetConfirm: "Create reset branch",
    resultTitle: "Experiment result card",
    resultObservations: "Recorded phenomena",
    resultPredictions: "Your predictions",
    resultGoals: "Goals met",
    resultFinished: "Finished at",
    resultNote: "The result card covers this run only; it does not infer mastery.",
    atBanner: "Viewing revision %n read-only: the scene is replayed to that moment and cannot be operated.",
    atBranch: "Branch from revision %n",
    backToLatest: "Back to latest",
    historyLoading: "Loading historical revision…",
    historyTip: "Read-only · latest revision %n",
    historyPrev: "Previous revision",
    historyNext: "Next revision",
    dismiss: "Got it",

    trayTitle: "Equipment",
    trayEmpty: "No extra equipment in this experiment.",
    trayClean: "Clean",
    trayDirty: "Needs washing",
    trayLoaded: "Loaded %n mL",
    trayConnected: "Connected",
    trayWash: "Wash",
    trayMeasure: "Measure",
    paletteTitle: "Reagents",
    paletteSearch: "Search reagents",
    paletteEmpty: "No reagents to add in this experiment.",
    paletteNoMatch: "No matching reagents.",
    remaining: "%n mL left",
    measureOut: "Measure out",
    pour: "Pour",

    selectHint: "Click or drag equipment and reagents on the bench to operate",
    heldHint: "Held — drag it anywhere on the bench, or release the hold.",
    releaseHold: "Release hold",
    deselect: "Deselect",
    operationSuffix: "",
    stir: "Stir",
    measure: "Measure",
    filter: "Filter",
    dispose: "Dispose",
    heat: "Heat",
    aspirate: "Aspirate",
    dispense: "Dispense",
    wash: "Wash",
    connect: "Connect tubing",
    wait: "Wait",
    confirm: "Run",
    back: "Back",
    choose: "Choose…",
    instrument: "Instrument",
    sourceVessel: "Source vessel",
    targetVessel: "Target vessel",
    vessel: "Vessel",
    device: "Heating device",
    tubing: "Tubing",
    filterInto: "Filter into",
    amount: "Amount",
    amountMl: "Amount (mL)",
    rate: "Pour rate",
    rateSlow: "Slow",
    rateNormal: "Normal",
    power: "Power",
    speed: "Stir speed",
    duration: "Duration (sim)",
    quantity: "Quantity",
    "quantity.temperature": "Temperature",
    "quantity.ph": "pH",
    "quantity.volume": "Volume",
    "quantity.mass": "Mass",
    disposeNote: "Waste goes into the waste ledger; matter never silently disappears.",

    noReading: "No reading yet",
    loaded: "Loaded %n mL",
    dirty: "Needs washing",
    connected: "Connected",
    ready: "Ready",

    "sync.synced": "Saved",
    "sync.predicting": "Local preview",
    "sync.pending": "%n pending",
    "sync.conflict": "Sync conflict",
    "sync.offline": "Offline · preview is not saved",
    "sync.safety": "Safety locked",
    syncedFromServer: "Synced with the server",
    retrySync: "Sync now",
    conflictTitle: "Lab state differs from the server",
    conflictDesc: "The server has stored a different result. Review and adopt the server state; unconfirmed operations are kept below for diagnosis.",
    conflictCommands: "Unconfirmed operations",
    offlineTitle: "Connection lost",
    offlineDesc: "You are in local preview. Sync resumes once the connection is back.",
    safetyTitle: "Safety locked",
    safetyDesc: "A virtual safety condition fired and operations are locked. Review the cause, branch from a checkpoint, or restart.",

    guidance: "Current guidance",
    noGuidance: "Hints tied to your steps will appear once you start operating.",
    "level.on_track": "On track",
    "level.try_again": "Try again",
    "level.hint": "Hint",
    "level.explain": "Explanation",
    "level.safety": "Safety",
    "level.complete": "Complete",
    rejected: "Last action was not run",
    evidenceSeq: "Based on your event #%n",
    concepts: "Related concepts",

    observationsTab: "Observations",
    guidanceTab: "Guidance",
    equipmentTab: "Equipment",
    noObservations: "No phenomena recorded yet.",
    rejectedEntry: "An operation was not run (see guidance for why)",
    myNote: "My note",
    notePlaceholder: "Write what you observed…",
    addNote: "Note",
    openEvidence: "Open evidence chain",
    simTime: "Sim time",
    "obs.bubbles_visible": "Bubbles appeared",
    "obs.color_changed": "Color changed",
    "obs.color_faded": "Color faded",
    "obs.color_visible": "Color visible",
    "obs.filtered": "Filtration done",
    "obs.gas_collected": "Gas collected",
    "obs.indicator_present": "Indicator added",
    "obs.measured_ph": "pH measured",
    "obs.measured_temperature": "Temperature measured",
    "obs.measured_volume": "Volume measured",
    "obs.precipitate_dissolved": "Precipitate dissolved",
    "obs.precipitate_visible": "Precipitate appeared",
    "obs.sediment_layer": "Sediment settled",
    "obs.steam_visible": "Steam visible",
    "obs.tubing_connected": "Tubing connected",

    evidenceTitle: "Evidence chain",
    evidenceEmpty: "Pick an observation to see the operations, rule and concepts behind it.",
    evidenceObservation: "Observed phenomenon",
    evidenceOperations: "Related operations and state changes",
    evidenceNoEvents: "No more related events.",
    evidenceRule: "Underlying rule",
    evidenceModelNote: "Explanations come from the versioned experiment pack and the event log; nothing is generated.",

    checkpoint: "Checkpoint",
    checkpointLabel: "Checkpoint name",
    reset: "Restart",
    compare: "Compare branches",
    finish: "Finish experiment",
    revisionLabel: "Revision %n",
    serverRevision: "server %n",
    timelineTrack: "Operation timeline",
    checkpointHint: "Click a diamond marker to branch from that checkpoint.",
    forkFromHere: "Branch from here",

    compareTitle: "Branch comparison",
    compareEmpty: "Choose another branch of the same experiment to compare.",
    comparePick: "Pick a branch to compare",
    compareVariables: "Operation categories that changed across the two branches",
    compareMultiVariable: "Several variables changed at once; the difference cannot be attributed to a single variable from this comparison alone.",
    compareVersionDiff: "The two branches use different pack versions; differences may come from a model update.",
    "variable.amount": "Amount added",
    "variable.heat": "Heating",
    "variable.stir": "Stirring",
    "variable.connection": "Connection",
    "variable.none": "(no comparable variable change)",
    empty: "Empty",
    hasPrecipitate: "Precipitate",
    hasBubbles: "Bubbles",
    thisSession: "Current session",

    // scene / stage
    sceneAria: "Virtual chemistry bench",
    sceneMove: "Move",
    cameraOverview: "Overview",
    cameraFocus: "Focus",
    chooseTarget: "Choose a target spot",
    "drop.move": "Release to move here",
    "drop.operation": "Release to choose an operation",
    "drop.none": "No move",
    "drop.occupied": "That spot is occupied",
    "drop.unsupported": "No operation between these",
    "drop.locked": "Movement locked (release the held object or wait for sync)",
    "drop.out_of_bounds": "Outside the bench",
    "sum.steam": "steaming",
    "sum.hot": "hot",
    "sum.warm": "warm",
    "chip.safety": "check safety",
    "chip.precipitate": "precipitate formed",
    "chip.gas": "gas released",
    "chip.crystal": "crystals formed",
    unknownKind: "Unknown equipment %s",
    spotOccupied: "Spot %s (occupied by %o)",
    moveToSpot: "Move to spot %s",

    "evt.checkpoint_created": "Checkpoint created",
    "evt.command_rejected": "Operation not run",
    "evt.contamination_changed": "Contamination changed",
    "evt.crystal_formed": "Crystals formed",
    "evt.gas_released": "Gas released",
    "evt.heating_started": "Heating started",
    "evt.instrument_connected": "Instrument connected",
    "evt.instrument_washed": "Instrument washed",
    "evt.material_poured": "Liquid poured",
    "evt.measurement_taken": "Measurement taken",
    "evt.mixing_changed": "Mixing changed",
    "evt.object_picked_up": "Picked up",
    "evt.object_placed": "Placed",
    "evt.observation_emitted": "Phenomenon recorded",
    "evt.phase_changed": "Phase changed",
    "evt.precipitate_formed": "Precipitate formed",
    "evt.procedure_step_completed": "Step completed",
    "evt.reagent_aspirated": "Reagent aspirated",
    "evt.reagent_dispensed": "Reagent dispensed",
    "evt.rule_limit_reached": "Rule limit reached",
    "evt.safety_locked": "Safety locked",
    "evt.safety_warning": "Safety warning",
    "evt.species_consumed": "Species consumed",
    "evt.species_produced": "Species produced",
    "evt.temperature_changed": "Temperature changed",
    "evt.volume_changed": "Volume changed",
  },
};
