import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "greeting.fallback": "欢迎回来，继续今天的学习吧",
    "stat.workspaces": "学习区",
    "stat.observed": "已有证据概念",
    "stat.attention": "待解决点",
    "stat.streak": "连续学习天数",
    "stat.active.foot": "累计活跃 {n} 天",
    "activity.title": "近 14 天学习活动",
    "activity.desc": "每日作答 / 讲解 / 复习与任务",
    "activity.total": "14 天总计",
    "activity.unit": "次",
    "activity.answers": "作答",
    "activity.teachings": "讲解",
    "activity.reviews": "复习·任务",
    "activity.legacy": "旧版留存数据",
    "recent.title": "最近学习",
    "recent.desc": "最近教学记录，点击查看知识图谱",
    "attention.title": "学习区近况",
    "attention.desc": "各学习区的评价覆盖近况，点击查看学习档案",
    "attention.more": "展开全部学习区",
    "attention.less": "收起",
    "answers.title": "最近作答",
    "answers.desc": "最近 10 次习题作答（本次题目结果，不代表整体水平）",
    "answers.evaluating": "评价中",
    "answers.empty": "还没有作答记录",
    "answers.empty.desc": "在对话中做题或参加测评后，这里会显示最近作答",
    "answers.verdict.correct": "对",
    "answers.verdict.partial": "部分对",
    "answers.verdict.wrong": "错",
    "answers.verdict.unknown": "未判分",
    "answers.from.chat": "对话",
    "answers.from.assessment": "测评",
    "empty.disabled": "该智能层已被环境开关关闭，暂无数据",
    "empty.recent": "暂无学习记录",
    "empty.recent.desc": "开始一次对话学习后，这里会显示最近学过的概念",
    "empty.attention": "暂无需要关注的概念",
    "empty.attention.desc": "创建学习区并完成一次讲解或练习后，这里会显示评价近况",
    "empty.activity": "近 14 天暂无学习活动",
    "empty.activity.desc": "作答、讲解、复习任一学习行为都会计入活动",
    "error.load": "数据加载失败，请检查后端服务后重试",
    "orch.title": "今日任务",
    "orch.goal": "目标",
    "orch.days": "天连击",
    "orch.more": "查看编排",
    "orch.empty": "今日任务已全部完成，或今日暂无安排。",
    "orch.summary": "今日总结",
  },
  en: {
    "greeting.fallback": "Welcome back — let's keep learning",
    "stat.workspaces": "Workspaces",
    "stat.observed": "Concepts with evidence",
    "stat.attention": "Points to resolve",
    "stat.streak": "Day streak",
    "stat.active.foot": "{n} active days in total",
    "activity.title": "Learning activity · 14 days",
    "activity.desc": "Daily answers / teachings / reviews & tasks",
    "activity.total": "14-day total",
    "activity.unit": "events",
    "activity.answers": "Answers",
    "activity.teachings": "Teachings",
    "activity.reviews": "Reviews·Tasks",
    "activity.legacy": "legacy data",
    "recent.title": "Recent learning",
    "recent.desc": "Latest teaching records — click to open the knowledge graph",
    "attention.title": "Workspace briefs",
    "attention.desc": "Per-workspace evaluation coverage; click to open the archive",
    "attention.more": "Show all workspaces",
    "attention.less": "Collapse",
    "answers.title": "Recent answers",
    "answers.desc": "Latest 10 quiz answers - this item result, not overall ability",
    "answers.evaluating": "Evaluating",
    "answers.empty": "No answers yet",
    "answers.empty.desc": "Answer questions in chat or take an assessment to see them here",
    "answers.verdict.correct": "Correct",
    "answers.verdict.partial": "Partial",
    "answers.verdict.wrong": "Wrong",
    "answers.verdict.unknown": "Ungraded",
    "answers.from.chat": "Chat",
    "answers.from.assessment": "Assessment",
    "empty.disabled": "This intelligence layer is disabled via environment switch",
    "empty.recent": "No learning records yet",
    "empty.recent.desc": "Concepts you study in chat will appear here",
    "empty.attention": "Nothing needs attention",
    "empty.attention.desc": "Create a workspace and finish an explanation or practice to see evaluation briefs",
    "empty.activity": "No learning activity in the last 14 days",
    "empty.activity.desc": "Any answer, teaching, or review counts as activity",
    "error.load": "Failed to load data. Check the backend and retry.",
    "orch.title": "Today's Tasks",
    "orch.goal": "Goal",
    "orch.days": "-day streak",
    "orch.more": "Orchestration",
    "orch.empty": "All done for today, or nothing scheduled.",
    "orch.summary": "Daily summary",
  },
} satisfies PageStrings;
