import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "greeting.fallback": "欢迎回来，继续今天的学习吧",
    "stat.mastered": "已掌握概念",
    "stat.learning": "学习中",
    "stat.attention": "需关注",
    "stat.streak": "连续学习天数",
    "stat.active.foot": "累计活跃 {n} 天",
    "radar.title": "学科掌握雷达",
    "radar.desc": "各学科平均掌握度（p_known）",
    "activity.title": "近 14 天学习活动",
    "activity.desc": "每日作答 / 讲解 / 复习与任务",
    "activity.total": "14 天总计",
    "activity.unit": "次",
    "activity.answers": "作答",
    "activity.teachings": "讲解",
    "activity.reviews": "复习·任务",
    "activity.legacy": "旧版留存数据",
    "recent.title": "最近学习",
    "recent.desc": "最近教学记录，点击查看知识图谱",
    "attention.title": "需要关注",
    "attention.desc": "存在误解或掌握度偏低的概念",
    "answers.title": "最近作答",
    "answers.desc": "学习账本中最近 10 次作答结果",
    "answers.empty": "还没有作答记录",
    "answers.empty.desc": "在对话中做题或参加测评后，这里会显示最近作答",
    "answers.verdict.correct": "对",
    "answers.verdict.partial": "部分对",
    "answers.verdict.wrong": "错",
    "answers.verdict.unknown": "未判分",
    "answers.from.chat": "对话",
    "answers.from.assessment": "测评",
    "empty.mastery": "暂无掌握度数据",
    "empty.mastery.desc": "开始学习后，这里会展示你的学科掌握情况",
    "empty.disabled": "该智能层已被环境开关关闭，暂无数据",
    "empty.recent": "暂无学习记录",
    "empty.recent.desc": "开始一次对话学习后，这里会显示最近学过的概念",
    "empty.attention": "暂无需要关注的概念",
    "empty.attention.desc": "当前没有误解或掌握度偏低的概念，继续保持",
    "empty.activity": "近 14 天暂无学习活动",
    "empty.activity.desc": "作答、讲解、复习任一学习行为都会计入活动",
    "error.load": "数据加载失败，请检查后端服务后重试",
    "orch.title": "今日任务",
    "orch.goal": "目标",
    "orch.days": "天连击",
    "orch.more": "查看编排",
    "orch.empty": "今日任务已全部完成，或今日暂无安排。",
    "orch.summary": "今日总结",
  },
  en: {
    "greeting.fallback": "Welcome back — let's keep learning",
    "stat.mastered": "Concepts mastered",
    "stat.learning": "Learning",
    "stat.attention": "Needs attention",
    "stat.streak": "Day streak",
    "stat.active.foot": "{n} active days in total",
    "radar.title": "Subject mastery radar",
    "radar.desc": "Average mastery per subject (p_known)",
    "activity.title": "Learning activity · 14 days",
    "activity.desc": "Daily answers / teachings / reviews & tasks",
    "activity.total": "14-day total",
    "activity.unit": "events",
    "activity.answers": "Answers",
    "activity.teachings": "Teachings",
    "activity.reviews": "Reviews·Tasks",
    "activity.legacy": "legacy data",
    "recent.title": "Recent learning",
    "recent.desc": "Latest teaching records — click to open the knowledge graph",
    "attention.title": "Needs attention",
    "attention.desc": "Concepts with misconceptions or low mastery",
    "answers.title": "Recent answers",
    "answers.desc": "Latest 10 graded answers from the learning ledger",
    "answers.empty": "No answers yet",
    "answers.empty.desc": "Answer questions in chat or take an assessment to see them here",
    "answers.verdict.correct": "Correct",
    "answers.verdict.partial": "Partial",
    "answers.verdict.wrong": "Wrong",
    "answers.verdict.unknown": "Ungraded",
    "answers.from.chat": "Chat",
    "answers.from.assessment": "Assessment",
    "empty.mastery": "No mastery data yet",
    "empty.mastery.desc": "Start learning and your subject mastery will show up here",
    "empty.disabled": "This intelligence layer is disabled via environment switch",
    "empty.recent": "No learning records yet",
    "empty.recent.desc": "Concepts you study in chat will appear here",
    "empty.attention": "Nothing needs attention",
    "empty.attention.desc": "No misconceptions or low-mastery concepts right now — keep it up",
    "empty.activity": "No learning activity in the last 14 days",
    "empty.activity.desc": "Any answer, teaching, or review counts as activity",
    "error.load": "Failed to load data. Check the backend and retry.",
    "orch.title": "Today's Tasks",
    "orch.goal": "Goal",
    "orch.days": "-day streak",
    "orch.more": "Orchestration",
    "orch.empty": "All done for today, or nothing scheduled.",
    "orch.summary": "Daily summary",
  },
} satisfies PageStrings;
