import type { MessageDict } from "@next-tutor/i18n";

import { registerDicts } from "@/lib/i18n";

/** Chat 域字典（辅导会话/流式/工具卡/题卡/会话管理）。 */
const zh: MessageDict = {
  "chat.title": "辅导",
  "chat.new": "新对话",
  "chat.sessions": "会话列表",
  "chat.send": "发送",
  "chat.stop": "停止",
  "chat.regenerate": "重新生成",
  "chat.retrying": "连接中断，正在重试",
  "chat.retry.attempt": "第 %n 次",
  "chat.stopped": "已停止生成",
  "chat.error.connect": "连接出了问题",
  "chat.error.interrupted": "生成被中断",
  "chat.load.earlier": "加载更早的消息",
  "chat.load.earlier.loading": "加载中…",
  "chat.notfound.title": "会话不存在或已被删除",
  "chat.notfound.desc": "它可能已被移除，或者链接已失效",
  "chat.notfound.back": "开始新对话",
  "chat.input.placeholder": "向老师提问，或描述你想学的内容…",
  "chat.input.hint": "AI 辅导仅供参考，重要知识请以教材为准",
  "chat.input.upload.title": "上传资料（PDF/DOCX/PPTX/TXT/MD）",
  "chat.input.unsupported": "不支持的文件类型",
  "chat.input.ocr": "拍照识题",
  "chat.ocr.preview": "识别到的题目",
  "chat.grade.label": "学段",
  "chat.empty.greeting.fallback": "今天想学点什么？",
  "chat.guest.title": "游客模式暂不支持完整辅导",
  "chat.guest.desc": "登录后可使用完整的 AI 辅导、会话记录与个性化学习计划",
  "chat.guest.signIn": "去登录",
  "chat.scroll.bottom": "回到底部",

  "msg.copy": "复制",
  "msg.copied": "已复制",

  "step.understanding": "理解问题",
  "step.planning": "规划讲解",
  "step.thinking": "思考中",
  "step.tool_executing": "调用工具",

  "thinking.title": "思考过程",

  "tool.running": "进行中",
  "tool.done": "已完成",
  "tool.failed": "失败",
  "tool.knowledge_search": "检索资料",
  "tool.generate_quiz": "出题练习",
  "tool.fit_quiz": "匹配练习",
  "tool.recall_history": "回顾历史",
  "tool.knowledge.sources": "命中来源",
  "tool.knowledge.filtered": "已过滤",
  "tool.knowledge.items": "条",
  "tool.knowledge.resource": "资料",
  "tool.knowledge.textbookPage": "教材第 %n 页",
  "tool.knowledge.pdfPage": "PDF 第 %n 页",
  "tool.knowledge.unpaged": "未标页",
  "tool.knowledge.figure": "图",
  "tool.knowledge.table": "表",
  "tool.knowledge.conf.high": "高置信",
  "tool.knowledge.conf.medium": "中置信",

  "quiz.questions.unit": "题",
  "quiz.type.multiple_choice": "选择题",
  "quiz.type.fill_blank": "填空题",
  "quiz.type.short_answer": "简答题",
  "quiz.difficulty": "难度",
  "quiz.submit": "提交答案",
  "quiz.grading": "批改中…",
  "quiz.hint": "提示",
  "quiz.hint.none": "暂无可用提示",
  "quiz.hint.error": "提示加载失败",
  "quiz.reveal": "揭晓答案",
  "quiz.grade.error": "提交失败，请重试",
  "quiz.answer.placeholder": "写下你的答案…",
  "quiz.legacy.note": "旧题目仅供回看，新练习请让老师重新出题",
  "quiz.submitted": "已提交",
  "quiz.submitted.answer": "已提交的答案",
  "quiz.explanation": "解析",
  "quiz.verdict.correct": "回答正确",
  "quiz.verdict.wrong": "再想想看",
  "quiz.verdict.partial": "部分正确",
  "quiz.evaluation.pending": "学习评价生成中…",
  "quiz.grounding.textbook": "教材依据",
  "quiz.grounding.partial": "部分教材依据",
  "quiz.grounding.more": "还有 %n 条依据",
  "quiz.grounding.collapse": "收起依据",
  "quiz.refresh.feedback": "刷新评价",

  "sessions.rename": "重命名",
  "sessions.rename.title": "重命名会话",
  "sessions.rename.placeholder": "会话标题",
  "sessions.delete": "删除会话",
  "sessions.delete.title": "删除这个会话？",
  "sessions.delete.desc": "删除后不可恢复",
  "sessions.delete.forget": "同时清除相关学习记忆",
  "sessions.move": "移动到工作区",
  "sessions.move.title": "选择工作区",
  "sessions.move.none": "未分组",
  "sessions.untitled": "未命名会话",
  "sessions.empty": "还没有会话",
  "sessions.new.workspace": "新工作区",
  "sessions.workspace.create": "创建工作区",
  "sessions.workspace.name": "工作区名称",

  "unit.chars": "字",

  "app.name": "Next Tutor",
  "app.tagline": "以教材为纲的 AI 私教",
  "suggestion.explain.text": "帮我讲一个知识点",
  "suggestion.explain": "用教材里的话讲清楚",
  "suggestion.quiz.text": "给我出几道题",
  "suggestion.quiz": "边做边学，即时反馈",
  "suggestion.error.text": "分析我的错题",
  "suggestion.error": "找到错因，举一反三",
  "suggestion.plan.text": "制定学习计划",
  "suggestion.plan": "目标拆成每天的任务",
  "chat.draft.refiles": "上次未发送的附件需重新选择",
  "chat.input.image.prompt": "请帮我解答这道图片中的题目",
};

const en: MessageDict = {
  "chat.title": "Tutor",
  "chat.new": "New chat",
  "chat.sessions": "Sessions",
  "chat.send": "Send",
  "chat.stop": "Stop",
  "chat.regenerate": "Regenerate",
  "chat.retrying": "Connection lost, retrying",
  "chat.retry.attempt": "attempt %n",
  "chat.stopped": "Generation stopped",
  "chat.error.connect": "Connection problem",
  "chat.error.interrupted": "Generation interrupted",
  "chat.load.earlier": "Load earlier messages",
  "chat.load.earlier.loading": "Loading…",
  "chat.notfound.title": "Session not found",
  "chat.notfound.desc": "It may have been deleted, or the link is stale",
  "chat.notfound.back": "Start a new chat",
  "chat.input.placeholder": "Ask the tutor anything…",
  "chat.input.hint": "AI tutoring is for reference only",
  "chat.input.upload.title": "Attach files (PDF/DOCX/PPTX/TXT/MD)",
  "chat.input.unsupported": "Unsupported file type",
  "chat.input.ocr": "Scan a problem",
  "chat.ocr.preview": "Recognized problem",
  "chat.grade.label": "Grade",
  "chat.empty.greeting.fallback": "What would you like to learn today?",
  "chat.guest.title": "Full tutoring needs an account",
  "chat.guest.desc":
    "Sign in for the full AI tutor, history and personalized plans",
  "chat.guest.signIn": "Sign in",
  "chat.scroll.bottom": "Back to bottom",

  "msg.copy": "Copy",
  "msg.copied": "Copied",

  "step.understanding": "Understanding",
  "step.planning": "Planning",
  "step.thinking": "Thinking",
  "step.tool_executing": "Using tools",

  "thinking.title": "Thinking",

  "tool.running": "Running",
  "tool.done": "Done",
  "tool.failed": "Failed",
  "tool.knowledge_search": "Search materials",
  "tool.generate_quiz": "Practice quiz",
  "tool.fit_quiz": "Match practice",
  "tool.recall_history": "Recall history",
  "tool.knowledge.sources": "Sources",
  "tool.knowledge.filtered": "filtered",
  "tool.knowledge.items": "items",
  "tool.knowledge.resource": "Resource",
  "tool.knowledge.textbookPage": "Textbook p. %n",
  "tool.knowledge.pdfPage": "PDF p. %n",
  "tool.knowledge.unpaged": "Unpaged",
  "tool.knowledge.figure": "figure",
  "tool.knowledge.table": "table",
  "tool.knowledge.conf.high": "high confidence",
  "tool.knowledge.conf.medium": "medium confidence",

  "quiz.questions.unit": "questions",
  "quiz.type.multiple_choice": "Multiple choice",
  "quiz.type.fill_blank": "Fill in the blank",
  "quiz.type.short_answer": "Short answer",
  "quiz.difficulty": "Difficulty",
  "quiz.submit": "Submit answer",
  "quiz.grading": "Grading…",
  "quiz.hint": "Hint",
  "quiz.hint.none": "No hint available",
  "quiz.hint.error": "Failed to load hint",
  "quiz.reveal": "Reveal answer",
  "quiz.grade.error": "Submit failed, please retry",
  "quiz.answer.placeholder": "Write your answer…",
  "quiz.legacy.note":
    "Legacy question is read-only; ask the tutor for a fresh quiz",
  "quiz.submitted": "Submitted",
  "quiz.submitted.answer": "Submitted answer",
  "quiz.explanation": "Explanation",
  "quiz.verdict.correct": "Correct",
  "quiz.verdict.wrong": "Not quite — think again",
  "quiz.verdict.partial": "Partially correct",
  "quiz.evaluation.pending": "Generating learning feedback…",
  "quiz.grounding.textbook": "Textbook-grounded",
  "quiz.grounding.partial": "Partially textbook-grounded",
  "quiz.grounding.more": "%n more sources",
  "quiz.grounding.collapse": "Collapse sources",
  "quiz.refresh.feedback": "Refresh feedback",

  "sessions.rename": "Rename",
  "sessions.rename.title": "Rename session",
  "sessions.rename.placeholder": "Session title",
  "sessions.delete": "Delete session",
  "sessions.delete.title": "Delete this session?",
  "sessions.delete.desc": "This cannot be undone",
  "sessions.delete.forget": "Also forget related learning memory",
  "sessions.move": "Move to workspace",
  "sessions.move.title": "Choose workspace",
  "sessions.move.none": "Ungrouped",
  "sessions.untitled": "Untitled session",
  "sessions.empty": "No sessions yet",
  "sessions.new.workspace": "New workspace",
  "sessions.workspace.create": "Create workspace",
  "sessions.workspace.name": "Workspace name",

  "unit.chars": "chars",

  "app.name": "Next Tutor",
  "app.tagline": "Textbook-aligned AI tutoring",
  "suggestion.explain.text": "Explain a concept",
  "suggestion.explain": "Grounded in your textbook",
  "suggestion.quiz.text": "Quiz me",
  "suggestion.quiz": "Learn by doing, instant feedback",
  "suggestion.error.text": "Review my mistakes",
  "suggestion.error": "Find the root cause",
  "suggestion.plan.text": "Plan my study",
  "suggestion.plan": "Goals broken into daily tasks",
  "chat.draft.refiles": "Previously attached files need re-selecting",
  "chat.input.image.prompt": "Please help me solve the problem in this image",
};

registerDicts(zh, en);
