// 课堂组件词条（CreateLessonModal / TemplatePicker 等，zh/en）。
// 页面级词条在 app/(workspace)/workspaces/[workspaceId]/classroom/strings.ts。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    "cls.form.title": "一键备课",
    "cls.form.topic": "主题",
    "cls.form.topic.placeholder": "例如：动量守恒与碰撞（2–120 字）",
    "cls.form.topic.count": "%n/120",
    "cls.form.goals": "学习目标（最多 5 项，可不填）",
    "cls.form.goals.placeholder": "例如：会判断系统动量是否守恒（每项 ≤120 字）",
    "cls.form.goals.add": "添加目标",
    "cls.form.sources": "教材 / 章节",
    "cls.form.sources.desc": "勾选本学习区的教材章节作为课程依据；跨卷保留卷名与页码。最多 8 个文件、12 个章节。",
    "cls.form.sources.empty": "本学习区还没有可选教材。可以先按主题备课，或到学习区设置里选入教材。",
    "cls.form.sources.general.hint": "未选教材时将按「通识资料」生成主题课程，不伪造教材依据。",
    "cls.form.sources.file": "文件",
    "cls.form.sources.chapters.load": "选择章节",
    "cls.form.sources.chapters.loading": "章节加载中…",
    "cls.form.sources.chapters.none": "整本使用（无章节目录）",
    "cls.form.sources.chapters.count": "已选 %n/12 章",
    "cls.form.sources.sessions": "额外对话材料（默认不选）",
    "cls.form.sources.sessions.desc": "仅添加你明确勾选的对话；不会扩大学习区可见性，也不发送给外部检索。",
    "cls.form.sources.sessions.none": "本学习区还没有对话。",
    "cls.form.duration": "时长",
    "cls.form.duration.unit": "分钟",
    "cls.form.duration.hint": "指讲授 + 建议思考时间，不含你自由提问的时间。",
    "cls.form.pages": "页数",
    "cls.form.pages.auto": "自动（按时长匹配）",
    "cls.form.pages.range": "%n 页左右",
    "cls.form.pages.hint": "硬上限 24 页。",
    "cls.form.grade": "学段",
    "cls.form.grade.auto": "自动",
    "cls.form.language": "语言",
    "cls.form.language.auto": "跟随主题",
    "cls.form.pedagogy": "教学模板",
    "cls.form.theme": "视觉模板",
    "cls.form.policy": "教材策略",
    "cls.form.policy.strict_textbook": "严格教材（只用所选资料）",
    "cls.form.policy.textbook_plus": "教材为主 + 联网补充",
    "cls.form.policy.web_topic": "通识资料（不依赖教材）",
    "cls.form.policy.auto": "自动（有教材时教材为主）",
    "cls.form.research": "联网补充",
    "cls.form.research.desc": "启用后会检索主题关键词补充资料；严格教材时仍可单独搜图。",
    "cls.form.research.unavailable": "联网检索暂不可用：%s",
    "cls.form.timeliness": "时效",
    "cls.form.timeliness.basic": "基础知识",
    "cls.form.timeliness.recent_year": "近一年",
    "cls.form.timeliness.recent_month": "近一月",
    "cls.form.image": "图片",
    "cls.form.image.none": "不用图",
    "cls.form.image.balanced": "适量",
    "cls.form.image.rich": "丰富",
    "cls.form.image.hint": "「丰富」也只在有教学作用时使用图片。",
    "cls.form.image.unavailable": "图片搜索暂不可用：%s",
    "cls.form.checkpoint": "随堂检查",
    "cls.form.checkpoint.none": "关闭",
    "cls.form.checkpoint.light": "轻量",
    "cls.form.checkpoint.standard": "标准",
    "cls.form.checkpoint.hint": "标准 = 15 分钟课 2 个检查点。",
    "cls.form.voice": "语音",
    "cls.form.voice.auto": "自动（云端优先）",
    "cls.form.voice.cloud": "云端语音",
    "cls.form.voice.local": "本地语音",
    "cls.form.voice.silent": "只看讲稿",
    "cls.form.voice.unavailable": "语音合成暂不可用：%s",
    "cls.form.voice.fallback": "云失败回退本地",
    "cls.form.voice.fallback.hint": "关闭后云端失败将只切文字模式。",
    "cls.form.voice.speed": "语速 %sx",
    "cls.form.custom": "自定义教学要求",
    "cls.form.custom.placeholder": "可选。例如：多用生活例子；强调量纲分析；结尾给一张自检表。（≤1000 字）",
    "cls.form.custom.count": "%n/1000",
    "cls.form.more": "更多设置",
    "cls.form.privacy": "生成会使用所选资料。启用联网时会检索主题关键词；启用云端语音时讲稿将发送给语音服务。",
    "cls.form.submit": "生成课程",
    "cls.form.submitting": "创建中…",
    "cls.form.outline.first": "先看大纲",
    "cls.form.cancel": "取消",
    "cls.form.error": "创建失败",
    "cls.form.cap.renderer": "课件渲染服务暂不可用（%s），生成的排版检查将降级。",
    "cls.form.topic.required": "请填写主题（2–120 字）",
    "cls.form.topic.too.long": "主题不能超过 120 字",
    "cls.form.topic.too.short": "主题至少 2 个字",
    "cls.form.chapters.limit": "最多选择 12 个章节",
    "cls.form.files.limit": "最多选择 8 个文件",
  },
  en: {
    "cls.form.title": "Quick lesson",
    "cls.form.topic": "Topic",
    "cls.form.topic.placeholder": "e.g. Conservation of momentum (2–120 chars)",
    "cls.form.topic.count": "%n/120",
    "cls.form.goals": "Learning goals (up to 5, optional)",
    "cls.form.goals.placeholder": "e.g. Determine when momentum is conserved (≤120 chars each)",
    "cls.form.goals.add": "Add goal",
    "cls.form.sources": "Textbooks / chapters",
    "cls.form.sources.desc": "Pick chapters from this workspace as the lesson basis; volume names and page numbers are preserved. Max 8 files, 12 chapters.",
    "cls.form.sources.empty": "No selectable textbooks in this workspace yet. Start with a topic, or add textbooks in workspace settings.",
    "cls.form.sources.general.hint": "Without textbooks the lesson is generated from general knowledge — never faked textbook citations.",
    "cls.form.sources.file": "file",
    "cls.form.sources.chapters.load": "Choose chapters",
    "cls.form.sources.chapters.loading": "Loading chapters…",
    "cls.form.sources.chapters.none": "Use whole file (no chapter outline)",
    "cls.form.sources.chapters.count": "%n/12 chapters",
    "cls.form.sources.sessions": "Extra chat materials (off by default)",
    "cls.form.sources.sessions.desc": "Only chats you explicitly pick are added; visibility never widens and nothing extra goes to external search.",
    "cls.form.sources.sessions.none": "No chats in this workspace yet.",
    "cls.form.duration": "Duration",
    "cls.form.duration.unit": "min",
    "cls.form.duration.hint": "Lecture + suggested thinking time, excluding your own questions.",
    "cls.form.pages": "Pages",
    "cls.form.pages.auto": "Auto (match duration)",
    "cls.form.pages.range": "≈ %n pages",
    "cls.form.pages.hint": "Hard cap: 24 pages.",
    "cls.form.grade": "Level",
    "cls.form.grade.auto": "Auto",
    "cls.form.language": "Language",
    "cls.form.language.auto": "Follow topic",
    "cls.form.pedagogy": "Teaching template",
    "cls.form.theme": "Visual theme",
    "cls.form.policy": "Source policy",
    "cls.form.policy.strict_textbook": "Strict textbook (selected sources only)",
    "cls.form.policy.textbook_plus": "Textbook + web supplement",
    "cls.form.policy.web_topic": "General knowledge (no textbook)",
    "cls.form.policy.auto": "Auto (textbook when available)",
    "cls.form.research": "Web supplement",
    "cls.form.research.desc": "Searches topic keywords for extra material; strict textbook can still search images alone.",
    "cls.form.research.unavailable": "Web search unavailable: %s",
    "cls.form.timeliness": "Freshness",
    "cls.form.timeliness.basic": "Established knowledge",
    "cls.form.timeliness.recent_year": "Past year",
    "cls.form.timeliness.recent_month": "Past month",
    "cls.form.image": "Images",
    "cls.form.image.none": "None",
    "cls.form.image.balanced": "Balanced",
    "cls.form.image.rich": "Rich",
    "cls.form.image.hint": "Even \u201crich\u201d only uses images that teach something.",
    "cls.form.image.unavailable": "Image search unavailable: %s",
    "cls.form.checkpoint": "Checkpoints",
    "cls.form.checkpoint.none": "Off",
    "cls.form.checkpoint.light": "Light",
    "cls.form.checkpoint.standard": "Standard",
    "cls.form.checkpoint.hint": "Standard = 2 checkpoints per 15-minute lesson.",
    "cls.form.voice": "Voice",
    "cls.form.voice.auto": "Auto (cloud first)",
    "cls.form.voice.cloud": "Cloud voice",
    "cls.form.voice.local": "Local voice",
    "cls.form.voice.silent": "Script only",
    "cls.form.voice.unavailable": "TTS unavailable: %s",
    "cls.form.voice.fallback": "Fall back to local on cloud failure",
    "cls.form.voice.fallback.hint": "Turn off to switch to text-only mode when cloud fails.",
    "cls.form.voice.speed": "Speed %sx",
    "cls.form.custom": "Custom requirements",
    "cls.form.custom.placeholder": "Optional. e.g. more everyday examples; stress dimensional analysis; end with a self-check list. (≤1000 chars)",
    "cls.form.custom.count": "%n/1000",
    "cls.form.more": "More settings",
    "cls.form.privacy": "Generation uses the selected materials. Web supplement searches topic keywords; cloud voice sends the script to the speech service.",
    "cls.form.submit": "Generate lesson",
    "cls.form.submitting": "Creating…",
    "cls.form.outline.first": "Outline first",
    "cls.form.cancel": "Cancel",
    "cls.form.error": "Failed to create",
    "cls.form.cap.renderer": "Lesson renderer unavailable (%s); layout checks will be degraded.",
    "cls.form.topic.required": "Enter a topic (2–120 chars)",
    "cls.form.topic.too.long": "Topic must be ≤120 characters",
    "cls.form.topic.too.short": "Topic needs at least 2 characters",
    "cls.form.chapters.limit": "Up to 12 chapters",
    "cls.form.files.limit": "Up to 8 files",
  },
};
