// 课堂组件词条（CreateLessonModal / TemplatePicker 等，zh/en）。
// 页面级词条在 app/(workspace)/workspaces/[workspaceId]/classroom/strings.ts。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    "cls.form.title": "一键备课",
    "cls.form.topic": "主题",
    "cls.form.topic.placeholder": "例如：动量守恒与碰撞（2–120 字）",
    "cls.form.topic.count": "%n/120",
    "cls.form.goals": "学习目标（最多 5 项，可不填）",
    "cls.form.goals.placeholder": "例如：会判断系统动量是否守恒（每项 ≤120 字）",
    "cls.form.goals.add": "添加目标",
    "cls.form.sources": "教材 / 章节",
    "cls.form.sources.desc": "勾选本学习区的教材章节作为课程依据；跨卷保留卷名与页码。最多 8 个文件、12 个章节。",
    "cls.form.sources.empty": "本学习区还没有可选教材。可以先按主题备课，或到学习区设置里选入教材。",
    "cls.form.sources.general.hint": "未选教材时将按「通识资料」生成主题课程，不伪造教材依据。",
    "cls.form.sources.file": "文件",
    "cls.form.sources.chapters.load": "选择章节",
    "cls.form.sources.chapters.loading": "章节加载中…",
    "cls.form.sources.chapters.none": "整本使用（无章节目录）",
    "cls.form.sources.chapters.count": "已选 %n/12 章",
    "cls.form.sources.sessions": "额外对话材料（默认不选）",
    "cls.form.sources.sessions.desc": "仅添加你明确勾选的对话；不会扩大学习区可见性，也不发送给外部检索。",
    "cls.form.sources.sessions.none": "本学习区还没有对话。",
    "cls.form.duration": "时长",
    "cls.form.duration.unit": "分钟",
    "cls.form.duration.hint": "指讲授 + 建议思考时间，不含你自由提问的时间。",
    "cls.form.pages": "页数",
    "cls.form.pages.auto": "自动（按时长匹配）",
    "cls.form.pages.range": "%n 页左右",
    "cls.form.pages.hint": "硬上限 24 页。",
    "cls.form.grade": "学段",
    "cls.form.grade.auto": "自动",
    "cls.form.language": "语言",
    "cls.form.language.auto": "跟随主题",
    "cls.form.pedagogy": "教学模板",
    "cls.form.theme": "视觉模板",
    "cls.form.policy": "教材策略",
    "cls.form.policy.strict_textbook": "严格教材（只用所选资料）",
    "cls.form.policy.textbook_plus": "教材为主 + 联网补充",
    "cls.form.policy.web_topic": "通识资料（不依赖教材）",
    "cls.form.policy.auto": "自动（有教材时教材为主）",
    "cls.form.research": "联网补充",
    "cls.form.research.desc": "启用后会检索主题关键词补充资料；严格教材时仍可单独搜图。",
    "cls.form.research.unavailable": "联网检索暂不可用：%s",
    "cls.form.timeliness": "时效",
    "cls.form.timeliness.basic": "基础知识",
    "cls.form.timeliness.recent_year": "近一年",
    "cls.form.timeliness.recent_month": "近一月",
    "cls.form.image": "图片",
    "cls.form.image.none": "不用图",
    "cls.form.image.balanced": "适量",
    "cls.form.image.rich": "丰富",
    "cls.form.image.hint": "「丰富」也只在有教学作用时使用图片。",
    "cls.form.image.unavailable": "图片搜索暂不可用：%s",
    "cls.form.checkpoint": "随堂检查",
    "cls.form.checkpoint.none": "关闭",
    "cls.form.checkpoint.light": "轻量",
    "cls.form.checkpoint.standard": "标准",
    "cls.form.checkpoint.hint": "标准 = 15 分钟课 2 个检查点。",
    "cls.form.voice": "语音",
    "cls.form.voice.auto": "自动（云端优先）",
    "cls.form.voice.cloud": "云端语音",
    "cls.form.voice.local": "本地语音",
    "cls.form.voice.silent": "只看讲稿",
    "cls.form.voice.unavailable": "语音合成暂不可用：%s",
    "cls.form.voice.fallback": "云失败回退本地",
    "cls.form.voice.fallback.hint": "关闭后云端失败将只切文字模式。",
    "cls.form.voice.speed": "语速 %sx",
    "cls.form.custom": "自定义教学要求",
    "cls.form.custom.placeholder": "可选。例如：多用生活例子；强调量纲分析；结尾给一张自检表。（≤1000 字）",
    "cls.form.custom.count": "%n/1000",
    "cls.form.more": "更多设置",
    "cls.form.privacy": "生成会使用所选资料。启用联网时会检索主题关键词；启用云端语音时讲稿将发送给语音服务。",
    "cls.form.submit": "生成课程",
    "cls.form.submitting": "创建中…",
    "cls.form.outline.first": "先看大纲",
    "cls.form.cancel": "取消",
    "cls.form.error": "创建失败",
    "cls.form.cap.renderer": "课件渲染服务暂不可用（%s），生成的排版检查将降级。",
    "cls.form.topic.required": "请填写主题（2–120 字）",
    "cls.form.topic.too.long": "主题不能超过 120 字",
    "cls.form.topic.too.short": "主题至少 2 个字",
    "cls.form.chapters.limit": "最多选择 12 个章节",
    "cls.progress.stages": "生成阶段",
    "cls.progress.pages": "已完成 %c/%t 页",
    "cls.progress.minutes": "通常需要数分钟；可以关闭此页稍后回来。",
    "cls.progress.polling": "实时连接中断，已切换为定时刷新。",
    "cls.progress.failed": "生成失败",
    "cls.progress.retry": "重试此阶段",
    "cls.progress.or.settings": "或在备课设置里调整后重新生成",
    "cls.progress.cancelled": "已取消：草稿与已发布版本保留，可随时重试。",
    "cls.progress.ready": "课程已准备好，可以开始上课。",
    "cls.progress.needs_input": "需要补充信息：请在下方调整设置后继续。",
    "cls.progress.cancel": "取消任务",
    "cls.progress.cancelling": "正在取消（完成后停止后续工作）…",
    "cls.progress.draft.note": "已生成的草稿页仍可预览。",
    "cls.progress.outline.review": "查看课程大纲",
    "cls.progress.outline.hint": "可直接修改页标题；确认后开始编写课件与讲稿。",
    "cls.progress.outline.loading": "大纲加载中…",
    "cls.progress.outline.confirm": "确认并生成",
    "cls.stage.resolve_sources": "读取教材",
    "cls.stage.research": "查找补充资料",
    "cls.stage.outline": "组织课程",
    "cls.stage.author_slides": "编写课件与讲稿",
    "cls.stage.render": "检查排版",
    "cls.stage.publish": "准备开课",
    "cls.edit.conflict": "内容已更新：有人（或另一个标签页）已先生成新版本。",
    "cls.edit.reload": "重新载入",
    "cls.edit.failed": "修订未完成",
    "cls.edit.slow": "修订仍在进行，稍后会自动显示新版本。",
    "cls.edit.outline": "课程目录",
    "cls.edit.prev": "上一页",
    "cls.edit.next": "下一页",
    "cls.edit.theme": "视觉风格",
    "cls.edit.theme.hint": "换风格即时重新排版，不重新生成内容。",
    "cls.tab.script": "讲稿",
    "cls.tab.sources": "来源",
    "cls.tab.settings": "设置",
    "cls.script.title": "本页讲稿",
    "cls.script.edit": "编辑本页",
    "cls.script.cancel.edit": "取消编辑",
    "cls.script.field.title": "标题",
    "cls.script.field.bullets": "要点",
    "cls.script.field.caption": "图注",
    "cls.script.field.segments": "讲稿段",
    "cls.script.rich.bullet": "该要点含公式/强调格式，暂不支持在线编辑",
    "cls.script.save": "保存并生成新版本",
    "cls.script.save.hint": "保存会创建新版本；正在上课的旧版本不受影响。",
    "cls.role.motivation": "引入",
    "cls.role.explain": "讲解",
    "cls.role.derive": "推导",
    "cls.role.example": "例子",
    "cls.role.misconception": "误区",
    "cls.role.transition": "衔接",
    "cls.role.summary": "总结",
    "cls.sources.title": "本页来源",
    "cls.sources.none": "本页没有引用外部来源（教师讲解）。",
    "cls.sources.web": "网络",
    "cls.sources.book": "教材",
    "cls.regen.title": "本页重生成",
    "cls.regen.detail": "更详细",
    "cls.regen.brief": "更简洁",
    "cls.regen.example": "换个例子",
    "cls.regen.custom.ph": "自定义修改要求…",
    "cls.regen.go": "重生成",
    "cls.img.title": "换图",
    "cls.img.search": "搜索候选图",
    "cls.img.empty": "没有找到合适的候选图，可换个说法再试。",
    "cls.img.noblock": "本页没有图片块。",
    "cls.page.ops": "页面操作",
    "cls.page.up": "上移",
    "cls.page.down": "下移",
    "cls.page.delete": "删除本页",
    "cls.page.last": "最后一页不能删除。",
    "cls.export.zip": "下载课件",
    "cls.export.notes": "下载讲稿",
    "cls.form.files.limit": "最多选择 8 个文件",
  },
  en: {
    "cls.form.title": "Quick lesson",
    "cls.form.topic": "Topic",
    "cls.form.topic.placeholder": "e.g. Conservation of momentum (2–120 chars)",
    "cls.form.topic.count": "%n/120",
    "cls.form.goals": "Learning goals (up to 5, optional)",
    "cls.form.goals.placeholder": "e.g. Determine when momentum is conserved (≤120 chars each)",
    "cls.form.goals.add": "Add goal",
    "cls.form.sources": "Textbooks / chapters",
    "cls.form.sources.desc": "Pick chapters from this workspace as the lesson basis; volume names and page numbers are preserved. Max 8 files, 12 chapters.",
    "cls.form.sources.empty": "No selectable textbooks in this workspace yet. Start with a topic, or add textbooks in workspace settings.",
    "cls.form.sources.general.hint": "Without textbooks the lesson is generated from general knowledge — never faked textbook citations.",
    "cls.form.sources.file": "file",
    "cls.form.sources.chapters.load": "Choose chapters",
    "cls.form.sources.chapters.loading": "Loading chapters…",
    "cls.form.sources.chapters.none": "Use whole file (no chapter outline)",
    "cls.form.sources.chapters.count": "%n/12 chapters",
    "cls.form.sources.sessions": "Extra chat materials (off by default)",
    "cls.form.sources.sessions.desc": "Only chats you explicitly pick are added; visibility never widens and nothing extra goes to external search.",
    "cls.form.sources.sessions.none": "No chats in this workspace yet.",
    "cls.form.duration": "Duration",
    "cls.form.duration.unit": "min",
    "cls.form.duration.hint": "Lecture + suggested thinking time, excluding your own questions.",
    "cls.form.pages": "Pages",
    "cls.form.pages.auto": "Auto (match duration)",
    "cls.form.pages.range": "≈ %n pages",
    "cls.form.pages.hint": "Hard cap: 24 pages.",
    "cls.form.grade": "Level",
    "cls.form.grade.auto": "Auto",
    "cls.form.language": "Language",
    "cls.form.language.auto": "Follow topic",
    "cls.form.pedagogy": "Teaching template",
    "cls.form.theme": "Visual theme",
    "cls.form.policy": "Source policy",
    "cls.form.policy.strict_textbook": "Strict textbook (selected sources only)",
    "cls.form.policy.textbook_plus": "Textbook + web supplement",
    "cls.form.policy.web_topic": "General knowledge (no textbook)",
    "cls.form.policy.auto": "Auto (textbook when available)",
    "cls.form.research": "Web supplement",
    "cls.form.research.desc": "Searches topic keywords for extra material; strict textbook can still search images alone.",
    "cls.form.research.unavailable": "Web search unavailable: %s",
    "cls.form.timeliness": "Freshness",
    "cls.form.timeliness.basic": "Established knowledge",
    "cls.form.timeliness.recent_year": "Past year",
    "cls.form.timeliness.recent_month": "Past month",
    "cls.form.image": "Images",
    "cls.form.image.none": "None",
    "cls.form.image.balanced": "Balanced",
    "cls.form.image.rich": "Rich",
    "cls.form.image.hint": "Even \u201crich\u201d only uses images that teach something.",
    "cls.form.image.unavailable": "Image search unavailable: %s",
    "cls.form.checkpoint": "Checkpoints",
    "cls.form.checkpoint.none": "Off",
    "cls.form.checkpoint.light": "Light",
    "cls.form.checkpoint.standard": "Standard",
    "cls.form.checkpoint.hint": "Standard = 2 checkpoints per 15-minute lesson.",
    "cls.form.voice": "Voice",
    "cls.form.voice.auto": "Auto (cloud first)",
    "cls.form.voice.cloud": "Cloud voice",
    "cls.form.voice.local": "Local voice",
    "cls.form.voice.silent": "Script only",
    "cls.form.voice.unavailable": "TTS unavailable: %s",
    "cls.form.voice.fallback": "Fall back to local on cloud failure",
    "cls.form.voice.fallback.hint": "Turn off to switch to text-only mode when cloud fails.",
    "cls.form.voice.speed": "Speed %sx",
    "cls.form.custom": "Custom requirements",
    "cls.form.custom.placeholder": "Optional. e.g. more everyday examples; stress dimensional analysis; end with a self-check list. (≤1000 chars)",
    "cls.form.custom.count": "%n/1000",
    "cls.form.more": "More settings",
    "cls.form.privacy": "Generation uses the selected materials. Web supplement searches topic keywords; cloud voice sends the script to the speech service.",
    "cls.form.submit": "Generate lesson",
    "cls.form.submitting": "Creating…",
    "cls.form.outline.first": "Outline first",
    "cls.form.cancel": "Cancel",
    "cls.form.error": "Failed to create",
    "cls.form.cap.renderer": "Lesson renderer unavailable (%s); layout checks will be degraded.",
    "cls.form.topic.required": "Enter a topic (2–120 chars)",
    "cls.form.topic.too.long": "Topic must be ≤120 characters",
    "cls.form.topic.too.short": "Topic needs at least 2 characters",
    "cls.form.chapters.limit": "Up to 12 chapters",
    "cls.progress.stages": "Stages",
    "cls.progress.pages": "%c/%t slides done",
    "cls.progress.minutes": "Usually a few minutes; you can leave and come back.",
    "cls.progress.polling": "Live connection lost; refreshing periodically.",
    "cls.progress.failed": "Generation failed",
    "cls.progress.retry": "Retry this stage",
    "cls.progress.or.settings": "or adjust settings and generate again",
    "cls.progress.cancelled": "Cancelled: drafts and published versions are kept; retry anytime.",
    "cls.progress.ready": "Lesson ready — you can start the class.",
    "cls.progress.needs_input": "Needs more input: adjust settings below to continue.",
    "cls.progress.cancel": "Cancel task",
    "cls.progress.cancelling": "Cancelling (stops further work once done)…",
    "cls.progress.draft.note": "Draft slides that were generated are still previewable.",
    "cls.progress.outline.review": "Review outline",
    "cls.progress.outline.hint": "Edit page titles inline; confirm to start authoring slides.",
    "cls.progress.outline.loading": "Loading outline…",
    "cls.progress.outline.confirm": "Confirm and generate",
    "cls.stage.resolve_sources": "Reading textbooks",
    "cls.stage.research": "Finding supplements",
    "cls.stage.outline": "Organizing the lesson",
    "cls.stage.author_slides": "Writing slides & script",
    "cls.stage.render": "Checking layout",
    "cls.stage.publish": "Preparing class",
    "cls.edit.conflict": "Content updated: someone (or another tab) published a newer version first.",
    "cls.edit.reload": "Reload",
    "cls.edit.failed": "Revision did not finish",
    "cls.edit.slow": "Revision still running; the new version will appear shortly.",
    "cls.edit.outline": "Lesson outline",
    "cls.edit.prev": "Prev",
    "cls.edit.next": "Next",
    "cls.edit.theme": "Visual theme",
    "cls.edit.theme.hint": "Switching re-lays out instantly without regenerating content.",
    "cls.tab.script": "Script",
    "cls.tab.sources": "Sources",
    "cls.tab.settings": "Settings",
    "cls.script.title": "Script for this slide",
    "cls.script.edit": "Edit slide",
    "cls.script.cancel.edit": "Cancel editing",
    "cls.script.field.title": "Title",
    "cls.script.field.bullets": "Key points",
    "cls.script.field.caption": "Caption",
    "cls.script.field.segments": "Narration segments",
    "cls.script.rich.bullet": "This bullet contains formula/emphasis formatting and can't be edited inline yet",
    "cls.script.save": "Save as new version",
    "cls.script.save.hint": "Saving creates a new version; ongoing classes keep the old one.",
    "cls.role.motivation": "Motivation",
    "cls.role.explain": "Explain",
    "cls.role.derive": "Derive",
    "cls.role.example": "Example",
    "cls.role.misconception": "Misconception",
    "cls.role.transition": "Transition",
    "cls.role.summary": "Summary",
    "cls.sources.title": "Sources for this slide",
    "cls.sources.none": "No external sources cited on this slide (teacher explanation).",
    "cls.sources.web": "Web",
    "cls.sources.book": "Textbook",
    "cls.regen.title": "Regenerate this slide",
    "cls.regen.detail": "More detail",
    "cls.regen.brief": "More concise",
    "cls.regen.example": "Another example",
    "cls.regen.custom.ph": "Custom instruction…",
    "cls.regen.go": "Regenerate",
    "cls.img.title": "Replace image",
    "cls.img.search": "Search candidates",
    "cls.img.empty": "No suitable candidates found; try rephrasing.",
    "cls.img.noblock": "No image block on this slide.",
    "cls.page.ops": "Page operations",
    "cls.page.up": "Move up",
    "cls.page.down": "Move down",
    "cls.page.delete": "Delete slide",
    "cls.page.last": "The last slide cannot be deleted.",
    "cls.export.zip": "Download deck",
    "cls.export.notes": "Download notes",
    "cls.form.files.limit": "Up to 8 files",
  },
};
