import type { PageStrings } from "@/lib/i18n-page";

// /admin 管理台词条：页签 + 账号与数据 / 生命周期与记忆策略 / OCR 策略 / 公共库归档。
// 字段说明一律为 Field 底部的常驻帮助小字（不再悬浮遮挡），文案保持一行短句。
export const STRINGS = {
  zh: {
    "adm.title": "管理台",
    "adm.desc": "账号与数据治理、生命周期与记忆策略、教材 OCR 与公共库归档。",

    // 页签
    "adm.tab.accounts": "账号与数据",
    "adm.tab.policy": "生命周期与记忆",
    "adm.tab.ocr": "OCR 与解析策略",
    "adm.tab.trash": "公共库归档",

    // 账号与数据
    "adm.stat.accounts": "账号数",
    "adm.stat.total": "总占用",
    "adm.stat.sessions": "会话总数",
    "adm.stat.files": "文件总数",
    "adm.users.title": "账号列表",
    "adm.users.desc": "点击任意行展开该账号的占用明细；可清理聊天数据或彻底删除账号。",
    "adm.users.email": "邮箱",
    "adm.users.username": "用户名",
    "adm.users.role": "角色",
    "adm.users.created": "注册时间",
    "adm.users.lastLogin": "最近登录",
    "adm.users.storage": "占用",
    "adm.users.storage.chat": "聊天与资料库",
    "adm.users.storage.uploads": "会话上传",
    "adm.users.storage.notes": "笔记",
    "adm.users.storage.students": "学习档案",
    "adm.users.storage.knowledge": "知识图谱",
    "adm.users.storage.trashB": "回收站",
    "adm.users.storage.sessions": "会话数",
    "adm.users.storage.files": "文件数",
    "adm.users.actions": "操作",
    "adm.users.search": "搜索邮箱 / 用户名",
    "adm.users.role.all": "全部角色",
    "adm.users.role.student": "学生",
    "adm.users.role.parent": "家长",
    "adm.users.role.teacher": "教师",
    "adm.users.role.admin": "管理员",
    "adm.users.summary": "{count} 个账号 · 总占用 {size}",
    "adm.users.noMatch": "没有匹配的账号",
    "adm.users.clearChat": "清空聊天",
    "adm.users.clearChat.title": "清空聊天数据",
    "adm.users.clearChat.all": "完整清理（连会话一起删）",
    "adm.users.clearChat.all.desc": "删除全部会话、转写与调用追踪、上传附件、工作区、资料库文件及相关回收站条目；账号、笔记与学习档案保留。",
    "adm.users.clearChat.uploads_only": "仅清理上传文件",
    "adm.users.clearChat.uploads_only.desc": "只删除上传的原始文件与提取文本（会话附件、资料库文件、工作区上传）；聊天记录文本保留。",
    "adm.users.clearChat.estimate": "预计可释放约 {size}",
    "adm.users.clearChat.confirm": "确认清理",
    "adm.users.notice.cleared": "清理完成，已释放 {size}",
    "adm.users.purge": "彻底删除",
    "adm.users.purgeTitle": "彻底删除账号",
    "adm.users.purgeDesc": "将永久删除该账号及其名下全部数据（聊天、上传、笔记、学习档案、知识图谱、回收站），不可恢复且立即无法登录。键入该账号邮箱以确认：",
    "adm.users.purgeConfirm": "彻底删除",
    "adm.users.notice.purged": "账号已彻底删除，释放 {size}",
    "adm.users.notice.fail": "操作失败，请重试",
    "adm.users.adminBadge": "管理员",
    "adm.users.empty": "暂无账号",
    "adm.users.loadFail": "加载失败（需要管理员权限）",
    "adm.users.cancel": "取消",
    "adm.users.never": "从未登录",
    "adm.users.self": "（我）",

    // 生命周期与记忆策略
    "adm.policy.title": "生命周期与记忆策略",
    "adm.policy.desc": "回收站保留与提示词记忆窗口的全局默认值，保存后立即生效。",
    "adm.policy.save": "保存策略",
    "adm.policy.saved": "已保存",
    "adm.policy.trash": "回收站",
    "adm.policy.trash.defaultDays": "默认保留（天）",
    "adm.policy.trash.defaultDays.hint": "default_days · 1–30，新用户默认保留天数",
    "adm.policy.trash.userMaxDays": "用户上限（天）",
    "adm.policy.trash.userMaxDays.hint": "user_max_days · 1–30，用户可自调的最大值",
    "adm.policy.trash.forcedMaxDays": "强制上限（天）",
    "adm.policy.trash.forcedMaxDays.hint": "forced_max_days · 1–365，到期必删的绝对上限",
    "adm.policy.trash.mode": "清理模式",
    "adm.policy.trash.mode.hint": "auto 到期自动清理；manual 仅手动彻底删除",
    "adm.policy.trash.mode.auto": "自动到期清理",
    "adm.policy.trash.mode.manual": "仅手动彻底删除",
    "adm.policy.memory": "提示词记忆窗口",
    "adm.policy.memory.defaultWindow": "默认窗口（轮）",
    "adm.policy.memory.defaultWindow.hint": "default_window · 最小 5，默认覆盖轮数",
    "adm.policy.memory.maxWindow": "最大窗口（轮）",
    "adm.policy.memory.maxWindow.hint": "max_window · 最小 5，用户可设上限",
    "adm.policy.memory.coreLimit": "核心记忆上限（字符）",
    "adm.policy.memory.coreLimit.hint": "core_char_limit，单条核心记忆字符上限",
    "adm.policy.memory.directiveLimit": "指令上限（字符）",
    "adm.policy.memory.directiveLimit.hint": "directive_char_limit，长期指令字符上限",

    // 教材后台 OCR 策略
    "adm.ocr.title": "教材后台 OCR 策略",
    "adm.ocr.desc": "仅影响教材后台 OCR，修改后无需重启。",
    "adm.ocr.detail": "详细说明",
    "adm.ocr.hint": "仅影响教材后台 OCR；聊天附件、工作区和普通资料库仍使用原有短重试与本地回退。默认持续使用多模态 API；失败页默认每 10 秒重试（可调 0），空内容类页达到尝试上限后按空白页收尾。修改后无需重启。",
    "adm.ocr.concurrency": "并发页面数",
    "adm.ocr.concurrency.hint": "concurrency · 1–100，并行提交页面数",
    "adm.ocr.failureMode": "失败处理",
    "adm.ocr.failureMode.hint": "多次失败后：持续重试 / 本地 OCR / 暂停",
    "adm.ocr.failureMode.persistentApi": "持续 API 重试（默认，不降级）",
    "adm.ocr.failureMode.boundedThenLocal": "达上限后本地 OCR",
    "adm.ocr.failureMode.boundedApiOnly": "达上限后暂停",
    "adm.ocr.maxAttempts": "最大尝试次数",
    "adm.ocr.maxAttempts.hint": "max_attempts · 1–100，单页最大尝试次数",
    "adm.ocr.retryInterval": "重试间隔（秒）",
    "adm.ocr.retryInterval.hint": "retry_interval_seconds · 0–3600，0 为立即重试",
    "adm.ocr.requestTimeout": "单次超时（秒）",
    "adm.ocr.requestTimeout.hint": "request_timeout_seconds · 10–300，单次请求超时",
    "adm.ocr.apply": "应用策略",
    "adm.ocr.applied": "已应用",
    "adm.ocr.status": "运行状态",
    "adm.ocr.stat.concurrency": "当前并发",
    "adm.ocr.stat.pending": "待生效并发",
    "adm.ocr.stat.jobs": "活动任务",
    "adm.ocr.stat.pages": "活动页面",
    "adm.ocr.stat.waiting": "重试等待页",
    "adm.ocr.stat.failureMode": "重试策略",
    "adm.ocr.stat.nextRetry": "下次重试",
    "adm.ocr.stat.generation": "策略代次",
    "adm.ocr.stat.version": "策略版本",

    "adm.pipeline.title": "教材解析并行策略",
    "adm.pipeline.desc": "只改执行调度（可切回原有串行），解析方式与产出完全不变；修改后无需重启。",
    "adm.pipeline.detail": "详细说明",
    "adm.pipeline.hint": "并行模式只让相互独立的调用在时间上重叠：逐章概念抽取、教材组内的卷、排队中的教材可并行（OCR 页并发仍由上方 OCR 策略单独限流）。选择「原有串行」后所有并发强制为 1，执行顺序与历史实现完全一致。429 风暴由既有重试退避兜底；遇到限流可调低 LLM 并发。",
    "adm.pipeline.mode": "解析模式",
    "adm.pipeline.mode.hint": "parallel = 并行加速；legacy = 原有严格串行",
    "adm.pipeline.mode.parallel": "并行加速（默认）",
    "adm.pipeline.mode.legacy": "原有串行",
    "adm.pipeline.build": "同时构建教材数",
    "adm.pipeline.build.hint": "build_concurrency · 1–4，同一用户/公共库同时在建的教材本数",
    "adm.pipeline.volume": "组内并行卷数",
    "adm.pipeline.volume.hint": "volume_concurrency · 1–4，教材组同时处理的卷数",
    "adm.pipeline.llm": "图谱 LLM 并发",
    "adm.pipeline.llm.hint": "llm_concurrency · 1–8，逐章概念抽取等调用的全局并发",
    "adm.pipeline.apply": "应用策略",
    "adm.pipeline.applied": "已应用",
    "adm.pipeline.status": "运行状态",
    "adm.pipeline.stat.mode": "当前模式",
    "adm.pipeline.stat.build": "生效·教材并发",
    "adm.pipeline.stat.volume": "生效·卷并发",
    "adm.pipeline.stat.llm": "生效·LLM 并发",
    "adm.pipeline.stat.gateActive": "在途 LLM 调用",
    "adm.pipeline.stat.gateWaiting": "排队 LLM 调用",

    // 公共教材库归档
    "adm.trash.title": "公共教材库归档",
    "adm.trash.desc": "恢复或彻底删除已归档的公共教材。",
    "adm.trash.empty": "暂无公共库归档",
    "adm.trash.restore": "恢复",
    "adm.trash.purge": "彻底删除",
    "adm.trash.purgeTitle": "彻底删除公共库归档",
    "adm.trash.purgeDesc": "将永久删除该公共教材归档包的全部可恢复痕迹，无法撤销。",
    "adm.trash.purgeConfirm": "彻底删除",

    // 数据清理（孤儿数据扫描/清理）
    "adm.tab.cleanup": "数据清理",
    "adm.cleanup.title": "孤儿数据清理",
    "adm.cleanup.desc": "扫描并清理不属于任何在册账号的运行时数据：测试残留、已注销账号遗物、无引用追踪、失去会话的转写与空回收站目录。",
    "adm.cleanup.rescan": "重新扫描",
    "adm.cleanup.empty": "未发现孤儿数据，全部干净。",
    "adm.cleanup.loadFail": "扫描失败（需要管理员权限）",
    "adm.cleanup.col.category": "类别",
    "adm.cleanup.col.items": "数量",
    "adm.cleanup.col.bytes": "占用",
    "adm.cleanup.col.samples": "示例",
    "adm.cleanup.cat.students": "学习档案",
    "adm.cleanup.cat.sessions": "会话",
    "adm.cleanup.cat.transcripts": "转写",
    "adm.cleanup.cat.traces": "调用追踪",
    "adm.cleanup.cat.uploads": "会话上传",
    "adm.cleanup.cat.workspaces": "工作区",
    "adm.cleanup.cat.library": "资料库",
    "adm.cleanup.cat.trash": "回收站",
    "adm.cleanup.cat.notes": "笔记",
    "adm.cleanup.cat.knowledge": "知识图谱",
    "adm.cleanup.total": "共 {count} 项 / {size}",
    "adm.cleanup.purge": "清理孤儿数据",
    "adm.cleanup.purgeTitle": "清理孤儿数据",
    "adm.cleanup.purgeDesc": "将永久删除上述扫描到的全部孤儿数据。注册账号、游客与公共教材库数据受保护，不会被清理。此操作不可撤销。",
    "adm.cleanup.purgeConfirm": "清理",
    "adm.cleanup.notice.purged": "已清理 {count} 项，释放 {size}。",
    "adm.cleanup.notice.fail": "清理失败",
  },
  en: {
    "adm.title": "Admin Console",
    "adm.desc": "Accounts & data governance, lifecycle & memory policies, textbook OCR and public archives.",

    // Tabs
    "adm.tab.accounts": "Accounts & Data",
    "adm.tab.policy": "Lifecycle & Memory",
    "adm.tab.ocr": "OCR & Parsing",
    "adm.tab.trash": "Public Archives",

    // Accounts & data
    "adm.stat.accounts": "Accounts",
    "adm.stat.total": "Total usage",
    "adm.stat.sessions": "Sessions",
    "adm.stat.files": "Files",
    "adm.users.title": "Accounts",
    "adm.users.desc": "Click any row to expand its storage breakdown; clear chat data or delete accounts permanently.",
    "adm.users.email": "Email",
    "adm.users.username": "Username",
    "adm.users.role": "Role",
    "adm.users.created": "Registered",
    "adm.users.lastLogin": "Last login",
    "adm.users.storage": "Usage",
    "adm.users.storage.chat": "Chat & library",
    "adm.users.storage.uploads": "Chat uploads",
    "adm.users.storage.notes": "Notes",
    "adm.users.storage.students": "Learning records",
    "adm.users.storage.knowledge": "Knowledge graphs",
    "adm.users.storage.trashB": "Trash",
    "adm.users.storage.sessions": "Sessions",
    "adm.users.storage.files": "Files",
    "adm.users.actions": "Actions",
    "adm.users.search": "Search email / username",
    "adm.users.role.all": "All roles",
    "adm.users.role.student": "Student",
    "adm.users.role.parent": "Parent",
    "adm.users.role.teacher": "Teacher",
    "adm.users.role.admin": "Admin",
    "adm.users.summary": "{count} accounts · {size} total",
    "adm.users.noMatch": "No matching accounts",
    "adm.users.clearChat": "Clear chat",
    "adm.users.clearChat.title": "Clear chat data",
    "adm.users.clearChat.all": "Full cleanup (sessions included)",
    "adm.users.clearChat.all.desc": "Deletes all sessions, transcripts and traces, attachments, workspaces, library files and related trash items; the account, notes and learning records are kept.",
    "adm.users.clearChat.uploads_only": "Uploaded files only",
    "adm.users.clearChat.uploads_only.desc": "Deletes only uploaded originals and extracted text (chat attachments, library files, workspace uploads); chat transcripts are kept.",
    "adm.users.clearChat.estimate": "Estimated ~{size} to be freed",
    "adm.users.clearChat.confirm": "Clear now",
    "adm.users.notice.cleared": "Cleared; {size} freed",
    "adm.users.purge": "Delete permanently",
    "adm.users.purgeTitle": "Delete account permanently",
    "adm.users.purgeDesc": "Permanently deletes the account and everything under it (chat, uploads, notes, learning records, knowledge graphs, trash). Irreversible and signed out immediately. Type the account email to confirm:",
    "adm.users.purgeConfirm": "Delete permanently",
    "adm.users.notice.purged": "Account purged; {size} freed",
    "adm.users.notice.fail": "Operation failed, please retry",
    "adm.users.adminBadge": "Admin",
    "adm.users.empty": "No accounts",
    "adm.users.loadFail": "Failed to load (admin required)",
    "adm.users.cancel": "Cancel",
    "adm.users.never": "Never",
    "adm.users.self": " (me)",

    "adm.policy.title": "Lifecycle & Memory Policy",
    "adm.policy.desc": "Global defaults for trash retention and prompt memory windows. Takes effect on save.",
    "adm.policy.save": "Save policy",
    "adm.policy.saved": "Saved",
    "adm.policy.trash": "Trash",
    "adm.policy.trash.defaultDays": "Default retention (days)",
    "adm.policy.trash.defaultDays.hint": "default_days · 1–30, default retention for new users",
    "adm.policy.trash.userMaxDays": "User max (days)",
    "adm.policy.trash.userMaxDays.hint": "user_max_days · 1–30, max users may set",
    "adm.policy.trash.forcedMaxDays": "Forced max (days)",
    "adm.policy.trash.forcedMaxDays.hint": "forced_max_days · 1–365, absolute cap; always purged past it",
    "adm.policy.trash.mode": "Cleanup mode",
    "adm.policy.trash.mode.hint": "auto purges on expiry; manual purge only",
    "adm.policy.trash.mode.auto": "Auto cleanup on expiry",
    "adm.policy.trash.mode.manual": "Manual purge only",
    "adm.policy.memory": "Prompt memory window",
    "adm.policy.memory.defaultWindow": "Default window (turns)",
    "adm.policy.memory.defaultWindow.hint": "default_window · min 5, turns covered by default",
    "adm.policy.memory.maxWindow": "Max window (turns)",
    "adm.policy.memory.maxWindow.hint": "max_window · min 5, user-settable cap",
    "adm.policy.memory.coreLimit": "Core memory cap (chars)",
    "adm.policy.memory.coreLimit.hint": "core_char_limit, per-core-memory character cap",
    "adm.policy.memory.directiveLimit": "Directive cap (chars)",
    "adm.policy.memory.directiveLimit.hint": "directive_char_limit, long-term directive cap",

    "adm.ocr.title": "Textbook Background OCR",
    "adm.ocr.desc": "Only affects background textbook OCR. No restart needed.",
    "adm.ocr.detail": "Details",
    "adm.ocr.hint": "Only affects background textbook OCR; chat attachments, workspaces and the regular library keep the existing short-retry with local fallback. By default the multimodal API is retried persistently; failed pages retry every 10 s by default (settable to 0), and empty-content pages finish as blank pages once the attempt limit is reached. No restart needed.",
    "adm.ocr.concurrency": "Concurrent pages",
    "adm.ocr.concurrency.hint": "concurrency · 1–100, pages submitted in parallel",
    "adm.ocr.failureMode": "Failure handling",
    "adm.ocr.failureMode.hint": "After repeated failures: retry / local OCR / pause",
    "adm.ocr.failureMode.persistentApi": "Persistent API retry (default)",
    "adm.ocr.failureMode.boundedThenLocal": "Local OCR after limit",
    "adm.ocr.failureMode.boundedApiOnly": "Pause after limit",
    "adm.ocr.maxAttempts": "Max attempts",
    "adm.ocr.maxAttempts.hint": "max_attempts · 1–100, attempts per page",
    "adm.ocr.retryInterval": "Retry interval (s)",
    "adm.ocr.retryInterval.hint": "retry_interval_seconds · 0–3600, 0 retries immediately",
    "adm.ocr.requestTimeout": "Request timeout (s)",
    "adm.ocr.requestTimeout.hint": "request_timeout_seconds · 10–300, per-request timeout",
    "adm.ocr.apply": "Apply policy",
    "adm.ocr.applied": "Applied",
    "adm.ocr.status": "Live status",
    "adm.ocr.stat.concurrency": "Concurrency",
    "adm.ocr.stat.pending": "Pending",
    "adm.ocr.stat.jobs": "Active jobs",
    "adm.ocr.stat.pages": "Active pages",
    "adm.ocr.stat.waiting": "Retry waiting",
    "adm.ocr.stat.failureMode": "Retry policy",
    "adm.ocr.stat.nextRetry": "Next retry",
    "adm.ocr.stat.generation": "Generation",
    "adm.ocr.stat.version": "Version",

    "adm.pipeline.title": "Textbook Parse Parallelism",
    "adm.pipeline.desc": "Execution scheduling only (revertible to the original serial mode); the parsing method and its output stay identical. No restart needed.",
    "adm.pipeline.detail": "Details",
    "adm.pipeline.hint": "Parallel mode only overlaps independent calls in time: per-chapter concept extraction, volumes inside a textbook group, and queued textbooks may run in parallel (page-level OCR concurrency is still capped separately by the OCR policy above). Choosing the original serial mode forces every concurrency to 1, matching the historical execution order exactly. 429 storms are absorbed by the existing retry backoff; lower the LLM concurrency if the provider rate-limits.",
    "adm.pipeline.mode": "Parse mode",
    "adm.pipeline.mode.hint": "parallel = accelerated; legacy = original strict serial",
    "adm.pipeline.mode.parallel": "Parallel (default)",
    "adm.pipeline.mode.legacy": "Original serial",
    "adm.pipeline.build": "Simultaneous textbooks",
    "adm.pipeline.build.hint": "build_concurrency · 1–4, books built at once per owner/public library",
    "adm.pipeline.volume": "Parallel volumes per group",
    "adm.pipeline.volume.hint": "volume_concurrency · 1–4, volumes processed at once within a group",
    "adm.pipeline.llm": "Graph LLM concurrency",
    "adm.pipeline.llm.hint": "llm_concurrency · 1–8, global cap for chapter extraction calls",
    "adm.pipeline.apply": "Apply policy",
    "adm.pipeline.applied": "Applied",
    "adm.pipeline.status": "Live status",
    "adm.pipeline.stat.mode": "Mode",
    "adm.pipeline.stat.build": "Effective · books",
    "adm.pipeline.stat.volume": "Effective · volumes",
    "adm.pipeline.stat.llm": "Effective · LLM",
    "adm.pipeline.stat.gateActive": "In-flight LLM calls",
    "adm.pipeline.stat.gateWaiting": "Queued LLM calls",

    "adm.trash.title": "Public Library Archives",
    "adm.trash.desc": "Restore or permanently delete archived public textbooks.",
    "adm.trash.empty": "No public archives",
    "adm.trash.restore": "Restore",
    "adm.trash.purge": "Purge",
    "adm.trash.purgeTitle": "Permanently delete archive",
    "adm.trash.purgeDesc": "Every recoverable trace of this public textbook archive will be permanently removed. This cannot be undone.",
    "adm.trash.purgeConfirm": "Delete permanently",

    // Orphan data cleanup
    "adm.tab.cleanup": "Data Cleanup",
    "adm.cleanup.title": "Orphan Data Cleanup",
    "adm.cleanup.desc": "Scan and remove runtime data that belongs to no registered account: test leftovers, deregistered-account remnants, unreferenced traces, orphan transcripts and empty trash dirs.",
    "adm.cleanup.rescan": "Rescan",
    "adm.cleanup.empty": "No orphan data found. Everything is clean.",
    "adm.cleanup.loadFail": "Scan failed (admin required)",
    "adm.cleanup.col.category": "Category",
    "adm.cleanup.col.items": "Items",
    "adm.cleanup.col.bytes": "Size",
    "adm.cleanup.col.samples": "Samples",
    "adm.cleanup.cat.students": "Learning profiles",
    "adm.cleanup.cat.sessions": "Sessions",
    "adm.cleanup.cat.transcripts": "Transcripts",
    "adm.cleanup.cat.traces": "Traces",
    "adm.cleanup.cat.uploads": "Session uploads",
    "adm.cleanup.cat.workspaces": "Workspaces",
    "adm.cleanup.cat.library": "Library",
    "adm.cleanup.cat.trash": "Trash",
    "adm.cleanup.cat.notes": "Notes",
    "adm.cleanup.cat.knowledge": "Knowledge graphs",
    "adm.cleanup.total": "{count} items / {size} in total",
    "adm.cleanup.purge": "Clean orphan data",
    "adm.cleanup.purgeTitle": "Clean orphan data",
    "adm.cleanup.purgeDesc": "All orphan data found above will be permanently deleted. Registered accounts, the guest namespace and the public textbook library are protected and never touched. This cannot be undone.",
    "adm.cleanup.purgeConfirm": "Clean",
    "adm.cleanup.notice.purged": "Cleaned {count} items, freed {size}.",
    "adm.cleanup.notice.fail": "Cleanup failed",
  },
} satisfies PageStrings;
