// /orchestration 学习编排页（M9 学习编排智能）的页面级词条。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "page.title": "学习编排",
    "page.desc": "M9 学习编排智能 · 多长期目标 → 周计划 → 今日任务 + 间隔复习",
    "action.dismiss": "关闭",

    "goal.title": "长期目标",
    "goal.desc": "GoalAnalyzer 差距分析 · 读 M2 掌握度与 M5 图谱",
    "goal.type.exam": "考试目标",
    "goal.type.ability": "能力提升",
    "goal.type.interest": "兴趣探索",
    "goal.deadline": "截止",
    "goal.deadline.left": "天后截止",
    "goal.deadline.overdue": "已超期",
    "goal.deadline.none": "未设截止",
    "goal.progress": "总体掌握进度",
    "goal.skills": "个技能点",
    "goal.level": "水平",
    "goal.level.to": "→",
    "goal.level.novice": "入门",
    "goal.level.beginner": "初学",
    "goal.level.intermediate": "中级",
    "goal.level.advanced": "进阶",
    "goal.level.proficient": "熟练",
    "goal.urgency": "截止压力",
    "goal.strategy": "推荐策略",
    "goal.strategy.foundation_first": "先打基础：优先补齐前置概念，再推进高阶内容。",
    "goal.strategy.intensive_review": "集中复习：以巩固薄弱点为主，少量推进新内容。",
    "goal.strategy.mixed_progress": "混合推进：新内容与复习交替，稳步提升。",
    "goal.strategy.advanced_refinement": "拔高精炼：基础已牢，聚焦高阶与综合应用。",
    "goal.gaps": "差距清单",
    "goal.gaps.empty": "没有明显差距，保持当前节奏。",
    "goal.gap.missing": "缺失",
    "goal.gap.weak": "薄弱",
    "goal.gap.unknown": "未测",
    "goal.estimate.range": "按你的可用时间约 %a–%b 周",
    "goal.chain": "目标链",
    "goal.chain.desc": "差距与进度按目标概念的前置依赖链计算",
    "goal.progress.chain": "目标链口径",
    "goal.estimate": "按每周 %p 个概念，约需 %e 周",
    "goal.estimate.left": "距截止还有 %w 周",
    "goal.fit.tight": "时间紧张",
    "goal.fit.ok": "节奏适中",
    "goal.fit.loose": "时间充裕",
    "goal.gap.learn": "去学",
    "goal.gap.locate": "在谱系中查看",
    "goal.layer.first": "第 1 层 · 现在就能学",
    "goal.layer.n": "第 %n 层",
    "goal.layer.pre": "需先补上层",
    "goal.layer.unknown": "未分层（无前置数据）",
    "goal.gaps.chain": "达成目标所需的前置链",
    "goal.gaps.subject": "该学科未掌握概念",
    "form.goal.desc": "目标描述（可选）",
    "form.goal.desc.ph": "例如：期末物理上册考到 85 分，重点补力学",
    "goal.edit": "编辑目标",
    "goal.edit.title": "编辑长期目标",
    "form.update": "保存并重新规划",

    "kickoff.title": "目标已设定，学习计划已生成",
    "kickoff.desc": "已为你生成 %n 周计划，第一步已经就绪。",
    "kickoff.title.empty": "目标已设定，但无法自动规划",
    "kickoff.desc.empty": "该学科不在考纲图谱内，无法自动生成周计划。你可以手动添加周和任务，或改用考纲内学科。",
    "kickoff.cta": "开始第一个任务",
    "kickoff.dismiss": "稍后",

    "replan.banner": "你的学习进度与计划出现偏差。",
    "replan.action": "让教练帮我调整",
    "replan.msg": "我的学习进度落后于原计划，请帮我分析原因，并重新安排后续的学习计划。",

    "goal.add": "添加目标",
    "goal.add.title": "添加长期目标",
    "goal.del": "删除目标",
    "goal.del.confirm.title": "删除目标",
    "goal.del.confirm.desc": "将删除目标「%t」并重新规划，已生成的每日任务会保留。确定删除？",

    "form.title": "设定你的长期学习目标",
    "form.desc": "编排智能会据此倒推周计划与每日任务",
    "form.name": "目标名称",
    "form.name.ph": "例如：期末数学上 90 分",
    "form.type": "目标类型",
    "form.deadline": "截止日期（可选）",
    "form.submit": "设定目标并生成计划",
    "form.submitting": "生成中…",
    "form.failed": "目标设定失败，请重试",

    "catalog.level": "学段",
    "catalog.levelPh": "请选择学段",
    "catalog.subject": "学科（可选）",
    "catalog.subjectPh": "数学, 物理",
    "catalog.anySubject": "（不限）",
    "catalog.loading": "目录加载中…",

    "today.title": "今日任务",
    "today.desc": "由周计划与 SRS 到期队列生成",
    "today.pending": "待完成",
    "today.done.all": "今日任务全部完成，太棒了！",
    "today.empty": "今日暂无任务",
    "today.go": "去学习",
    "today.go.q": "讲一下",
    "today.kind.study": "新学",
    "today.kind.review": "复习",
    "today.kind.practice": "练习",
    "today.kind.summary": "总结",
    "today.tab.plan": "学习计划",
    "today.tab.review": "间隔复习",
    "today.review.empty": "今天没有到期的复习——SM-2 会在最佳遗忘点把旧知识带回来。",
    "today.min": "分钟",
    "today.add": "添加任务",
    "today.edit": "编辑",
    "today.delete": "删除",
    "today.reset": "重置为待办",
    "today.custom": "自建",
    "today.carryover": "昨日结转",
    "today.selfreport": "手动完成",
    "today.launching": "启动中…",
    "today.delete.confirm.title": "删除任务",
    "today.delete.confirm.desc": "将删除任务「%t」，不可恢复。确定删除？",
    "today.phase.foundation": "基础",
    "today.phase.reinforce": "强化",
    "today.phase.sprint": "冲刺",

    "taskform.title.add": "添加任务",
    "taskform.title.edit": "编辑任务",
    "taskform.day": "日期",
    "taskform.name": "标题",
    "taskform.name.ph": "例如：复习浮力错题",
    "taskform.concept": "关联概念（可选）",
    "taskform.concept.ph": "例如：浮力",
    "taskform.kind": "类型",
    "taskform.phase": "阶段",
    "taskform.phase.none": "无",
    "taskform.estimate": "预估分钟",
    "taskform.priority": "优先级",
    "taskform.submit": "保存",
    "taskform.failed": "保存失败，请重试",

    "task.go.study": "去学",
    "task.go.review": "去复习",
    "task.go.practice": "去练",
    "task.go.summary": "去总结",
    "task.msg.study": "讲一下「%c」，请系统地讲一讲",
    "task.msg.review": "请出几道关于「%c」的复习题",
    "task.msg.practice": "请出几道关于「%c」的练习题，让我练一练",
    "task.msg.summary": "帮我总结今天学习的内容并指出薄弱点",

    "week.title": "周计划",
    "week.desc": "复用 M3 学习路径推理生成的每周安排",
    "week.n": "第 %n 周",
    "week.review": "本周复盘",
    "week.review.msg": "帮我做本周学习复盘：本周重点是「%f」，计划任务已完成 %d/%t 个，请总结我的掌握情况并指出薄弱点。",
    "week.empty": "暂无周计划——设定目标后自动生成，或点「添加一周」手动创建。",
    "week.add": "添加一周",
    "week.task.custom": "自建",
    "week.task.add": "添加任务",
    "week.task.add.ph": "例如：学完浮力前两节并做基础练习",
    "week.task.empty": "本周还没有任务——",
    "week.sub.min": "分钟",
    "week.sub.empty": "还没有子任务——点「推荐子任务」让教练拆解，或手动添加。",
    "week.sub.add": "添加",
    "week.sub.add.ph": "例如：做 10 道浮力计算题并订正",
    "week.sub.suggest": "推荐子任务",
    "week.sub.suggest.failed": "推荐暂时不可用，请稍后重试",
    "week.delete.confirm.title": "删除周计划",
    "week.delete.confirm.desc": "将删除第 %n 周的安排，已生成的每日任务会保留。确定删除？",
    "week.concept.add": "添加概念",
    "week.concept.remove": "移除",
    "weekform.title": "添加一周",
    "weekform.focus": "本周重点（可选）",
    "weekform.focus.ph": "例如：浮力与压强",
    "weekform.concepts": "包含概念（可选）",
    "weekform.submit": "添加",
    "weekform.failed": "保存失败，请重试",
    "concept.pick": "从计划概念中选择",
    "concept.custom.ph": "或输入新概念名，回车确认",

    "review.title": "间隔复习",
    "review.desc": "SM-2 算法调度的到期卡片，最逾期优先",
    "review.empty": "今天没有到期的复习卡片。",
    "review.go": "去复习",
    "review.go.q": "复习一下",
    "review.msg": "请出几道关于「%c」的复习题",
    "review.interval": "间隔 %n 天",
    "review.reps": "连续通过 %n 次",
    "review.overdue": "逾期 %n 天",
    "review.due.today": "今日到期",

    "habit.title": "学习习惯",
    "habit.desc": "TaskCompletionTracker 任务执行统计",
    "habit.streak": "连续学习",
    "habit.streak.longest": "最长连击",
    "habit.days": "天",
    "habit.rate": "任务完成率",
    "habit.active": "累计活跃天数",
    "habit.procrastination": "拖延次数",

    "empty.title": "还没有长期目标",
    "empty.desc": "设定一个长期目标，M9 编排智能会为你倒推周计划与每日任务，并用 SM-2 间隔复习对抗遗忘。",
    "err.load": "学习编排数据加载失败，请确认后端服务已启动。",
  },
  en: {
    "page.title": "Orchestration",
    "page.desc": "M9 learning orchestration · goals → weekly plan → daily tasks + spaced review",
    "action.dismiss": "Dismiss",

    "goal.title": "Long-term Goal",
    "goal.desc": "GoalAnalyzer gap analysis · reads M2 mastery & M5 graph",
    "goal.type.exam": "Exam",
    "goal.type.ability": "Ability",
    "goal.type.interest": "Interest",
    "goal.deadline": "Deadline",
    "goal.deadline.left": "days left",
    "goal.deadline.overdue": "Overdue",
    "goal.deadline.none": "No deadline",
    "goal.progress": "Overall mastery progress",
    "goal.skills": "skills",
    "goal.level": "Level",
    "goal.level.to": "→",
    "goal.level.novice": "Novice",
    "goal.level.beginner": "Beginner",
    "goal.level.intermediate": "Intermediate",
    "goal.level.advanced": "Advanced",
    "goal.level.proficient": "Proficient",
    "goal.urgency": "Urgency",
    "goal.strategy": "Recommended strategy",
    "goal.strategy.foundation_first": "Foundation first: fill prerequisite gaps before advanced content.",
    "goal.strategy.intensive_review": "Intensive review: consolidate weak points, advance slowly.",
    "goal.strategy.mixed_progress": "Mixed progress: alternate new content with review.",
    "goal.strategy.advanced_refinement": "Advanced refinement: foundations are solid — focus on synthesis.",
    "goal.gaps": "Gap list",
    "goal.gaps.empty": "No significant gaps — keep the current pace.",
    "goal.gap.missing": "Missing",
    "goal.gap.weak": "Weak",
    "goal.gap.unknown": "Untested",
    "goal.estimate.range": "≈ %a–%b weeks at your available time",
    "goal.chain": "Goal chain",
    "goal.chain.desc": "Gaps and progress follow the target concepts' prerequisite chain",
    "goal.progress.chain": "chain-based",
    "goal.estimate": "≈ %e weeks at %p concepts/week",
    "goal.estimate.left": "%w weeks until deadline",
    "goal.fit.tight": "Tight",
    "goal.fit.ok": "On pace",
    "goal.fit.loose": "Comfortable",
    "goal.gap.learn": "Learn",
    "goal.gap.locate": "Locate in genealogy",
    "goal.layer.first": "Layer 1 · learnable now",
    "goal.layer.n": "Layer %n",
    "goal.layer.pre": "needs earlier layers",
    "goal.layer.unknown": "Unlayered (no prereq data)",
    "goal.gaps.chain": "prerequisite chain to the goal",
    "goal.gaps.subject": "unmastered concepts in this subject",
    "goal.edit": "Edit goal",
    "goal.edit.title": "Edit long-term goal",
    "form.update": "Save & replan",

    "kickoff.title": "Goal set — your plan is ready",
    "kickoff.desc": "Generated a %n-week plan; your first step is ready.",
    "kickoff.title.empty": "Goal set — auto-planning unavailable",
    "kickoff.desc.empty": "This subject isn't in the syllabus graph, so a weekly plan can't be generated automatically. Add weeks and tasks manually, or pick a syllabus subject.",
    "kickoff.cta": "Start the first task",
    "kickoff.dismiss": "Later",

    "replan.banner": "Your progress has drifted from the plan.",
    "replan.action": "Ask the coach to adjust",
    "replan.msg": "My progress has fallen behind the plan. Please analyze why and rearrange my upcoming schedule.",

    "goal.add": "Add goal",
    "goal.add.title": "Add long-term goal",
    "goal.del": "Delete goal",
    "goal.del.confirm.title": "Delete goal",
    "goal.del.confirm.desc": "Goal \"%t\" will be deleted and the plan regenerated. Already-generated daily tasks are kept. Continue?",

    "form.title": "Set your long-term learning goal",
    "form.desc": "Orchestration back-plans weekly plans and daily tasks from it",
    "form.name": "Goal title",
    "form.name.ph": "e.g. Score 90+ on the math final",
    "form.goal.desc": "Description (optional)",
    "form.goal.desc.ph": "e.g. Score 85+ on the physics final, focus on mechanics",
    "form.type": "Goal type",
    "form.deadline": "Deadline (optional)",
    "form.submit": "Set goal & generate plan",
    "form.submitting": "Generating…",
    "form.failed": "Failed to set the goal — please retry",

    "catalog.level": "Grade level",
    "catalog.levelPh": "Select a level",
    "catalog.subject": "Subject (optional)",
    "catalog.subjectPh": "Math, Physics",
    "catalog.anySubject": "(Any)",
    "catalog.loading": "Loading catalog…",

    "today.title": "Today's Tasks",
    "today.desc": "Generated from the weekly plan and the SRS due queue",
    "today.pending": "pending",
    "today.done.all": "All of today's tasks are done — great job!",
    "today.empty": "No tasks for today",
    "today.go": "Study",
    "today.go.q": "Explain ",
    "today.kind.study": "Study",
    "today.kind.review": "Review",
    "today.kind.practice": "Practice",
    "today.kind.summary": "Summary",
    "today.tab.plan": "Study plan",
    "today.tab.review": "Spaced review",
    "today.review.empty": "Nothing due for review today — SM-2 brings old knowledge back right at the forgetting point.",
    "today.min": "min",
    "today.add": "Add task",
    "today.edit": "Edit",
    "today.delete": "Delete",
    "today.reset": "Reset to pending",
    "today.custom": "Custom",
    "today.carryover": "Carried over",
    "today.selfreport": "Marked done",
    "today.launching": "Launching…",
    "today.delete.confirm.title": "Delete task",
    "today.delete.confirm.desc": "Task \"%t\" will be permanently deleted. Continue?",
    "today.phase.foundation": "Foundation",
    "today.phase.reinforce": "Reinforce",
    "today.phase.sprint": "Sprint",

    "taskform.title.add": "Add task",
    "taskform.title.edit": "Edit task",
    "taskform.day": "Day",
    "taskform.name": "Title",
    "taskform.name.ph": "e.g. Rework buoyancy mistakes",
    "taskform.concept": "Linked concept (optional)",
    "taskform.concept.ph": "e.g. Buoyancy",
    "taskform.kind": "Kind",
    "taskform.phase": "Phase",
    "taskform.phase.none": "None",
    "taskform.estimate": "Estimate (min)",
    "taskform.priority": "Priority",
    "taskform.submit": "Save",
    "taskform.failed": "Save failed — please retry",

    "task.go.study": "Study",
    "task.go.review": "Review",
    "task.go.practice": "Practice",
    "task.go.summary": "Summarize",
    "task.msg.study": "Explain \"%c\" systematically",
    "task.msg.review": "Give me a few review questions on \"%c\"",
    "task.msg.practice": "Give me a few practice problems on \"%c\" so I can drill",
    "task.msg.summary": "Summarize what I learned today and point out my weak spots",

    "week.title": "Weekly Plan",
    "week.desc": "Weekly schedule derived with the M3 path reasoning engine",
    "week.n": "Week %n",
    "week.review": "Weekly review",
    "week.review.msg": "Help me review this week: the focus was \"%f\" and I completed %d/%t planned tasks — summarize my mastery and point out weak spots.",
    "week.empty": "No weekly plan yet — set a goal to generate one, or add a week manually.",
    "week.add": "Add week",
    "week.task.custom": "Custom",
    "week.task.add": "Add task",
    "week.task.add.ph": "e.g. Finish the first two sections on buoyancy with drills",
    "week.task.empty": "No tasks this week —",
    "week.sub.min": "min",
    "week.sub.empty": "No subtasks yet — hit Suggest for a coach breakdown, or add one manually.",
    "week.sub.add": "Add",
    "week.sub.add.ph": "e.g. Do 10 buoyancy problems and correct them",
    "week.sub.suggest": "Suggest subtasks",
    "week.sub.suggest.failed": "Suggestions unavailable — please retry later",
    "week.delete.confirm.title": "Delete week",
    "week.delete.confirm.desc": "Week %n will be deleted. Already-generated daily tasks are kept. Continue?",
    "week.concept.add": "Add concept",
    "week.concept.remove": "Remove",
    "weekform.title": "Add week",
    "weekform.focus": "Week focus (optional)",
    "weekform.focus.ph": "e.g. Buoyancy and pressure",
    "weekform.concepts": "Concepts (optional)",
    "weekform.submit": "Add",
    "weekform.failed": "Save failed — please retry",
    "concept.pick": "Pick from planned concepts",
    "concept.custom.ph": "…or type a new concept name and press Enter",

    "review.title": "Spaced Review",
    "review.desc": "SM-2 scheduled due cards, most overdue first",
    "review.empty": "No review cards due today.",
    "review.go": "Review",
    "review.go.q": "Review ",
    "review.msg": "Give me a few review questions on \"%c\"",
    "review.interval": "%n-day interval",
    "review.reps": "%n consecutive passes",
    "review.overdue": "%n days overdue",
    "review.due.today": "Due today",

    "habit.title": "Study Habits",
    "habit.desc": "TaskCompletionTracker execution stats",
    "habit.streak": "Current streak",
    "habit.streak.longest": "Longest streak",
    "habit.days": "days",
    "habit.rate": "Completion rate",
    "habit.active": "Active days",
    "habit.procrastination": "Procrastinations",

    "empty.title": "No long-term goal yet",
    "empty.desc": "Set a long-term goal and M9 will back-plan weekly plans and daily tasks, with SM-2 spaced review against forgetting.",
    "err.load": "Failed to load orchestration data — is the backend running?",
  },
} satisfies PageStrings;
