// /knowledge 页面词条（zh/en）。领域标签（edge.*/state.*/mode.*）走 lib/labels.ts 的 dt()。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    title: "知识图谱",
    desc: "M5 知识本体 × M2 掌握度叠加 × M3 学习路径",
    all: "全部",
    // 分层筛选栏
    filterSubject: "学科",
    filterTextbook: "教材",
    filterVolume: "卷",
    filterAny: "全部",
    clearFilters: "清除筛选",
    // 搜索
    searchPh: "搜索概念名称 / ID / 别名…",
    searchResultCount: "共 %n 个结果",
    searchTruncated: "仅显示前 %n 项，试试更精确的关键词",
    searchEmpty: "当前学段未找到「%q」",
    searchScopeHint: "仅搜索当前学段的概念",
    searchPrev: "上一个命中",
    searchNext: "下一个命中",
    searchClear: "清空搜索",
    prereqOnly: "只看前置链",
    resetView: "复位视图",
    statConcepts: "概念",
    statEdges: "边",
    statLearned: "学得",
    statChapters: "章节",
    statSections: "节",
    unitDirectConcepts: "本单元概念",
    emptySectionConcepts: "该课文/单元暂无关联概念",
    "level.小学": "小学",
    "level.初中": "初中",
    "level.高中": "高中",
    "level.本科": "本科",
    "level.其他": "其他",
    emptyTitle: "暂无知识图谱数据",
    emptyDesc: "知识本体尚未构建，或当前没有任何概念节点。先去对话中学习几个概念吧。",
    disabledTitle: "知识智能层未启用",
    disabledDesc: "该智能层（M5 知识图谱）被环境开关关闭。在后端开启对应开关后重启即可恢复。",
    loadFail: "知识图谱加载失败",
    pathTitle: "推荐学习路径",
    pathEmpty: "暂无可推荐的学习内容",
    pathDisabled: "教学引擎未启用，暂无路径推荐",
    pathFail: "学习路径加载失败",
    askPrefix: "讲一下",
    askMsg: "讲一下「%c」",
    askMsgReason: "讲一下「%c」（我的个性化推荐：%r）",
    "drawer.learn": "在对话中学这个",
    "drawer.goal": "属于目标《%t》",
    "drawer.goal.target": "目标概念",
    "drawer.goal.remaining": "距目标还差 %n 个概念",
    "drawer.goal.layer": "当前第 %n 层",
    "drawer.quiz": "出几道题考我",
    "drawer.learn.msg": "我想学习「%c」（%m），请系统地讲一讲",
    "drawer.mastery.part": "，我目前的掌握情况：%s",
    "drawer.quiz.msg": "请出几道关于「%c」的题目考我，并在我作答后批改讲解",
    difficulty: "难度",
    aliases: "别名",
    commonErrors: "常见错误",
    contentTitle: "讲解内容",
    "drawer.parents": "所属",
    "drawer.children": "包含",
    "drawer.pages": "教材页码",
    "drawer.struct": "结构数据",
    masteryTitle: "掌握度",
    attemptsTxt: "次尝试",
    correctTxt: "次答对",
    unlocks: "解锁后续",
    teachingLog: "最近教学记录",
    memories: "相关记忆",
    notFound: "未找到该概念",

    // M5.7 教材图谱（P6-A4 起图谱只来自教材）
    "custom.title": "教材图谱",
    "custom.view": "查看",
    "custom.delete": "删除",
    "custom.source.llm": "LLM 生成",
    "custom.source.material": "教材",
    "custom.textbook.badge": "教材",
    "build.open.textbook": "上传教材构建",
    "custom.actionFail": "操作失败，请稍后重试",
    "custom.delete.confirm.title": "删除图谱",
    "custom.delete.confirm.desc": "「%t」将进入归档中心；可在到期前恢复，彻底删除需在归档中心二次确认。",
  },
  en: {
    title: "Knowledge Graph",
    desc: "M5 ontology × M2 mastery overlay × M3 learning path",
    all: "All",
    // Filter bar
    filterSubject: "Subject",
    filterTextbook: "Textbook",
    filterVolume: "Volume",
    filterAny: "All",
    clearFilters: "Clear filters",
    // Search
    searchPh: "Search name / ID / alias…",
    searchResultCount: "%n results",
    searchTruncated: "showing first %n — refine your query",
    searchEmpty: "No match for \"%q\" in this level",
    searchScopeHint: "Searching concepts in the current level only",
    searchPrev: "Previous match",
    searchNext: "Next match",
    searchClear: "Clear search",
    prereqOnly: "Prereq chain only",
    resetView: "Reset view",
    statConcepts: "concepts",
    statEdges: "edges",
    statLearned: "learned",
    statChapters: "chapters",
    statSections: "sections",
    unitDirectConcepts: "Unit concepts",
    emptySectionConcepts: "No concepts linked to this lesson/unit yet",
    "level.小学": "Primary",
    "level.初中": "Middle school",
    "level.高中": "High school",
    "level.本科": "Undergrad",
    "level.其他": "Other",
    emptyTitle: "No knowledge graph yet",
    emptyDesc: "The ontology has not been built, or there are no concept nodes yet. Learn a few concepts in chat first.",
    disabledTitle: "Knowledge layer disabled",
    disabledDesc: "The M5 knowledge layer is turned off by an environment switch. Enable it on the backend and restart.",
    loadFail: "Failed to load the knowledge graph",
    pathTitle: "Recommended path",
    pathEmpty: "Nothing to recommend yet",
    pathDisabled: "Teaching engine disabled; no path available",
    pathFail: "Failed to load the learning path",
    askPrefix: "Explain ",
    askMsg: "Explain \"%c\"",
    askMsgReason: "Explain \"%c\" (recommended for me: %r)",
    "drawer.learn": "Learn this in chat",
    "drawer.goal": "Part of goal \u300c%t\u300d",
    "drawer.goal.target": "Target concept",
    "drawer.goal.remaining": "%n concepts from the goal",
    "drawer.goal.layer": "Layer %n",
    "drawer.quiz": "Quiz me on this",
    "drawer.learn.msg": "I want to learn \"%c\" (%m) — please explain it systematically",
    "drawer.mastery.part": ", my current mastery: %s",
    "drawer.quiz.msg": "Give me a few questions on \"%c\" to test me, then grade and explain my answers",
    difficulty: "Difficulty",
    aliases: "Aliases",
    commonErrors: "Common errors",
    contentTitle: "Teaching content",
    "drawer.parents": "Belongs to",
    "drawer.children": "Contains",
    "drawer.pages": "Textbook pages",
    "drawer.struct": "Structure data",
    masteryTitle: "Mastery",
    attemptsTxt: "attempts",
    correctTxt: "correct",
    unlocks: "Unlocks",
    teachingLog: "Recent teaching",
    memories: "Related memories",
    notFound: "Concept not found",

    // M5.7 textbook graphs (since P6-A4 graphs come from textbooks only)
    "custom.title": "Textbook graphs",
    "custom.view": "View",
    "custom.delete": "Delete",
    "custom.source.llm": "LLM generated",
    "custom.source.material": "Textbook",
    "custom.textbook.badge": "Textbook",
    "build.open.textbook": "Upload textbook",
    "custom.actionFail": "Operation failed — please try again later",
    "custom.delete.confirm.title": "Delete graph",
    "custom.delete.confirm.desc": "\"%t\" will be moved to the recycle bin. It can be restored before expiry; permanent deletion needs a second confirmation there.",
  },
} satisfies PageStrings;
