import type { PageStrings } from "@/lib/i18n-page";

/** 测评中心（/assessment）页面词条。 */
export const STRINGS = {
  zh: {
    "page.desc": "自适应诊断：根据你的作答动态调整题目难度，帮助了解你在本概念上的当前表现；结论仅反映本轮作答，不等同于长期掌握。",

    "config.title": "发起自适应测评",
    "config.desc": "输入一个概念，系统将生成一组难度自适应的题目。",
    "config.concept": "测评概念",
    "config.conceptPh": "例如：浮力",
    "config.subject": "学科（可选）",
    "config.subjectPh": "例如：物理",
    "config.grade": "学段",
    "config.start": "开始测评",
    "config.bloom": "认知层级焦点（布鲁姆分类学）",
    "config.starting": "正在出题…",
    "config.needConcept": "请先输入要测评的概念",

    "catalog.level": "学段",
    "catalog.levelPh": "请选择学段",
    "catalog.subject": "学科（可选）",
    "catalog.subjectPh": "例如：物理",
    "catalog.anySubject": "（不限）",
    "catalog.loading": "目录加载中…",

    "disabled.title": "自适应测评未启用",
    "disabled.desc": "M4 智能层已被环境开关关闭。可继续使用下方的练习会话，或联系管理员开启后重试。",

    "ask.answered": "已答",
    "ask.difficulty": "难度",
    "ask.submit": "提交答案",
    "ask.submitting": "判分中…",
    "ask.answerPh": "在此输入你的答案…",
    "ask.pickOne": "请选择一个选项",
    "ask.needAnswer": "请先填写答案",

    "fb.title": "判分结果",
    "fb.score": "得分",
    "fb.next": "下一题",
    "fb.loading": "正在生成下一题…",
    "fb.finish": "查看总结",

    "abandon": "放弃测评",
    "abandoning": "正在放弃…",

    "sum.title": "测评总结",
    "sum.concept": "概念",
    "sum.asked": "已答题数",
    "sum.answered": "已答题数",
    "sum.correct": "答对",
    "sum.wrong": "答错",
    "sum.partial": "部分正确",
    "sum.accuracy": "正确率",
    "sum.final_difficulty": "最终难度",
    "sum.verdict": "本轮表现",
    "sum.recommendation": "学习建议",
    "sum.status": "状态",
    "sum.stop_reason": "结束原因",
    "sum.stop_reason.mastered": "连续答对且难度较高：本轮诊断表现稳定（非长期掌握结论）",
    "sum.stop_reason.confirmed_gap": "连续答错且已达最低难度：建议针对性复习该概念",
    "sum.stop_reason.max_reached": "已达到本轮题数上限，可稍后再检验一次",
    "sum.stop_reason.oscillating": "作答表现交替起伏：该概念还不够稳定，建议换个角度再检验",
    "sum.stop_reason.no_session": "没有进行中的诊断",
    "sum.status.active": "进行中",
    "sum.status.mastered": "本轮结束（表现稳定）",
    "sum.status.stuck": "需要巩固",
    "sum.status.stopped": "已结束",
    "sum.status.abandoned": "已放弃",
    "sum.again": "再来一次",
    "sum.bloom": "认知层级分布",
    "sum.bloom.q": "题",
    "sum.addToPlan": "把薄弱概念加入周计划",
    "sum.adding": "加入中…",
    "sum.added": "已加入本周计划",
    "sum.empty": "暂无总结数据",

    "verdict.unknown": "未判定",

    "recent.title": "近期练习会话",
    "recent.desc": "包含测验记录的对话，点击回到会话继续练习。",
    "recent.quizUnit": "题",
    "recent.empty": "暂无练习会话",
    "recent.loadFail": "会话加载失败",

    "rq.title": "最近习题",
    "rq.desc": "跨会话汇集最近生成的题目（最多保留 100 道），点击回到出题会话。",
    "rq.empty": "暂无习题记录",
    "rq.loadFail": "习题加载失败",
    "rq.unanswered": "未作答",
    "rq.type.multiple_choice": "选择",
    "rq.type.fill_blank": "填空",
    "rq.type.short_answer": "简答",
    "rq.diff.easy": "基础",
    "rq.diff.medium": "中等",
    "rq.diff.hard": "挑战",

    "eb.title": "错题本",
    "eb.desc": "跨会话汇集你答错或半对的题目，点「重练」让教练仿照出一道变式。",
    "eb.empty": "暂无错题",
    "eb.empty.desc": "答题卡作答后，答错或半对的题会自动收进来。",
    "eb.loadFail": "错题本加载失败",
    "eb.rework": "重练",
    "eb.rework.msg": "我之前这道题做错了：「%s」。请仿照它出一道变式题让我重练，做完帮我批改讲解。",
    "eb.your.answer": "我的作答",
    "eb.correct.answer": "参考答案",
    "eb.goto.session": "回到出题会话",

    "err.start": "发起测评失败",
    "err.answer": "提交答案失败",
    "err.next": "获取下一题失败",
    "err.abandon": "放弃测评失败",
    "err.noActive": "没有进行中的测评，请重新开始",
  },
  en: {
    "page.desc": "Adaptive diagnosis: difficulty adapts to your answers to probe your current performance on a concept; the result reflects only this round, not long-term mastery.",

    "config.title": "Start an adaptive assessment",
    "config.desc": "Enter a concept and the system generates a set of difficulty-adaptive questions.",
    "config.concept": "Concept",
    "config.conceptPh": "e.g. Buoyancy",
    "config.subject": "Subject (optional)",
    "config.subjectPh": "e.g. Physics",
    "config.grade": "Grade",
    "config.start": "Start assessment",
    "config.bloom": "Cognitive-level focus (Bloom)",
    "config.starting": "Generating…",
    "config.needConcept": "Please enter a concept first",

    "catalog.level": "Grade level",
    "catalog.levelPh": "Select a level",
    "catalog.subject": "Subject (optional)",
    "catalog.subjectPh": "e.g. Physics",
    "catalog.anySubject": "(Any)",
    "catalog.loading": "Loading catalog…",

    "disabled.title": "Adaptive assessment unavailable",
    "disabled.desc": "The M4 intelligence layer is turned off by an environment flag. You can still use the practice sessions below, or ask an admin to enable it.",

    "ask.answered": "Answered",
    "ask.difficulty": "Difficulty",
    "ask.submit": "Submit answer",
    "ask.submitting": "Grading…",
    "ask.answerPh": "Type your answer here…",
    "ask.pickOne": "Pick an option",
    "ask.needAnswer": "Please enter an answer",

    "fb.title": "Grading result",
    "fb.score": "Score",
    "fb.next": "Next question",
    "fb.loading": "Generating next question…",
    "fb.finish": "View summary",

    "abandon": "Abandon",
    "abandoning": "Abandoning…",

    "sum.title": "Assessment summary",
    "sum.concept": "Concept",
    "sum.asked": "Questions asked",
    "sum.answered": "Questions asked",
    "sum.correct": "Correct",
    "sum.wrong": "Wrong",
    "sum.partial": "Partial",
    "sum.accuracy": "Accuracy",
    "sum.final_difficulty": "Final difficulty",
    "sum.verdict": "This round",
    "sum.recommendation": "Recommendation",
    "sum.status": "Status",
    "sum.stop_reason": "Stop reason",
    "sum.stop_reason.mastered": "Consecutive correct answers at higher difficulty — stable performance this round (not a long-term mastery claim)",
    "sum.stop_reason.confirmed_gap": "Consecutive wrong answers at the lowest difficulty — targeted review recommended",
    "sum.stop_reason.max_reached": "Question cap for this round reached; check again later",
    "sum.stop_reason.oscillating": "Results kept alternating — the concept is not yet stable; probe it from another angle",
    "sum.stop_reason.no_session": "No active diagnosis",
    "sum.status.active": "In progress",
    "sum.status.mastered": "Finished (stable this round)",
    "sum.status.stuck": "Needs consolidation",
    "sum.status.stopped": "Finished",
    "sum.status.abandoned": "Abandoned",
    "sum.again": "Start over",
    "sum.bloom": "Cognitive-level distribution",
    "sum.bloom.q": "Q",
    "sum.addToPlan": "Add weak concept to this week's plan",
    "sum.adding": "Adding…",
    "sum.added": "Added to this week's plan",
    "sum.empty": "No summary data",

    "verdict.unknown": "Ungraded",

    "recent.title": "Recent practice sessions",
    "recent.desc": "Conversations containing quizzes. Click to resume.",
    "recent.quizUnit": "quiz",
    "recent.empty": "No practice sessions yet",
    "recent.loadFail": "Failed to load sessions",

    "rq.title": "Recent questions",
    "rq.desc": "Questions generated across sessions (up to 100 kept). Click to revisit the session.",
    "rq.empty": "No questions yet",
    "rq.loadFail": "Failed to load questions",
    "rq.unanswered": "Unanswered",
    "rq.type.multiple_choice": "MC",
    "rq.type.fill_blank": "Fill-in",
    "rq.type.short_answer": "Short answer",
    "rq.diff.easy": "Basic",
    "rq.diff.medium": "Medium",
    "rq.diff.hard": "Hard",

    "eb.title": "Mistake notebook",
    "eb.desc": "Questions you got wrong or partially right, gathered across sessions. Hit Rework for a variant drill.",
    "eb.empty": "No mistakes yet",
    "eb.empty.desc": "Wrong or partially correct answers on quiz cards are collected here automatically.",
    "eb.loadFail": "Failed to load the mistake notebook",
    "eb.rework": "Rework",
    "eb.rework.msg": "I got this question wrong: \"%s\". Please create a variant for me to retry, then grade and explain it.",
    "eb.your.answer": "My answer",
    "eb.correct.answer": "Correct answer",
    "eb.goto.session": "Open the original session",

    "err.start": "Failed to start assessment",
    "err.answer": "Failed to submit answer",
    "err.next": "Failed to load next question",
    "err.abandon": "Failed to abandon",
    "err.noActive": "No active assessment — please start again",
  },
} satisfies PageStrings;
