import type { PageStrings } from "@/lib/i18n-page";

/** 测评中心（/assessment）页面词条。 */
export const STRINGS = {
  zh: {
    "illustration.review": "回看题目",
    "illustration.title": "题目插图",
    "illustration.optionsTitle": "出题插图选项",
    "illustration.expand": "放大查看",
    "illustration.close": "关闭",
    "illustration.unavailable": "插图无法显示，请刷新后重试；下方为图意描述。",
    "illustration.setting": "允许生成题目插图",
    "illustration.desc": "同时控制出题中心和聊天。开启后由 AI 按题目需要选择配图，已有题图不受影响。",
    "illustration.required": "本次必须配图",
    "illustration.disabled": "题目插图生成已关闭，请在出题中心开启后重试。",
    "illustration.unavailableSetting": "题目插图功能尚未开放。",
    "illustration.login": "登录后可设置题目插图偏好。",
    "illustration.saveFailed": "设置保存失败，请重试。",
    "illustration.loadFailed": "设置读取失败，请重试。",
    "illustration.retry": "重试",
    "illustration.saving": "保存中…",

    "review.sectionTitle": "生成审查选项",
    "review.sectionDesc": "审查更严格但更慢，偶尔会误拒可用的题目或插图；关闭后仅保留确定性的结构与安全校验。",
    "review.critic": "生成后审核题目质量",
    "review.criticDesc": "关闭后出题跳过独立审题（critic），题目更快交付且不易落入保底草稿，但答案正确性未经二次核对。",
    "review.illustrationAudit": "生成后审查题图",
    "review.illustrationAuditDesc": "关闭后题图仅过确定性 SVG 安全校验，不再由 AI 复核图文一致性，配图更快更稳定。",
    "review.on": "开启",
    "review.off": "关闭",

    "page.desc": "自适应诊断：根据你的作答动态调整题目难度，帮助了解你在本概念上的当前表现；结论仅反映本轮作答，不等同于长期掌握。",

    "config.title": "发起自适应测评",
    "config.desc": "选择工作区与概念，系统将生成一组难度自适应的题目。",
    "config.start": "开始测评",
    "config.starting": "正在出题…",

    "disabled.title": "自适应测评未启用",
    "disabled.desc": "M4 智能层已被环境开关关闭。可继续使用下方的练习会话，或联系管理员开启后重试。",

    "ask.answered": "已答",
    "ask.difficulty": "难度",
    "ask.submit": "提交答案",
    "ask.submitting": "判分中…",
    "ask.answerPh": "在此输入你的答案…",

    "fb.title": "判分结果",
    "fb.score": "得分",
    "fb.next": "下一题",
    "fb.loading": "正在生成下一题…",
    "fb.finish": "查看总结",

    "abandon": "放弃测评",
    "abandoning": "正在放弃…",

    "sum.title": "测评总结",
    "sum.asked": "已答题数",
    "sum.correct": "答对",
    "sum.wrong": "答错",
    "sum.partial": "部分正确",
    "sum.final_difficulty": "最终难度",
    "sum.stop_reason": "结束原因",
    "sum.stop_reason.sufficient_for_current_claim": "已覆盖本轮目标主张，证据足够（仅本轮结论）",
    "sum.stop_reason.needs_clarification": "仍有未澄清的主张，可换个角度再检验",
    "sum.stop_reason.max_questions": "已达到本轮题数上限，可稍后再检验一次",
    "sum.stop_reason.max_time": "已达到本轮时间上限",
    "sum.stop_reason.user_stopped": "你主动结束了本轮测评",
    "sum.stop_reason.generation_failed": "出题失败，本轮提前结束",
    "sum.again": "再来一次",
    "sum.empty": "暂无总结数据",

    "recent.title": "近期练习会话",
    "recent.desc": "包含测验记录的对话，点击回到会话继续练习。",
    "recent.quizUnit": "题",
    "recent.empty": "暂无练习会话",
    "recent.loadFail": "会话加载失败",

    "rq.title": "最近习题",
    "rq.desc": "跨会话汇集最近生成的题目（最多保留 100 道），点击回到出题会话。",
    "rq.empty": "暂无习题记录",
    "rq.loadFail": "习题加载失败",
    "rq.unanswered": "未作答",
    "rq.type.multiple_choice": "选择",
    "rq.type.fill_blank": "填空",
    "rq.type.short_answer": "简答",
    "rq.diff.easy": "基础",
    "rq.diff.medium": "中等",
    "rq.diff.hard": "挑战",

    "eb.title": "错题本",
    "eb.desc": "跨会话汇集你答错或半对的题目，点「重练」让教练仿照出一道变式。",
    "eb.empty": "暂无错题",
    "eb.empty.desc": "答题卡作答后，答错或半对的题会自动收进来。",
    "eb.loadFail": "错题本加载失败",
    "eb.rework": "重练",
    "eb.rework.msg": "我之前这道题做错了：「%s」。请仿照它出一道变式题让我重练，做完帮我批改讲解。",
    "eb.your.answer": "我的作答",
    "eb.correct.answer": "参考答案",
    "eb.goto.session": "回到出题会话",

    "err.start": "发起测评失败",
    "err.answer": "提交答案失败",
    "err.next": "获取下一题失败",
    "err.abandon": "放弃测评失败",
    "err.noActive": "没有进行中的测评，请重新开始",
  },
  en: {
    "illustration.review": "Review question",
    "illustration.title": "Question illustration",
    "illustration.optionsTitle": "Question illustration options",
    "illustration.expand": "Enlarge",
    "illustration.close": "Close",
    "illustration.unavailable": "Unable to display the diagram. Refresh to retry. Its description follows.",
    "illustration.setting": "Allow question illustrations",
    "illustration.desc": "Applies to assessment and chat. AI adds diagrams when useful. Existing diagrams are preserved.",
    "illustration.required": "Require diagrams for this assessment",
    "illustration.disabled": "Illustrations are disabled. Enable them in the assessment center and retry.",
    "illustration.unavailableSetting": "Question illustrations are not available on this server yet.",
    "illustration.login": "Sign in to set your illustration preference.",
    "illustration.saveFailed": "Could not save the setting. Please retry.",
    "illustration.loadFailed": "Could not load the setting. Please retry.",
    "illustration.retry": "Retry",
    "illustration.saving": "Saving…",

    "review.sectionTitle": "Generation review options",
    "review.sectionDesc": "Reviews are stricter but slower and occasionally reject usable questions or diagrams; turning them off keeps only deterministic structural and safety checks.",
    "review.critic": "Review question quality after generation",
    "review.criticDesc": "Off skips the independent critic: questions arrive faster and rarely fall back to self-check drafts, but answer keys are not double-checked.",
    "review.illustrationAudit": "Review diagrams after generation",
    "review.illustrationAuditDesc": "Off keeps only the deterministic SVG safety check without the AI consistency audit, so diagrams arrive faster and more reliably.",
    "review.on": "On",
    "review.off": "Off",

    "page.desc": "Adaptive diagnosis: difficulty adapts to your answers to probe your current performance on a concept; the result reflects only this round, not long-term mastery.",

    "config.title": "Start an adaptive assessment",
    "config.desc": "Pick a workspace and concepts; the system generates a set of difficulty-adaptive questions.",
    "config.start": "Start assessment",
    "config.starting": "Generating…",

    "disabled.title": "Adaptive assessment unavailable",
    "disabled.desc": "The M4 intelligence layer is turned off by an environment flag. You can still use the practice sessions below, or ask an admin to enable it.",

    "ask.answered": "Answered",
    "ask.difficulty": "Difficulty",
    "ask.submit": "Submit answer",
    "ask.submitting": "Grading…",
    "ask.answerPh": "Type your answer here…",

    "fb.title": "Grading result",
    "fb.score": "Score",
    "fb.next": "Next question",
    "fb.loading": "Generating next question…",
    "fb.finish": "View summary",

    "abandon": "Abandon",
    "abandoning": "Abandoning…",

    "sum.title": "Assessment summary",
    "sum.asked": "Questions asked",
    "sum.correct": "Correct",
    "sum.wrong": "Wrong",
    "sum.partial": "Partial",
    "sum.final_difficulty": "Final difficulty",
    "sum.stop_reason": "Stop reason",
    "sum.stop_reason.sufficient_for_current_claim": "Target claims of this round covered with sufficient evidence (this round only)",
    "sum.stop_reason.needs_clarification": "Some claims still need clarification — probe from another angle later",
    "sum.stop_reason.max_questions": "Question cap for this round reached; check again later",
    "sum.stop_reason.max_time": "Time cap for this round reached",
    "sum.stop_reason.user_stopped": "You ended this round",
    "sum.stop_reason.generation_failed": "Question generation failed — round ended early",
    "sum.again": "Start over",
    "sum.empty": "No summary data",

    "recent.title": "Recent practice sessions",
    "recent.desc": "Conversations containing quizzes. Click to resume.",
    "recent.quizUnit": "quiz",
    "recent.empty": "No practice sessions yet",
    "recent.loadFail": "Failed to load sessions",

    "rq.title": "Recent questions",
    "rq.desc": "Questions generated across sessions (up to 100 kept). Click to revisit the session.",
    "rq.empty": "No questions yet",
    "rq.loadFail": "Failed to load questions",
    "rq.unanswered": "Unanswered",
    "rq.type.multiple_choice": "MC",
    "rq.type.fill_blank": "Fill-in",
    "rq.type.short_answer": "Short answer",
    "rq.diff.easy": "Basic",
    "rq.diff.medium": "Medium",
    "rq.diff.hard": "Hard",

    "eb.title": "Mistake notebook",
    "eb.desc": "Questions you got wrong or partially right, gathered across sessions. Hit Rework for a variant drill.",
    "eb.empty": "No mistakes yet",
    "eb.empty.desc": "Wrong or partially correct answers on quiz cards are collected here automatically.",
    "eb.loadFail": "Failed to load the mistake notebook",
    "eb.rework": "Rework",
    "eb.rework.msg": "I got this question wrong: \"%s\". Please create a variant for me to retry, then grade and explain it.",
    "eb.your.answer": "My answer",
    "eb.correct.answer": "Correct answer",
    "eb.goto.session": "Open the original session",

    "err.start": "Failed to start assessment",
    "err.answer": "Failed to submit answer",
    "err.next": "Failed to load next question",
    "err.abandon": "Failed to abandon",
    "err.noActive": "No active assessment — please start again",
  },
} satisfies PageStrings;
