import type { PageStrings } from "@/lib/i18n-page";

/** D10 is the single source for user-facing workbench copy (zh/en pairs). */
export const STRINGS: PageStrings = {
  zh: {
    title: "几何作图器", intro: "平面几何、二维/三维函数与基础微积分的本地作图工作台。",
    backToTools: "返回工具助手",
    untitled: "未命名绘图", unsaved: "未保存", savedInBrowser: "已保存到此浏览器", saveFailed: "保存失败",
    undo: "撤销", redo: "重做",
    fileNew: "新建", fileOpen: "打开绘图", fileSave: "保存", fileMore: "更多",
    rename: "重命名", saveAs: "另存为", importJson: "导入 JSON", exportJson: "导出 JSON", exportCanvas: "导出当前画布", deleteDrawing: "删除绘图",
    recentSaves: "最近保存", openDrawingAction: "打开", searchDrawings: "搜索绘图", noDrawings: "此浏览器还没有保存的绘图",
    fileFilterMode: "仅当前模式",
    savedLocalOnly: "文档保存在此浏览器，不跨设备同步。",
    functionsTab: "函数输入", objectsTab: "对象", inspectorTab: "属性", calculatorTab: "数学工具",
    addFunction: "添加函数", addFunctionCommit: "添加", removeFunction: "删除", showFunction: "显示/隐藏", details: "详情",
    modeToggle: "选择绘图模式", modePanelTitle: "绘图模式",
    modeFunctions2d: "二维函数", modeGeometry2d: "平面几何", modeFunctions3d: "三维函数",
    modeFunctions2dDesc: "绘制 y=f(x)、参数、极坐标与隐式曲线", modeGeometry2dDesc: "在网格纸上构造点、线、圆并测量",
    modeFunctions3dDesc: "绘制曲面、参数曲面、等值面与空间曲线",
    unsavedTitle: "当前绘图尚未保存", unsavedBody: "离开后，尚未保存的更改将丢失。是否先保存此绘图？",
    unsavedSwitchBody: "当前模式有未保存的更改。切换模式不会丢弃数据，但建议先保存。",
    saveAndContinue: "保存并继续", discardChanges: "放弃更改", switchDirectly: "直接切换", cancel: "取消",
    statusMode: "当前", cursor: "坐标", zoom: "缩放", snap: "吸附",
    zoomIn: "放大", zoomOut: "缩小", resetView: "回到原点", resetCamera: "重置视角", fitView: "适配视图",
    expressionPlaceholder: "例如 y = sin(x)",
    expressionTypeExplicit: "y = f(x)", expressionTypeInverse: "x = f(y)", expressionTypeParametric: "参数", expressionTypePolar: "极坐标", expressionTypeImplicit: "隐式",
    surfaceExplicit: "显式曲面", surfaceParametric: "参数曲面", surfaceImplicit: "隐式曲面", curve3d: "参数曲线",
    plotType: "类型", domain: "定义域", quality: "质量", low: "低", normal: "标准", high: "高", opacity: "透明度", showGrid: "参数网格",
    levelLabel: "等值 c", resolutionLabel: "分辨率", samplesLabel: "采样数", invalidDomain: "区间有误：下限需小于上限",
    parameters: "参数", addParameter: "新增参数", paramName: "名称", paramValue: "值", paramMin: "最小", paramMax: "最大", paramStep: "步长",
    calculatorEvaluate: "求值", calculatorDerivative: "导数", calculatorIntegral: "定积分", calculatorSolve: "解方程",
    calculatorAt: "在 x =", calculatorFrom: "从", calculatorTo: "到",
    analysisSource: "函数来源", analysisManual: "手动输入", drawDerivative: "绘制导数曲线",
    symbolicUnsupported: "无法得到符号形式，已回退数值结果。",
    methodExact: "精确解", methodNumeric: "区间数值解", rootSimple: "单根", rootDouble: "重根", rootsUnit: "个根",
    noRootsFound: "当前区间未找到根，可尝试扩大区间后重试。", markSingle: "标记",
    integralConverged: "已收敛", integralNotConverged: "未收敛", integralEvaluations: "求值次数",
    calculatorRun: "计算", markToCanvas: "标记到图上", result: "结果", noResult: "尚无结果",
    toolSelect: "选择", toolPoint: "点", toolLine: "线段", toolCircle: "圆", toolMeasure: "测量", toolText: "文本",
    hintToolStart: "点击放置起点（可点击已有点复用）· Esc 取消", hintPending: "点击完成图形（可点击已有点复用）· Esc 取消",
    selectObjectHint: "在画布或对象列表中选择一个对象查看属性。",
    lengthLabel: "长度", radiusLabel: "半径", lockedLabel: "锁定",
    gridSnap: "网格吸附", toggleGrid: "网格",
    deleteSelected: "删除所选", visibility: "可见", label: "标签", color: "颜色", lineWidth: "线宽",
    objKindPoint: "点", objKindLine: "线", objKindConstructedLine: "构造线", objKindCircle: "圆", objKindArc: "弧", objKindPolygon: "多边形", objKindRegularPolygon: "正多边形",
    confirmDeleteTitle: "删除绘图", confirmDeleteBody: "将删除此浏览器中保存的该绘图，无法恢复。",
    confirmCascadeTitle: "删除被依赖的对象", confirmCascadeBody: "有其他对象依赖此对象，将一并删除依赖它的对象。",
    importFailed: "导入失败：文件不是有效的绘图文档。", importSuccess: "已导入为未保存的新文档。",
    recoveryBanner: "发现上次未保存草稿", recoveryRestore: "恢复", recoveryDismiss: "忽略",
    presets: "示例", loadPreset: "载入示例",
    functionsHint: "输入表达式立即开始绘图，空行不是错误。",
    examples: "试试这些",
    helpTitle: "帮助与快捷键", helpBody: "Ctrl+S 保存 · Ctrl+O 打开 · Ctrl+N 新建 · Ctrl+Z 撤销 · Shift+Ctrl+Z 重做 · Alt+1/2/3 切换模式",
    helpWheel: "滚轮缩放（以光标为中心）· 拖拽空白平移 · 双击文本注释可编辑 · 构造中 Esc 取消 · Delete 删除所选 · 每个模式独立保存",
    objectsEmpty: "暂无对象，从左侧工具栏开始构造。",
    webglUnavailable: "当前浏览器不支持 WebGL2，三维舞台不可用；二维绘图与计算不受影响。",
    stage3d: "三维舞台",
    saveNamePrompt: "绘图名称", saveNamePlaceholder: "未命名绘图 1",
    invalidExpression: "表达式有误",
    demoReadonlyHint: "演示模式为只读：可查看与旋转，创建、编辑和保存请在登录后使用。",
  },
  en: {
    title: "Geometry workbench", intro: "Local drawing workbench for plane geometry, 2D/3D functions and basic calculus.",
    backToTools: "Back to tool assistants",
    untitled: "Untitled drawing", unsaved: "Unsaved", savedInBrowser: "Saved in this browser", saveFailed: "Save failed",
    undo: "Undo", redo: "Redo",
    fileNew: "New", fileOpen: "Open drawing", fileSave: "Save", fileMore: "More",
    rename: "Rename", saveAs: "Save as", importJson: "Import JSON", exportJson: "Export JSON", exportCanvas: "Export canvas", deleteDrawing: "Delete drawing",
    recentSaves: "Recent saves", openDrawingAction: "Open", searchDrawings: "Search drawings", noDrawings: "No drawings saved in this browser yet",
    fileFilterMode: "Current mode only",
    savedLocalOnly: "Drawings are saved in this browser only; they do not sync across devices.",
    functionsTab: "Functions", objectsTab: "Objects", inspectorTab: "Properties", calculatorTab: "Math tools",
    addFunction: "Add function", addFunctionCommit: "Add", removeFunction: "Delete", showFunction: "Show/hide", details: "Details",
    modeToggle: "Select drawing mode", modePanelTitle: "Drawing modes",
    modeFunctions2d: "2D functions", modeGeometry2d: "Plane geometry", modeFunctions3d: "3D functions",
    modeFunctions2dDesc: "Plot y=f(x), parametric, polar and implicit curves", modeGeometry2dDesc: "Construct points, lines and circles on grid paper with measurements",
    modeFunctions3dDesc: "Plot surfaces, parametric surfaces, isosurfaces and space curves",
    unsavedTitle: "This drawing is not saved yet", unsavedBody: "Leaving now will discard unsaved changes. Save this drawing first?",
    unsavedSwitchBody: "This mode has unsaved changes. Switching keeps them in memory, but saving first is recommended.",
    saveAndContinue: "Save and continue", discardChanges: "Discard changes", switchDirectly: "Switch anyway", cancel: "Cancel",
    statusMode: "Current", cursor: "Cursor", zoom: "Zoom", snap: "Snap",
    zoomIn: "Zoom in", zoomOut: "Zoom out", resetView: "Reset to origin", resetCamera: "Reset view", fitView: "Fit view",
    expressionPlaceholder: "e.g. y = sin(x)",
    expressionTypeExplicit: "y = f(x)", expressionTypeInverse: "x = f(y)", expressionTypeParametric: "Parametric", expressionTypePolar: "Polar", expressionTypeImplicit: "Implicit",
    surfaceExplicit: "Explicit surface", surfaceParametric: "Parametric surface", surfaceImplicit: "Implicit surface", curve3d: "Parametric curve",
    plotType: "Type", domain: "Domain", quality: "Quality", low: "Low", normal: "Normal", high: "High", opacity: "Opacity", showGrid: "Parameter grid",
    levelLabel: "Level c", resolutionLabel: "Resolution", samplesLabel: "Samples", invalidDomain: "Invalid range: min must be below max",
    parameters: "Parameters", addParameter: "Add parameter", paramName: "Name", paramValue: "Value", paramMin: "Min", paramMax: "Max", paramStep: "Step",
    calculatorEvaluate: "Evaluate", calculatorDerivative: "Derivative", calculatorIntegral: "Integral", calculatorSolve: "Solve",
    calculatorAt: "at x =", calculatorFrom: "From", calculatorTo: "To",
    analysisSource: "Function source", analysisManual: "Manual input", drawDerivative: "Plot derivative",
    symbolicUnsupported: "No symbolic form available; numeric result shown instead.",
    methodExact: "Exact", methodNumeric: "Numeric scan", rootSimple: "simple", rootDouble: "double", rootsUnit: "roots",
    noRootsFound: "No roots found in this interval — widen it and run again.", markSingle: "Mark",
    integralConverged: "converged", integralNotConverged: "not converged", integralEvaluations: "evaluations",
    calculatorRun: "Calculate", markToCanvas: "Mark on canvas", result: "Result", noResult: "No result yet",
    toolSelect: "Select", toolPoint: "Point", toolLine: "Segment", toolCircle: "Circle", toolMeasure: "Measure", toolText: "Text",
    hintToolStart: "Click to place the start point (click an existing point to reuse it) · Esc cancels", hintPending: "Click to finish the shape (existing points are reusable) · Esc cancels",
    selectObjectHint: "Select an object on the canvas or in the list to see its properties.",
    lengthLabel: "Length", radiusLabel: "Radius", lockedLabel: "Locked",
    gridSnap: "Grid snap", toggleGrid: "Grid",
    deleteSelected: "Delete selection", visibility: "Visible", label: "Label", color: "Color", lineWidth: "Width",
    objKindPoint: "Point", objKindLine: "Line", objKindConstructedLine: "Constructed", objKindCircle: "Circle", objKindArc: "Arc", objKindPolygon: "Polygon", objKindRegularPolygon: "Regular polygon",
    confirmDeleteTitle: "Delete drawing", confirmDeleteBody: "This deletes the drawing saved in this browser and cannot be undone.",
    confirmCascadeTitle: "Delete depended-on object", confirmCascadeBody: "Other objects depend on this one; they will be deleted too.",
    importFailed: "Import failed: the file is not a valid drawing document.", importSuccess: "Imported as an unsaved new drawing.",
    recoveryBanner: "Unsaved draft from last session found", recoveryRestore: "Restore", recoveryDismiss: "Dismiss",
    presets: "Examples", loadPreset: "Load example",
    functionsHint: "Type an expression to start plotting — an empty row is not an error.",
    examples: "Try these",
    helpTitle: "Help & shortcuts", helpBody: "Ctrl+S save · Ctrl+O open · Ctrl+N new · Ctrl+Z undo · Shift+Ctrl+Z redo · Alt+1/2/3 switch mode",
    helpWheel: "Scroll to zoom (at cursor) · drag empty space to pan · double-click a text note to edit · Esc cancels a construction · Delete removes the selection · each mode saves separately",
    objectsEmpty: "No objects yet — start constructing from the left toolbar.",
    webglUnavailable: "WebGL2 is unavailable in this browser; the 3D stage is disabled. 2D plotting and calculations still work.",
    stage3d: "3D stage",
    saveNamePrompt: "Drawing name", saveNamePlaceholder: "Untitled drawing 1",
    invalidExpression: "Invalid expression",
    demoReadonlyHint: "The demo is read-only: view and orbit freely; create, edit and save after signing in.",
  },
};
