import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "res.title": "资料中心",
    "res.desc": "你的个人资料库：文件按文件夹组织，只有被学习区选中的资料才会参与对话检索（RAG）。",
    "res.group.library": "资料库",
    "res.group.sessions": "会话附件",
    "res.all": "全部文件",
    "res.root": "未归档",
    "res.noSessions": "暂无含附件的会话",
    "res.new.folder": "新建文件夹",
    "res.new.folder.placeholder": "文件夹名称…",
    "res.new.ws": "新建学习区",
    "res.rename": "重命名",
    "res.delete": "删除",
    "res.download": "下载",
    "res.move": "移动到…",
    "res.move.root": "未归档",
    "res.exclusive": "学习区专属",
    "res.delete.folder.title": "删除文件夹",
    "res.delete.folder.desc": "文件夹及其中文件会进入归档中心，活动资料库和学习区将暂时不可见；到期前可恢复。",
    "res.delete.file.title": "删除文件",
    "res.delete.file.desc": "文件会进入归档中心，活动资料库和学习区将暂时不可见；到期前可恢复。",
    "res.confirm.delete": "删除",
    "res.files.unit": "个文件",
    "res.chars.unit": "字符",
    "res.chunks.unit": "块",
    "res.upload.drop": "拖拽文件到此处，或点击选择",
    "res.upload.hint": "支持 PDF / DOCX / PPTX / TXT / MD，单个 ≤256MB，可多选；上传后默认仅资料库可见",
    "res.uploading": "上传中…",
    "res.upload.failed": "上传失败，请重试",
    "res.download.failed": "下载失败：原始文件未保留或已删除",
    "res.session.note.title": "会话附件请在对话中上传",
    "res.session.note.desc": "该会话的附件随对话上下文管理，仅该会话可检索。",
    "res.session.open": "打开会话",
    "res.pick.hint.title": "选择一个来源",
    "res.pick.hint.desc": "在左侧选择资料库文件夹或会话，查看其中的文件。",
    "res.empty.title": "资料库还是空的",
    "res.empty.desc": "上传教材、讲义等文件到资料库，再在学习区设置中选入，对话时即可检索引用。",
    "res.empty.files": "暂无文件",
    "res.load.failed": "加载失败，请检查后端服务后重试",
    "res.retry": "重试",
    "res.updated": "更新于",
    "res.tab.files": "文件库",
    "res.tab.textbooks": "教材库",
    "res.tb.nav.all": "全部教材",
    "res.tb.nav.loading": "载入教材分层…",
    "res.tb.nav.empty": "暂无教材，先在右侧上传",
    "res.tb.nav.filtered": "教材组",
    "res.tb.nav.filteredMiss": "该组不在当前账号可见范围",
    "res.tb.nav.clearFilter": "显示全部",
    "res.tb.title": "教材库",
    "res.tb.desc": "上传任意学科的教材 PDF，系统会自动解析、检索索引，并构建专属知识图谱。教材被学习区/会话选入后即可在对话中检索引用。",
    "res.tb.upload.drop": "拖拽教材到此处，或点击选择",
    "res.tb.upload.hint": "支持大 PDF 教材（≤256MB），可多选；上传后自动构建知识图谱（分钟级）",
    "res.tb.upload.level": "教材学段：",
    "res.tb.upload.public": "上传到公用教材库",
    "res.tb.upload.publicHint": "公用教材库：所有账号可选用",
    "res.tb.upload.group": "教材组名（可选）：多卷 PDF 编为一组，统一构建知识谱系",
    "res.tb.upload.open": "上传教材",
    "res.tb.upload.intro": "支持大 PDF 教材（≤256MB），可多卷编组；上传后自动解析并构建知识图谱。",
    "res.tb.group.badge": "教材组",
    "res.tb.group.volumes": "卷",
    "res.tb.group.volumes.title": "分卷",
    "res.tb.group.volume.remove": "移除该卷（剩余卷自动重建图谱）",
    "res.tb.group.note": "组后加的卷不会自动进入已存在的会话/工作区选择，需要重新勾选。",
    "res.tb.public": "公用教材库",
    "res.tb.public.badge": "公用",
    "res.tb.mine": "我的教材",
    "res.tb.empty.mine": "还没有自己的教材",
    "res.tb.uploading": "上传中…",
    "res.tb.empty.title": "还没有教材",
    "res.tb.empty.desc": "上传一本教材，AI 会自动理解其结构并构建专属知识图谱，把它变成你的私人教师。",
    "res.tb.building": "构建图谱中",
    "res.tb.ready": "就绪",
    "res.tb.graph_failed": "图谱构建失败",
    "res.tb.failed": "失败",
    "res.tb.retry": "重试构建",
    "res.tb.rebuild": "重建图谱",
    "res.tb.refresh.tip": "刷新 RAG 与知识谱系；默认不重新 OCR",
    "res.tb.refresh.title": "刷新教材索引与知识谱系",
    "res.tb.refresh.start": "开始刷新",
    "res.tb.refresh.rag": "RAG + 知识谱系（推荐）",
    "res.tb.refresh.rag.desc": "复用现有解析/OCR 文本；重建 V2 切片、BM25、向量和必要图谱，不会重新 OCR。",
    "res.tb.refresh.graph": "仅知识谱系",
    "res.tb.refresh.graph.desc": "只重新抽取知识谱系，不改变 RAG 切片，也不会重新 OCR。",
    "res.tb.refresh.ocr": "完整重新 OCR（升级图表与页码提取）",
    "res.tb.refresh.ocr.desc": "逐页重新调用多模态 OCR，产出插图描述、表格结构与教材印刷页码；按管理员重试策略等待，耗时和调用量较大。",
    "res.tb.refresh.upgrade": "此教材转录于图表提取上线前，不含插图描述与印刷页码；建议完整重新 OCR 一次升级（之后日常刷新仍用 RAG + 知识谱系）。",
    "res.tb.refresh.ocr.warn": "确认后会重新处理全部页面；默认策略会持续等待多模态 API 成功，不自动降级。",
    "res.tb.ocr_paused": "OCR 已暂停",
    "res.tb.cancel.tip": "终止当前解析（OCR / 构建）；已有文本与切片保留",
    "res.tb.cancel.confirm.title": "终止解析",
    "res.tb.cancel.confirm.desc": "将停止当前教材的 OCR 与知识谱系构建。已解析的文本与检索切片会保留；如需完整成果可稍后重新构建。",
    "res.tb.cancel.confirm.start": "终止解析",
    "res.tb.cancel.confirm.done": "已终止解析",
    "res.tb.bulk.enter": "批量操作",
    "res.tb.bulk.hint": "需要同时刷新多本教材时，可进入批量操作多选提交",
    "res.tb.bulk.exit": "退出批量",
    "res.tb.bulk.selectAll": "全选",
    "res.tb.bulk.clear": "清空选择",
    "res.tb.bulk.selected": "已选 %n 本",
    "res.tb.bulk.rebuild": "批量重建",
    "res.tb.bulk.cancel": "批量取消",
    "res.tb.bulk.rebuild.title": "批量刷新 %n 本教材",
    "res.tb.bulk.cancel.title": "批量终止解析",
    "res.tb.bulk.cancel.desc": "将对所选 %n 本教材执行合作式终止；已解析的文本与检索切片会保留。",
    "res.tb.bulk.summary.rebuild": "已加入重建队列 %n 本 · 跳过 %k 本（在建/缺失/无权限）",
    "res.tb.bulk.summary.cancel": "已终止 %n 本 · 跳过 %k 本（不在解析中）",
    "res.tb.ocr.blocked": "多模态配置阻塞",
    "res.tb.ocr.waiting": "等待下一次多模态 OCR",
    "res.tb.ocr.attempt": "第",
    "res.tb.ocr.attempt.suffix": "次",
    "res.tb.ocr.pages": "页待处理",
    "res.tb.stage.ocr_waiting": "OCR 等待重试",
    "res.tb.stage.ocr_paused": "OCR 已暂停",
    "res.tb.detail": "详情",
    "res.tb.chapters": "章",
    "res.tb.concepts": "概念",
    "res.tb.view_graph": "在知识图谱中查看",
    "res.tb.detail.title": "教材详情",
    "res.tb.outline": "章节大纲",
    "res.tb.no_outline": "图谱尚未构建完成，暂无大纲",
    "res.tb.warnings": "构建提示",
    "res.tb.delete.title": "删除教材",
    "res.tb.delete.desc": "教材、原文件与知识谱系会作为一个完整归档包进入归档中心，可查看、恢复或二次确认后彻底删除。",
    "res.tb.edit.title": "编辑信息",
    "res.tb.subject": "学科",
    "res.tb.level": "学段",
    "res.tb.save": "保存",
    "res.tb.cancel": "取消",
    "res.tb.stage.parse": "解析中",
    "res.tb.stage.ocr": "OCR 识别中",
    "res.tb.stage.index": "索引中",
    "res.tb.stage.skeleton": "分析结构",
    "res.tb.stage.chapters": "抽取概念",
    "res.tb.stage.merge": "合并图谱",
  },
  en: {
    "res.title": "Resources",
    "res.desc": "Your personal library: files live in folders and stay private until a workspace selects them for RAG retrieval.",
    "res.group.library": "Library",
    "res.group.sessions": "Session attachments",
    "res.all": "All files",
    "res.root": "Unfiled",
    "res.noSessions": "No sessions with attachments",
    "res.new.folder": "New folder",
    "res.new.folder.placeholder": "Folder name…",
    "res.new.ws": "New workspace",
    "res.rename": "Rename",
    "res.delete": "Delete",
    "res.download": "Download",
    "res.move": "Move to…",
    "res.move.root": "Unfiled",
    "res.exclusive": "Workspace",
    "res.delete.folder.title": "Delete folder",
    "res.delete.folder.desc": "The folder and its files will move to Archive Center and disappear from active workspaces until restored.",
    "res.delete.file.title": "Delete file",
    "res.delete.file.desc": "The file will move to Archive Center and disappear from active workspaces until restored.",
    "res.confirm.delete": "Delete",
    "res.files.unit": "files",
    "res.chars.unit": "chars",
    "res.chunks.unit": "chunks",
    "res.upload.drop": "Drop files here, or click to browse",
    "res.upload.hint": "PDF / DOCX / PPTX / TXT / MD, up to 256MB each, multiple allowed; visible only to the library until selected",
    "res.uploading": "Uploading…",
    "res.upload.failed": "Upload failed, please try again",
    "res.download.failed": "Download failed: original not kept or deleted",
    "res.session.note.title": "Session attachments are uploaded in chat",
    "res.session.note.desc": "Attachments follow the conversation context and are retrievable only by that session.",
    "res.session.open": "Open session",
    "res.pick.hint.title": "Pick a source",
    "res.pick.hint.desc": "Select a library folder or a session on the left to browse its files.",
    "res.empty.title": "Your library is empty",
    "res.empty.desc": "Upload textbooks or handouts here, then select them in a workspace's settings so chats can retrieve them.",
    "res.empty.files": "No files",
    "res.load.failed": "Failed to load. Check the backend and retry.",
    "res.retry": "Retry",
    "res.updated": "Updated",
    "res.tab.files": "Files",
    "res.tab.textbooks": "Textbooks",
    "res.tb.nav.all": "All textbooks",
    "res.tb.nav.loading": "Loading textbook layers…",
    "res.tb.nav.empty": "No textbooks yet — upload on the right",
    "res.tb.nav.filtered": "Textbook group",
    "res.tb.nav.filteredMiss": "This group is not visible to your account",
    "res.tb.nav.clearFilter": "Show all",
    "res.tb.title": "Textbooks",
    "res.tb.desc": "Upload a textbook PDF of any subject. The system auto-parses, indexes, and builds a dedicated knowledge graph. Select it in a workspace/session to retrieve it in chat.",
    "res.tb.upload.drop": "Drop a textbook here, or click to browse",
    "res.tb.upload.hint": "Large PDF textbooks supported (≤256MB), multiple allowed; a knowledge graph is built automatically (minutes)",
    "res.tb.upload.level": "Stage:",
    "res.tb.upload.public": "Upload to public library",
    "res.tb.upload.publicHint": "Public library: selectable by all accounts",
    "res.tb.upload.group": "Group name (optional): bundle volumes into one unified knowledge graph",
    "res.tb.upload.open": "Upload textbook",
    "res.tb.upload.intro": "Large textbook PDFs supported (≤256MB); bundle volumes into a group and the knowledge graph is built automatically.",
    "res.tb.group.badge": "Group",
    "res.tb.group.volumes": "vols",
    "res.tb.group.volumes.title": "Volumes",
    "res.tb.group.volume.remove": "Remove this volume (graph auto-rebuilds from the rest)",
    "res.tb.group.note": "Volumes added later won't auto-join existing session/workspace selections — re-select to include them.",
    "res.tb.public": "Public library",
    "res.tb.public.badge": "Public",
    "res.tb.mine": "My textbooks",
    "res.tb.empty.mine": "No textbooks of your own yet",
    "res.tb.uploading": "Uploading…",
    "res.tb.empty.title": "No textbooks yet",
    "res.tb.empty.desc": "Upload a textbook and the AI will understand its structure, build a dedicated knowledge graph, and turn it into your private tutor.",
    "res.tb.building": "Building graph",
    "res.tb.ready": "Ready",
    "res.tb.graph_failed": "Graph failed",
    "res.tb.failed": "Failed",
    "res.tb.retry": "Retry build",
    "res.tb.rebuild": "Rebuild graph",
    "res.tb.refresh.tip": "Refresh RAG and graph; OCR is not rerun by default",
    "res.tb.refresh.title": "Refresh textbook indexes and graph",
    "res.tb.refresh.start": "Start refresh",
    "res.tb.refresh.rag": "RAG + graph (recommended)",
    "res.tb.refresh.rag.desc": "Reuse existing parsed/OCR text and rebuild V2 chunks, BM25, vectors, and the graph when needed. No OCR rerun.",
    "res.tb.refresh.graph": "Graph only",
    "res.tb.refresh.graph.desc": "Re-extract only the knowledge graph without changing RAG chunks or rerunning OCR.",
    "res.tb.refresh.ocr": "Full OCR rerun (upgrade figures & page numbers)",
    "res.tb.refresh.ocr.desc": "Re-run multimodal OCR page by page to produce figure descriptions, table structure and printed page numbers; waits per the admin retry policy.",
    "res.tb.refresh.upgrade": "This textbook was transcribed before figure extraction existed — no figure descriptions or printed page numbers. A one-time full OCR rerun upgrades it (daily refresh stays RAG + graph).",
    "res.tb.refresh.ocr.warn": "All pages will be processed again. The default policy keeps waiting for the multimodal API and does not downgrade automatically.",
    "res.tb.ocr_paused": "OCR paused",
    "res.tb.cancel.tip": "Stop parsing (OCR / build); existing text and chunks are kept",
    "res.tb.cancel.confirm.title": "Stop parsing",
    "res.tb.cancel.confirm.desc": "Stops OCR and knowledge graph building for this textbook. Already extracted text and search chunks are kept; you can rebuild later for full results.",
    "res.tb.cancel.confirm.start": "Stop parsing",
    "res.tb.cancel.confirm.done": "Parsing stopped",
    "res.tb.bulk.enter": "Batch actions",
    "res.tb.bulk.hint": "Pick multiple textbooks and submit a refresh for all of them at once",
    "res.tb.bulk.exit": "Exit batch",
    "res.tb.bulk.selectAll": "Select all",
    "res.tb.bulk.clear": "Clear selection",
    "res.tb.bulk.selected": "%n selected",
    "res.tb.bulk.rebuild": "Batch rebuild",
    "res.tb.bulk.cancel": "Batch cancel",
    "res.tb.bulk.rebuild.title": "Refresh %n textbooks",
    "res.tb.bulk.cancel.title": "Stop parsing (batch)",
    "res.tb.bulk.cancel.desc": "Cooperatively stops parsing for the %n selected textbooks; extracted text and search chunks are kept.",
    "res.tb.bulk.summary.rebuild": "%n queued for rebuild · %k skipped (running/missing/forbidden)",
    "res.tb.bulk.summary.cancel": "%n stopped · %k skipped (not parsing)",
    "res.tb.ocr.blocked": "Multimodal configuration blocked",
    "res.tb.ocr.waiting": "Waiting for next multimodal OCR attempt",
    "res.tb.ocr.attempt": "Attempt ",
    "res.tb.ocr.attempt.suffix": "",
    "res.tb.ocr.pages": "pages pending",
    "res.tb.stage.ocr_waiting": "OCR retry wait",
    "res.tb.stage.ocr_paused": "OCR paused",
    "res.tb.detail": "Details",
    "res.tb.chapters": "chapters",
    "res.tb.concepts": "concepts",
    "res.tb.view_graph": "View in knowledge graph",
    "res.tb.detail.title": "Textbook details",
    "res.tb.outline": "Chapter outline",
    "res.tb.no_outline": "Outline unavailable until the graph finishes building",
    "res.tb.warnings": "Build notes",
    "res.tb.delete.title": "Delete textbook",
    "res.tb.delete.desc": "The textbook, source files and knowledge map move together into Archive Center for inspection, restoration, or permanent deletion.",
    "res.tb.edit.title": "Edit info",
    "res.tb.subject": "Subject",
    "res.tb.level": "Stage",
    "res.tb.save": "Save",
    "res.tb.cancel": "Cancel",
    "res.tb.stage.parse": "Parsing",
    "res.tb.stage.ocr": "OCR recognizing",
    "res.tb.stage.index": "Indexing",
    "res.tb.stage.skeleton": "Analyzing structure",
    "res.tb.stage.chapters": "Extracting concepts",
    "res.tb.stage.merge": "Merging graph",
  },
} satisfies PageStrings;
