/**
 * Replay-vector conformance: the TS engine must reproduce, bit-for-bit, the
 * state hashes the Python engine pinned into services/api/app/chem_lab/
 * content/vectors. Any divergence means the two engines drifted apart.
 *
 * Runtime packs come from content/packs/*.json — snapshots of
 * Catalog.build_pack regenerated by scripts/chem_lab/validate_pack.py
 * --write-manifest, so pydantic schema defaults stay single-sourced in
 * Python.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { verifyVector, type AnyDict } from "../src/index.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = join(HERE, "..", "..", "..", "services", "api", "app", "chem_lab", "content");

function readJson(path: string): AnyDict {
  return JSON.parse(readFileSync(path, "utf8"));
}

const PACKS = new Map<string, AnyDict>();
for (const file of readdirSync(join(CONTENT_DIR, "packs")).sort()) {
  if (!file.endsWith(".json")) continue;
  const pack = readJson(join(CONTENT_DIR, "packs", file));
  PACKS.set(pack.id, pack);
}

function collectVectors(): { experiment: string; file: string; vector: AnyDict }[] {
  const out: { experiment: string; file: string; vector: AnyDict }[] = [];
  const vectorsRoot = join(CONTENT_DIR, "vectors");
  for (const experiment of readdirSync(vectorsRoot).sort()) {
    for (const file of readdirSync(join(vectorsRoot, experiment)).sort()) {
      if (!file.endsWith(".json")) continue;
      out.push({ experiment, file, vector: readJson(join(vectorsRoot, experiment, file)) });
    }
  }
  return out;
}

const VECTORS = collectVectors();

test("content tree ships 24 replay vectors across 6 experiments", () => {
  assert.equal(VECTORS.length, 24);
  assert.equal(new Set(VECTORS.map((v) => v.experiment)).size, 6);
  assert.equal(PACKS.size, 6);
});

for (const { experiment, file, vector } of VECTORS) {
  test(`vector ${experiment}/${file} reproduces pinned hashes`, () => {
    const pack = PACKS.get(experiment);
    assert.ok(pack, `runtime pack snapshot for ${experiment} missing — rerun validate_pack.py --write-manifest`);
    const problems = verifyVector(pack, vector);
    assert.deepEqual(problems, []);
  });
}
