export const STRINGS = {
  zh: {
    mode: "允许模态序号", halflives: "展示半衰期个数", retention_a: "A 斑点相对位置", retention_b: "B 斑点相对位置",
    shift: "谱线示意位移（像素）", step: "割线横向步长", p_a: "P(A)", p_b_given_a: "P(B|A)",
    subject: "学科", educationLevel: "适用学段", allLevels: "全部学段", assetKind: "图示形式", allKinds: "全部形式",
    zoomIn: "放大图示", zoomOut: "缩小图示",
    eccentricity: "离心率", rows: "行数", numerator: "分子", denominator: "分母", left: "区间左端", right: "区间右端",
    cycles: "周期数", amplitude: "振幅", tau: "时间常数", electrons: "电子数", lanes: "泳道片段大小（JSON）",
    marked: "标记数量", sample: "样本数量", previewSample: "图中参数和数据用于展示，出题时按题目条件设置。", recaptured: "重捕数量",
    temperature: "每月温度（JSON）", rainfall: "每月降水（JSON）", utc_hour: "UTC 小时", latitude: "纬度", declination: "太阳赤纬", sand: "砂粒百分比", clay: "黏粒百分比",
    groups: "分组数据（JSON）", flows: "流量矩阵（JSON）", target: "目标值", n: "试验次数", probability: "成功概率", rate: "发生率", df1: "分子自由度", df2: "分母自由度",
    start: "起点索引", words: "单词列表（JSON）", quantum: "时间片长度", input: "输入矩阵（JSON）", kernel: "卷积核（JSON）", layers: "各层节点数（JSON）",
    events: "事件时间、名称、分组（JSON）", income: "预算", price_x: "X 单价", price_y: "Y 单价", alpha: "效用权重", demand_intercept: "需求截距", supply_intercept: "供给截距", tax: "税额或外部成本",
    fixed_cost: "固定成本", unit_cost: "单位成本", unit_price: "单位价格", capacity_x: "X 最大产量", capacity_y: "Y 最大产量", choices: "两种选择（JSON）",
    diameter: "公称直径", tolerance: "尺寸公差", stars: "恒星温度与光度（JSON）", sharps: "升号数量", hue: "色相（°）",
    atomic_number: "原子序数", charge: "电荷数", people: "人物信息（JSON）", couples: "配偶关系（JSON）", children: "亲子关系（JSON）", difference: "液面高度差", object_distance: "物距", focal_length: "焦距",
    title: "教学素材库", subtitle: "让每一道题，都有清晰而生动的图示。", eyebrow: "TEACHING ATLAS",
    intro: "从实验仪器到几何构图，探索可组合、可调节的教材插图。", assets: "个素材", all: "全部学科", allFamilies: "全部类型",
    search: "搜索名称或别名，如烧杯、单摆、扇形图…", searchLabel: "搜索素材", family: "素材类型", empty: "没有找到相关素材，试试常用名称或英文别名。",
    loading: "正在展开素材…", failed: "素材加载失败，请重试。", retry: "重试", close: "关闭", preview: "放大与调节", settings: "调整图示", reset: "恢复示例", apply: "更新预览",
    invalid: "参数或数据不符合范围，请检查后重试。", textbook: "教材配色", monochrome: "黑白印刷", style: "图示风格",
    original: "项目原创 SVG", selection: "按学科探索", result: "搜索结果", filters: "筛选素材", parameters: "参数", noParameters: "此素材使用固定结构。", description: "图示说明",
    mathematics: "数学", physics: "物理", chemistry: "化学", statistics: "统计", biology: "生物", geography: "地理", systems: "通用与信息技术",
    geometry: "平面与立体几何", function: "函数与坐标", chart: "统计图表", vessel: "容器与玻璃仪器", apparatus: "实验配件", mechanics: "力学物体", circuit: "电路元件", optics: "光学", measurement: "测量仪器", waves: "波动与流体", earth: "地理与地球", graph: "关系与流程", logic: "逻辑电路", objects: "生活物体", template: "完整构图", matrix: "变换矩阵（JSON）",
    fill: "液面高度占比", liquid_color: "液体颜色", show_scale: "显示刻度", scale_labels: "显示读数", capacity: "刻度容量", lit: "点燃", reading: "读数", maximum: "量程", angle: "角度（°）", radius: "半径", length: "长度", show_angle: "显示角度标记", sides: "边数", count: "数量", filled: "涂色数量", face: "骰子点数", show_values: "显示数值", construction: "辅助构造", show_labels: "显示标签", closed: "闭合开关", displacement: "位移", show_poles: "标记磁极", values: "数值数据（JSON）", labels: "分类名称（JSON）", points: "坐标数据（JSON）", errors: "误差数据（JSON）", bin_edges: "分组边界（JSON）", density: "使用频数密度", df: "自由度", items: "对象名称（JSON）", edges: "连接关系（JSON）", columns: "列数", x_range: "横轴范围（JSON）", y_range: "纵轴范围（JSON）", interval: "区间（JSON）", vector: "向量（JSON）", x_label: "横轴名称", y_label: "纵轴名称", show_ticks: "显示坐标刻度", expression: "函数表达式", none: "无", altitude: "高", median: "中线", bisector: "角平分线",
  },
  en: {
    mode: "Allowed mode index", halflives: "Half-lives shown", retention_a: "Relative spot A position", retention_b: "Relative spot B position",
    shift: "Schematic spectral shift (px)", step: "Secant horizontal step", p_a: "P(A)", p_b_given_a: "P(B|A)",
    subject: "Subject", educationLevel: "Education level", allLevels: "All levels", assetKind: "Illustration kind", allKinds: "All kinds",
    zoomIn: "Zoom in", zoomOut: "Zoom out",
    eccentricity: "Eccentricity", rows: "Rows", numerator: "Numerator", denominator: "Denominator", left: "Left endpoint", right: "Right endpoint",
    cycles: "Cycles", amplitude: "Amplitude", tau: "Time constant", electrons: "Electrons", lanes: "Lane fragment sizes (JSON)",
    marked: "Marked count", sample: "Sample count", previewSample: "Parameters and data shown are preview examples. Questions supply their own conditions.", recaptured: "Recaptured count",
    temperature: "Monthly temperature (JSON)", rainfall: "Monthly rainfall (JSON)", utc_hour: "UTC hour", latitude: "Latitude", declination: "Solar declination", sand: "Sand percentage", clay: "Clay percentage",
    groups: "Grouped data (JSON)", flows: "Flow matrix (JSON)", target: "Target", n: "Trials", probability: "Success probability", rate: "Rate", df1: "Numerator degrees of freedom", df2: "Denominator degrees of freedom",
    start: "Start index", words: "Words (JSON)", quantum: "Time quantum", input: "Input matrix (JSON)", kernel: "Kernel (JSON)", layers: "Nodes in each layer (JSON)",
    events: "Event time, name, group (JSON)", income: "Budget", price_x: "X price", price_y: "Y price", alpha: "Utility weight", demand_intercept: "Demand intercept", supply_intercept: "Supply intercept", tax: "Tax or external cost",
    fixed_cost: "Fixed cost", unit_cost: "Unit cost", unit_price: "Unit price", capacity_x: "X capacity", capacity_y: "Y capacity", choices: "Two alternatives (JSON)",
    diameter: "Nominal diameter", tolerance: "Tolerance", stars: "Stellar temperature and luminosity (JSON)", sharps: "Number of sharps", hue: "Hue (°)",
    atomic_number: "Atomic number", charge: "Charge", people: "People (JSON)", couples: "Couples (JSON)", children: "Parent-child links (JSON)", difference: "Level difference", object_distance: "Object distance", focal_length: "Focal length",
    title: "Teaching atlas", subtitle: "A clear, expressive diagram for every question.", eyebrow: "TEACHING ATLAS",
    intro: "Explore adjustable textbook illustrations, from laboratory instruments to geometric constructions.", assets: "assets", all: "All subjects", allFamilies: "All types",
    search: "Search beakers, pendulums, pie charts…", searchLabel: "Search assets", family: "Asset type", empty: "No matching assets. Try a common name or an English alias.",
    loading: "Opening the atlas…", failed: "Could not load assets. Please retry.", retry: "Retry", close: "Close", preview: "Explore and adjust", settings: "Adjust illustration", reset: "Restore example", apply: "Update preview",
    invalid: "Check the parameter ranges and data, then retry.", textbook: "Textbook colors", monochrome: "Monochrome print", style: "Illustration style",
    original: "Original project artwork · Vector", selection: "Explore by subject", result: "Search results", filters: "Filter assets", parameters: "Parameters", noParameters: "This asset uses a fixed structure.", description: "Diagram description",
    mathematics: "Mathematics", physics: "Physics", chemistry: "Chemistry", statistics: "Statistics", biology: "Biology", geography: "Geography", systems: "General & computing",
    geometry: "Plane & solid geometry", function: "Functions & coordinates", chart: "Statistical charts", vessel: "Vessels & glassware", apparatus: "Laboratory accessories", mechanics: "Mechanical objects", circuit: "Circuit components", optics: "Optics", measurement: "Measuring instruments", waves: "Waves & fluids", earth: "Geography & earth", graph: "Relations & processes", logic: "Logic circuits", objects: "Everyday objects", template: "Complete compositions", matrix: "Transform matrix (JSON)",
    fill: "Liquid height fraction", liquid_color: "Liquid color", show_scale: "Show graduations", scale_labels: "Show readings", capacity: "Graduation capacity", lit: "Light flame", reading: "Reading", maximum: "Range", angle: "Angle (°)", radius: "Radius", length: "Length", show_angle: "Show angle mark", sides: "Sides", count: "Count", filled: "Filled count", face: "Die face", show_values: "Show values", construction: "Construction", show_labels: "Show labels", closed: "Close switch", displacement: "Displacement", show_poles: "Label poles", values: "Values (JSON)", labels: "Categories (JSON)", points: "Coordinates (JSON)", errors: "Errors (JSON)", bin_edges: "Bin edges (JSON)", density: "Use frequency density", df: "Degrees of freedom", items: "Object names (JSON)", edges: "Connections (JSON)", columns: "Columns", x_range: "Horizontal range (JSON)", y_range: "Vertical range (JSON)", interval: "Interval (JSON)", vector: "Vector (JSON)", x_label: "Horizontal axis label", y_label: "Vertical axis label", show_ticks: "Show axis ticks", expression: "Function expression", none: "None", altitude: "Altitude", median: "Median", bisector: "Angle bisector",
  },
};
