import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "wsm.title.new": "新建学习区",
    "wsm.title.edit": "学习区设置",
    "wsm.name.label": "名称",
    "wsm.name.placeholder": "例如：高三物理一轮复习",
    "wsm.sources": "资料来源（教材）",
    "wsm.sources.desc": "勾选教材后，本学习区内的对话会优先检索这些教材作答；未勾选的教材随时可再调整。普通文件不参与对话检索。",
    "wsm.exclusive.badge": "专属",
    "wsm.exclusive.auto": "创建后将自动生成「%s」专属资料夹，工作区内上传的资料都会放入其中。",
    "wsm.upload": "上传资料到此",
    "wsm.uploading": "上传中…",
    "wsm.upload.failed": "上传失败，请重试",
    "wsm.unfiled": "未归档",
    "wsm.textbooks": "教材",
    "wsm.textbooks.public": "公用教材库",
    "wsm.textbooks.mine": "我的教材",
    "wsm.empty.library": "还没有可选教材。请到「资料中心 → 教材库」上传教材，构建完成后即可选入。",
    "wsm.create": "创建学习区",
    "wsm.save": "保存设置",
    "wsm.saving": "保存中…",
    "wsm.cancel": "取消",
    "wsm.load.failed": "加载失败，请重试",
    "wsm.retry": "重试",
    "wsm.delete.file.title": "删除文件",
    "wsm.delete.file.desc": "将从资料库中彻底删除，所有选入它的学习区都无法再检索。",
    "wsm.confirm.delete": "删除",
    "wsm.download": "下载",
    "wsm.download.failed": "下载失败：原始文件未保留或已删除",
    "wsm.upload.formats": "支持 PDF / DOCX / PPTX / TXT / MD，单个 ≤256MB",
    "wsm.files.unit": "个文件",
    "wsm.name.required": "请填写学习区名称",
  },
  en: {
    "wsm.title.new": "New workspace",
    "wsm.title.edit": "Workspace settings",
    "wsm.name.label": "Name",
    "wsm.name.placeholder": "e.g. Grade-12 Physics review",
    "wsm.sources": "Knowledge sources (textbooks)",
    "wsm.sources.desc": "Chats in this workspace answer with the checked textbooks first. Plain files no longer participate in retrieval.",
    "wsm.exclusive.badge": "Private",
    "wsm.exclusive.auto": "A private folder 「%s」 will be created automatically — files uploaded inside this workspace go there.",
    "wsm.upload": "Upload here",
    "wsm.uploading": "Uploading…",
    "wsm.upload.failed": "Upload failed, please retry",
    "wsm.unfiled": "Unfiled",
    "wsm.textbooks": "Textbooks",
    "wsm.textbooks.public": "Public library",
    "wsm.textbooks.mine": "My textbooks",
    "wsm.empty.library": "No textbooks available. Upload one in Resource Center → Textbooks first.",
    "wsm.create": "Create workspace",
    "wsm.save": "Save settings",
    "wsm.saving": "Saving…",
    "wsm.cancel": "Cancel",
    "wsm.load.failed": "Failed to load, please retry",
    "wsm.retry": "Retry",
    "wsm.delete.file.title": "Delete file",
    "wsm.delete.file.desc": "The file will be removed from the library. Every workspace that selected it loses access.",
    "wsm.confirm.delete": "Delete",
    "wsm.download": "Download",
    "wsm.download.failed": "Download failed: original not kept or deleted",
    "wsm.upload.formats": "PDF / DOCX / PPTX / TXT / MD, up to 256MB each",
    "wsm.files.unit": "files",
    "wsm.name.required": "Please enter a workspace name",
  },
} satisfies PageStrings;
