// AUTO-GENERATED by scripts/dev/generate_assistant_types.py — DO NOT EDIT.
// Source of truth: services/api/app/schemas/assistant.py
// Regenerate with: python scripts/generate_assistant_types.py


export type AssistantRouteId = "home" | "chat" | "course" | "notes" | "dashboard" | "knowledge" | "orchestration" | "assessment" | "memory" | "resources_files" | "resources_textbooks" | "archive" | "profile" | "account" | "settings" | "insights" | "docs" | "admin" | "login" | "register";

export type LearningArchiveTab = "changes" | "sessions" | "concepts";

export interface ModuleTarget {
  kind?: "module";
  route_id: AssistantRouteId;
}

export interface WorkspaceChatTarget {
  kind?: "workspace_chat";
  workspace_id: string;
}

export interface ChatSessionTarget {
  kind?: "chat_session";
  session_id: string;
}

export interface WorkspaceCoursesTarget {
  kind?: "workspace_courses";
  workspace_id: string;
}

export interface LessonTarget {
  kind?: "lesson";
  workspace_id: string;
  lesson_id: string;
  view?: "overview" | "edit";
  revision?: number | null;
}

export interface ClassroomRunTarget {
  kind?: "classroom_run";
  workspace_id: string;
  lesson_id: string;
  run_id: string;
}

export interface NoteTarget {
  kind?: "note";
  note_id: string;
}

export interface LearningArchiveTarget {
  kind?: "learning_archive";
  workspace_id: string;
  tab?: LearningArchiveTab;
  concept_key?: string | null;
  source_id?: string | null;
}

export interface ConceptTarget {
  kind?: "concept";
  concept_id: string;
  workspace_id?: string | null;
}

export interface TaskTarget {
  kind?: "task";
  task_id: string;
}

export interface TeachingProposalTarget {
  kind?: "teaching_proposal";
  proposal_id: string;
}

export type DashboardRange = "7d" | "30d" | "this_week";

export interface DashboardViewTarget {
  kind?: "dashboard_view";
  workspace_id?: string | null;
  range?: DashboardRange;
}

export interface ChatMessageTarget {
  kind?: "chat_message";
  session_id: string;
  message_id: string;
}

export interface FileTarget {
  kind?: "file";
  file_id: string;
  folder_id?: string | null;
  page?: number | null;
}

export interface FileFolderTarget {
  kind?: "file_folder";
  folder_id: string;
}

export interface TextbookTarget {
  kind?: "textbook";
  textbook_id: string;
  volume_id?: string | null;
  chapter_id?: string | null;
}

export type AssessmentViewKind = "start" | "active" | "report" | "errors" | "recent";

export interface AssessmentViewTarget {
  kind?: "assessment_view";
  view?: AssessmentViewKind;
  assessment_id?: string | null;
  source_id?: string | null;
  question_id?: string | null;
}

export interface GoalTarget {
  kind?: "goal";
  goal_id: string;
}

export interface WeekTaskTarget {
  kind?: "week_task";
  week_index: number;
  week_task_id: string;
  subtask_id?: string | null;
}

export interface MemoryPreferencesTarget {
  kind?: "memory_preferences";
}

export interface NoteRevisionTarget {
  kind?: "note_revision";
  note_id: string;
  revision: number;
}

export type ArchiveResourceType = "session" | "library_file" | "library_folder" | "textbook" | "textbook_volume" | "workspace" | "knowledge_graph" | "notes_note" | "classroom_lesson";

export interface ArchiveItemTarget {
  kind?: "archive_item";
  item_id: string;
  resource_type: ArchiveResourceType;
}

export type ProfileSectionKind = "account" | "learning" | "voice" | "assistant";

export interface ProfileSectionTarget {
  kind?: "profile_section";
  section?: ProfileSectionKind;
}

export type SettingsSectionKind = "general" | "learning" | "voice" | "assistant" | "processing" | "account" | "about";

export interface SettingsSectionTarget {
  kind?: "settings_section";
  section?: SettingsSectionKind;
}

export interface TeachingGuidanceTarget {
  kind?: "teaching_guidance";
  guidance_id: string;
}

export interface DocsSectionTarget {
  kind?: "docs_section";
  section_id: string;
}

export type AdminSectionKind = "users" | "orphan_data" | "classroom_health" | "ocr" | "textbook_pipeline" | "llm" | "learner_evaluation" | "prompt_memory";

export interface AdminSectionTarget {
  kind?: "admin_section";
  section: AdminSectionKind;
}

export interface FollowPageScope {
  mode?: "follow_page";
}

export interface WorkspaceScope {
  mode?: "workspace";
  workspace_id: string;
}

export interface AllWorkspacesScope {
  mode?: "all_workspaces";
}

export interface ResolvedScope {
  mode: "public" | "workspace" | "all_workspaces" | "account";
  workspace_ids?: Array<string>;
  scope_revisions?: Record<string, string>;
}

export interface PageContextEntity {
  kind: "chat" | "lesson" | "run" | "note" | "concept" | "task";
  id: string;
  parent_id?: string | null;
  revision?: string | null;
}

export interface PageContextSelection {
  text: string;
  label: string;
}

export interface PageContext {
  schema_version?: 1;
  route_id: AssistantRouteId;
  route_epoch: number;
  workspace_id?: string | null;
  entity?: PageContextEntity | null;
  view?: string | null;
  selection?: PageContextSelection | null;
}

export interface TimeWindow {
  start_at: string;
  end_at: string;
  timezone: string;
  label: string;
}

export interface AssistantSource {
  source_id: string;
  kind: "learning_evidence" | "concept_evaluation" | "teaching_report" | "teaching_proposal" | "task" | "lesson" | "product_help" | "site_search";
  title: string;
  workspace_id?: string | null;
  observed_at?: string | null;
  retrieved_at: string;
  revision?: string | null;
  locator: ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget;
  availability?: "available" | "archived" | "removed" | "unavailable";
}

export interface AssistantNotice {
  code: string;
  message: string;
}

export interface MetricItem {
  key: "answer_attempt_count" | "graded_answer_count" | "pending_answer_count" | "recorded_learning_days" | "completed_task_count" | "observed_concept_count" | "course_position" | "learning_duration_minutes";
  label: string;
  value?: number | null;
  unit?: string;
  source_ids?: Array<string>;
  completeness?: "complete" | "partial" | "unavailable";
  known_minimum?: number | null;
  unavailable_reason?: string | null;
}

export interface EvaluationStatement {
  text: string;
  status?: string | null;
  scope_note?: string | null;
  source_ids?: Array<string>;
}

export interface PendingCounts {
  evaluation_pending?: number;
  active_reviews?: number;
  failed_jobs?: number;
}

export interface WorkspaceCoverage {
  observed_concepts?: number | null;
  coverage_note?: string | null;
}

export interface WorkspaceSummary {
  workspace_id: string;
  workspace_name: string;
  scope_revision?: string;
  evidence_watermark?: string;
  evaluation_status?: string;
  coverage?: WorkspaceCoverage;
  statements?: Array<EvaluationStatement>;
  pending_counts?: PendingCounts;
  source_ids?: Array<string>;
}

export interface UnscopedActivity {
  included?: boolean;
  summary?: string;
  recorded_learning_days?: number | null;
  source_ids?: Array<string>;
}

export interface NextStep {
  title: string;
  rationale: string;
  source_ids?: Array<string>;
  action_id?: string | null;
}

export interface LearningReport {
  window: TimeWindow;
  scope: ResolvedScope;
  facts?: Array<MetricItem>;
  workspace_summaries?: Array<WorkspaceSummary>;
  unscoped_activity?: UnscopedActivity;
  next_steps?: Array<NextStep>;
  generated_at: string;
  complete?: boolean;
  display_truncated?: boolean;
  notices?: Array<AssistantNotice>;
}

export interface FailureCount {
  category: string;
  count: number;
  label?: string | null;
}

export interface StrategyStat {
  name: string;
  label?: string | null;
  attempts: number;
  successes: number;
}

export interface ProposalSummary {
  proposal_id: string;
  title?: string | null;
  status: "proposed" | "approved" | "applied" | "rejected";
  summary?: string | null;
}

export interface GuidanceSummary {
  guidance_id: string;
  title?: string | null;
  impact_turns?: number;
  applied_at?: string | null;
}

export interface TeachingCoverage {
  complete?: boolean;
  inspected_count?: number;
  invalid_count?: number;
  earliest_available_at?: string | null;
}

export interface TeachingReport {
  window: TimeWindow;
  scope: ResolvedScope;
  total_turns?: number;
  failure_distribution?: Array<FailureCount>;
  top_strategies?: Array<StrategyStat>;
  proposals?: Array<ProposalSummary>;
  active_guidance?: Array<GuidanceSummary>;
  pending_proposals?: number;
  coverage?: TeachingCoverage;
  generated_at: string;
  source_ids?: Array<string>;
  notices?: Array<AssistantNotice>;
}

export interface NavigatePayload {
  kind?: "navigate";
  target: ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget;
}

export interface OpenWorkspaceFormPayload {
  kind?: "open_workspace_form";
  workspace_id?: string | "new";
}

export interface PrepareLessonDraft {
  topic: string;
  objectives?: string | null;
  duration_minutes?: 5 | 10 | 15 | 20 | 30 | null;
}

export interface PrepareLessonPayload {
  kind?: "prepare_lesson";
  workspace_id: string;
  draft: PrepareLessonDraft;
}

export interface ResumeLessonPayload {
  kind?: "resume_lesson";
  workspace_id: string;
  lesson_id: string;
  lesson_revision: number;
  run_id?: string | null;
}

export interface LaunchTaskPayload {
  kind?: "launch_task";
  task_id: string;
}

export interface HandoffChatPayload {
  kind?: "handoff_chat";
  workspace_id?: string | null;
  draft_id: string;
}

export interface HandoffNotePayload {
  kind?: "handoff_note";
  draft_id: string;
}

export interface OpenClassroomQuestionPayload {
  kind?: "open_classroom_question";
  workspace_id: string;
  lesson_id: string;
  run_id: string;
  question: string;
}

export interface SetLocalPreferencePayload {
  kind?: "set_local_preference";
  key: "theme" | "font_scale" | "lang";
  value: string;
}

export interface StartWorkflowPayload {
  kind?: "start_workflow";
  template: "setup_learning_space" | "weekly_review_to_plan" | "weak_point_to_practice" | "material_to_course" | "organize_materials" | "continue_learning_session";
  objective: string;
  scope?: Record<string, unknown>;
  selection_ids?: Record<string, Array<string>>;
}

export interface SubscriptionSubscribeInput {
  kind: "weekly_brief" | "daily_tasks" | "due_reviews" | "unfinished_course";
  local_time?: string;
  timezone?: string;
}

export interface ManageSubscriptionPayload {
  kind?: "manage_subscription";
  operation: "subscribe";
  input: SubscriptionSubscribeInput;
}

export interface TaskCreateInput {
  title: string;
  day?: string;
  estimate_minutes?: number | null;
  workspace_id?: string | null;
}

export interface TaskCompleteInput {
  task_id: string;
  expected_status?: "pending" | "in_progress" | "overdue";
}

export interface NoteCreateInput {
  title?: string;
  content: string;
  folder_id?: string | null;
  tags?: Array<string>;
}

export interface ChatRenameInput {
  session_id: string;
  title: string;
}

export interface ScheduleUpdateInput {
  daily_minutes: number;
}

export interface WorkspaceCreateInput {
  name: string;
  file_ids?: Array<string>;
}

export interface WorkspaceUpdateSourcesInput {
  workspace_id: string;
  add_file_ids?: Array<string>;
  remove_file_ids?: Array<string>;
}

export interface ChatMoveWorkspaceInput {
  session_id: string;
  workspace_id: string;
}

export interface ChatArchiveInput {
  session_id: string;
}

export interface LibraryCreateFolderInput {
  name: string;
}

export interface LibraryRenameFileInput {
  file_id: string;
  filename: string;
}

export interface LibraryMoveFileInput {
  file_id: string;
  folder_id?: string;
}

export interface TextbookCancelInput {
  textbook_id: string;
}

export interface TextbookRebuildInput {
  textbook_id: string;
  mode?: "rag_graph" | "full_ocr" | "graph_only";
}

export interface ArchiveRestoreInput {
  item_id: string;
  workspace_ids?: Array<string>;
}

export interface DomainWritePayload {
  kind?: "domain_write";
  operation: "workspace.create" | "workspace.update_sources" | "chat.rename" | "chat.move_workspace" | "chat.archive" | "note.create" | "note.append" | "note.replace" | "note.move" | "note.set_review" | "note.restore_revision" | "goal.create" | "goal.update" | "plan.regenerate" | "task.create" | "task.update" | "task.complete" | "subtask.create" | "schedule.update" | "assessment.start" | "assessment.practice" | "evaluation.request_review" | "evaluation.retry" | "evaluation.synthesize" | "memory.set_window" | "library.create_folder" | "library.rename_file" | "library.move_file" | "textbook.cancel" | "textbook.rebuild" | "archive.restore" | "profile.update" | "assistant.preferences" | "teaching.approve" | "teaching.apply" | "teaching.revoke" | "lesson.generate" | "lesson.retry" | "lesson.cancel" | "lesson.export";
  input: TaskCreateInput | TaskCompleteInput | NoteCreateInput | ChatRenameInput | ScheduleUpdateInput | WorkspaceCreateInput | WorkspaceUpdateSourcesInput | ChatMoveWorkspaceInput | ChatArchiveInput | LibraryCreateFolderInput | LibraryRenameFileInput | LibraryMoveFileInput | TextbookCancelInput | TextbookRebuildInput | ArchiveRestoreInput | NoteAppendInput | NoteReplaceInput | NoteMoveInput | NoteSetReviewInput | NoteRestoreRevisionInput | GoalCreateInput | GoalUpdateInput | PlanRegenerateInput | TaskUpdateInput | SubtaskCreateInput | AssessmentStartInput | AssessmentPracticeInput | EvaluationRequestReviewInput | EvaluationRetryInput | EvaluationSynthesizeInput | TeachingApproveInput | TeachingApplyInput | TeachingRevokeInput | MemorySetWindowInput | ProfileUpdateInput | AssistantPreferencesInput | LessonGenerateInput | LessonJobInput | LessonExportInput;
  expected_revision?: string | null;
  preview_id?: string;
}

export interface NoteAppendInput {
  note_id: string;
  base_revision: number;
  append_markdown: string;
}

export interface NoteReplaceInput {
  note_id: string;
  base_revision: number;
  title?: string;
  content: string;
  summary?: string;
}

export interface NoteMoveInput {
  note_ids: Array<string>;
  folder_id?: string;
}

export interface NoteSetReviewInput {
  note_id: string;
  enabled: boolean;
}

export interface NoteRestoreRevisionInput {
  note_id: string;
  revision: number;
  expected_current_revision: number;
}

export interface GoalCreateInput {
  title: string;
  description?: string;
  goal_type?: "ability" | "exam" | "interest";
  subjects?: Array<string>;
  target_concept_ids?: Array<string>;
  workspace_id?: string;
  deadline?: number;
}

export interface GoalUpdateInput {
  goal_id: string;
  title?: string | null;
  description?: string | null;
  goal_type?: "ability" | "exam" | "interest" | null;
  subjects?: Array<string> | null;
  target_concept_ids?: Array<string> | null;
  workspace_id?: string | null;
  deadline?: number | null;
}

export interface PlanRegenerateInput {
  expected_plan_revision: string;
  explicit_goal_ids?: Array<string>;
  num_weeks?: number;
}

export interface TaskUpdateInput {
  task_id: string;
  title?: string | null;
  day?: string | null;
  kind?: string | null;
  phase?: string | null;
  estimate_minutes?: number | null;
  priority?: number | null;
  milestone_id?: string | null;
}

export interface SubtaskCreateInput {
  week_index: number;
  week_task_id: string;
  title: string;
  estimate_minutes?: number;
}

export interface AssessmentStartInput {
  workspace_id?: string;
  concept_keys: Array<string>;
  count?: number;
  q_type?: string;
  grade?: string;
  subject?: string;
  expected_scope_revision?: string;
}

export interface AssessmentPracticeInput {
  question_id: string;
  question_revision: number;
  mode: "same" | "variant";
  expected_scope_revision?: string;
}

export interface EvaluationRequestReviewInput {
  source_id: string;
  interpretation_id: string;
  reason: string;
  issue_kind?: string;
  expected_revision: number;
}

export interface EvaluationRetryInput {
  job_id: string;
}

export interface EvaluationSynthesizeInput {
  workspace_id: string;
  expected_scope_revision?: string;
}

export interface TeachingApproveInput {
  proposal_id: string;
  expected_status?: "proposed" | "approved" | "rejected" | "applied";
}

export interface TeachingApplyInput {
  proposal_id: string;
  expected_status?: "approved" | "applied";
}

export interface TeachingRevokeInput {
  guidance_id: string;
  expected_active?: true;
}

export interface MemorySetWindowInput {
  window: number;
}

export interface SetLocalPreferencePayload {
  kind?: "set_local_preference";
  key: "theme" | "font_scale" | "lang";
  value: string;
}

export interface ProfileUpdateInput {
  name?: string | null;
  grade?: string | null;
  school?: string | null;
  subjects?: Array<string> | null;
}

export interface AssistantPreferencesInput {
  response_length?: "short" | "standard" | "detailed" | null;
  tone?: "neutral" | "encouraging" | null;
  default_scope?: "follow_page" | "all_workspaces" | null;
  proactive_enabled?: boolean | null;
  voice_input_mode?: "hold" | "toggle" | null;
  send_after_recording?: boolean | null;
  auto_read?: boolean | null;
  voice_policy?: "auto" | "cloud" | "local" | "silent" | null;
  voice_id?: string | null;
  allow_local_fallback?: boolean | null;
  playback_rate?: 0.75 | 1 | 1.25 | 1.5 | null;
  volume?: number | null;
  base_revision?: number | null;
}

export interface LessonGenerateInput {
  workspace_id: string;
  topic: string;
  goals?: Array<string>;
  duration_minutes?: 5 | 10 | 15 | 20 | 30;
  start_mode?: "automatic" | "outline_first";
  source_file_ids?: Array<string>;
  grade?: string;
  language?: "zh" | "en";
}

export interface LessonJobInput {
  workspace_id: string;
  lesson_id: string;
  job_id: string;
  expected_state_revision: number;
}

export interface LessonExportInput {
  workspace_id: string;
  lesson_id: string;
  revision: number;
  fmt?: "html_zip" | "notes_md";
}

export interface PreviewChange {
  field: string;
  label: string;
  before?: string | null;
  after?: string | null;
}

export interface ActionPreview {
  preview_id: string;
  action_id: string;
  title: string;
  summary: string;
  affected_entities?: Array<ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget>;
  changes?: Array<PreviewChange>;
  side_effects?: Array<string>;
  reversible?: boolean;
  parameter_hash: string;
  source_revisions?: Record<string, string>;
  expires_at: string;
  approval: "intent_sufficient" | "review_required" | "original_page_required";
  candidate_id?: string | null;
}

export interface ActionApproveRequest {
  preview_id: string;
  parameter_hash: string;
  decision: "approve" | "reject";
}

export interface ActionApproveResponse {
  approval_id: string;
  decision: "approve" | "reject";
  expires_at: string;
}

export interface ActionUndoRequest {
  client_request_id: string;
  expected_result_revision: string;
}

export interface ActionUndoResponse {
  action: AssistantAction;
  undone: boolean;
  reason?: string | null;
}

export interface BusinessUndoSnapshot {
  task_id?: string | null;
  day?: string | null;
  title?: string | null;
  note_id?: string | null;
  content_sha?: string | null;
  session_id?: string | null;
  previous_title?: string | null;
  previous_minutes?: number | null;
  workspace_id?: string | null;
  selected_file_ids?: Array<string>;
  added?: Array<string>;
  removed?: Array<string>;
  result_updated_at?: string | null;
  previous_workspace_id?: string | null;
  trash_item?: string | null;
  folder_id?: string | null;
  previous_filename?: string | null;
  file_id?: string | null;
  previous_folder_id?: string | null;
  resource_type?: string | null;
  original_id?: string | null;
  base_revision?: number | null;
  result_revision?: number | null;
  moves?: Array<Record<string, string>>;
  previous_enabled?: boolean | null;
  restored_from_current?: number | null;
  previous?: Record<string, string> | null;
  applied?: Record<string, string> | null;
  week_index?: number | null;
  week_task_id?: string | null;
  subtask_id?: string | null;
}

export interface BusinessResult {
  kind?: "none" | "classroom_run" | "task_launch" | "draft" | "note" | "task" | "chat" | "workspace" | "library_folder" | "library_file" | "trash_item" | "textbook" | "textbook_job" | "restore" | "goal" | "assessment" | "evaluation_job" | "teaching_proposal" | "profile" | "classroom_job" | "classroom_export" | "workflow" | "subscription";
  entity_id?: string | null;
  related_ids?: Record<string, string>;
  result_revision?: string | null;
  idempotent_reuse?: boolean;
  undo?: BusinessUndoSnapshot | null;
}

export interface ActionUndoResult {
  client_request_id: string;
  undone_at: string;
  message: string;
}

export interface ActionClientResult {
  status: "succeeded" | "failed" | "cancelled";
  code?: string | null;
  detail?: string | null;
}

export interface AssistantAction {
  action_id: string;
  conversation_id: string;
  turn_id: string;
  label: string;
  payload: NavigatePayload | OpenWorkspaceFormPayload | PrepareLessonPayload | ResumeLessonPayload | LaunchTaskPayload | HandoffChatPayload | HandoffNotePayload | OpenClassroomQuestionPayload | SetLocalPreferencePayload | StartWorkflowPayload | DomainWritePayload;
  execution?: "automatic" | "user_click";
  state?: "proposed" | "executing" | "awaiting_ack" | "succeeded" | "failed" | "cancelled" | "expired" | "needs_attention";
  undo_result?: ActionUndoResult | null;
  created_at: string;
  expires_at: string;
  business_result?: BusinessResult | null;
  client_result?: ActionClientResult | null;
  return_target?: ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget | null;
}

export interface NavigateCommand {
  kind?: "navigate";
  target: ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget;
}

export interface WorkspaceFormCommand {
  kind?: "workspace_form";
  workspace_id?: string | "new";
}

export interface LessonFormCommand {
  kind?: "lesson_form";
  workspace_id: string;
  draft_id: string;
}

export interface ChatDraftCommand {
  kind?: "chat_draft";
  draft_id: string;
}

export interface NoteDraftCommand {
  kind?: "note_draft";
  draft_id: string;
}

export interface ClassroomQuestionCommand {
  kind?: "classroom_question";
  workspace_id: string;
  lesson_id: string;
  run_id: string;
  draft_id: string;
}

export interface PageCommandResult {
  status: "succeeded" | "failed" | "cancelled";
  code?: "entity_not_found" | "draft_expired" | "user_stayed" | "page_not_ready" | "capability_disabled" | "save_failed" | null;
}

export interface ActionExecuteRequest {
  invocation_id: string;
  client_instance_id: string;
  route_epoch: number;
  approval_id?: string | null;
}

export interface ActionExecutionResponse {
  action: AssistantAction;
  conversation_revision: number;
  business_result: BusinessResult;
  command?: NavigateCommand | WorkspaceFormCommand | LessonFormCommand | ChatDraftCommand | NoteDraftCommand | ClassroomQuestionCommand | null;
  command_id?: string | null;
  ack_token?: string | null;
  command_expires_at?: string | null;
  retryable?: boolean;
  ready_to_deliver?: boolean;
}

export interface ActionAckRequest {
  command_id: string;
  ack_token: string;
  result: "succeeded" | "failed" | "cancelled";
  error_code?: "entity_not_found" | "draft_expired" | "user_stayed" | "page_not_ready" | "capability_disabled" | "save_failed" | null;
}

export interface LessonPrefill {
  kind?: "lesson";
  workspace_id: string;
  topic: string;
  objectives?: string | null;
  duration_minutes?: number | null;
}

export interface ChatPrefill {
  kind?: "chat";
  workspace_id?: string | null;
  session_id?: string | null;
  text: string;
}

export interface NotePrefill {
  kind?: "note";
  title: string;
  markdown: string;
  folder_id?: string | null;
}

export interface ClassroomQuestionPrefill {
  kind?: "classroom_question";
  workspace_id: string;
  lesson_id: string;
  run_id: string;
  question: string;
}

export interface DraftResultEntity {
  kind: "lesson" | "chat" | "note" | "classroom_question";
  id: string;
}

export interface AssistantDraft {
  draft_id: string;
  conversation_id: string;
  action_id: string;
  prefill: LessonPrefill | ChatPrefill | NotePrefill | ClassroomQuestionPrefill;
  source_ids?: Array<string>;
  created_at: string;
  expires_at: string;
  consumed?: boolean;
  result_entity?: DraftResultEntity | null;
}

export interface MarkdownBlock {
  block_id: string;
  type?: "markdown";
  text: string;
}

export interface MetricsBlock {
  block_id: string;
  type?: "metrics";
  items: Array<MetricItem>;
}

export interface LearningReportBlock {
  block_id: string;
  type?: "learning_report";
  report: LearningReport;
}

export interface TeachingReportBlock {
  block_id: string;
  type?: "teaching_report";
  report: TeachingReport;
}

export interface ActionsBlock {
  block_id: string;
  type?: "actions";
  items: Array<AssistantAction>;
}

export interface ChoiceOption {
  option_id: string;
  label: string;
  description?: string | null;
}

export interface ChoicesBlock {
  block_id: string;
  type?: "choices";
  prompt: string;
  options: Array<ChoiceOption>;
}

export interface NoticeBlock {
  block_id: string;
  type?: "notice";
  tone: "info" | "warning" | "error";
  code: string;
  text: string;
}

export interface AssistantMessage {
  message_id: string;
  seq: number;
  role: "user" | "assistant";
  created_at: string;
  turn_id: string;
  status: "streaming" | "complete" | "cancelled" | "failed" | "interrupted";
  scope: ResolvedScope;
  blocks?: Array<MarkdownBlock | MetricsBlock | LearningReportBlock | TeachingReportBlock | ActionsBlock | ChoicesBlock | NoticeBlock>;
  sources?: Array<AssistantSource>;
}

export interface TurnChoice {
  block_id: string;
  option_id: string;
}

export interface AssistantTurnRequest {
  schema_version?: 1;
  client_message_id: string;
  expected_conversation_revision: number;
  text: string;
  lang?: "zh" | "en";
  timezone: string;
  scope: FollowPageScope | WorkspaceScope | AllWorkspacesScope;
  page_context: PageContext;
  choice?: TurnChoice | null;
}

export interface AssistantError {
  code: string;
  message: string;
  retryable?: boolean;
  request_id?: string;
}

export interface TurnSnapshot {
  schema_version?: 1;
  turn_id: string;
  conversation_id: string;
  conversation_revision: number;
  client_message_id: string;
  state: "running" | "completed" | "cancelled" | "failed" | "interrupted";
  cancel_requested?: boolean;
  created_at: string;
  updated_at: string;
  last_event_seq?: number;
  user_message: AssistantMessage;
  assistant_message: AssistantMessage;
  actions?: Array<AssistantAction>;
  error?: AssistantError | null;
}

export interface TurnAcceptedResponse {
  turn_id: string;
  conversation_id: string;
  conversation_revision: number;
  state: "running" | "completed" | "cancelled" | "failed" | "interrupted";
  events_path: string;
  duplicate?: boolean;
}

export interface TurnCancelRequest {
  client_request_id: string;
}

export interface TurnCancelResponse {
  turn_id: string;
  state: "running" | "completed" | "cancelled" | "failed" | "interrupted";
  cancel_requested: boolean;
}

export interface SnapshotSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "snapshot";
  snapshot: TurnSnapshot;
  last_event_seq: number;
}

export interface StatusSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "status";
  stage: "understanding" | "reading" | "composing";
  label: string;
}

export interface TextDeltaSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "text_delta";
  message_id: string;
  block_id: string;
  delta: string;
}

export interface BlockUpsertSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "block_upsert";
  message_id: string;
  block: MarkdownBlock | MetricsBlock | LearningReportBlock | TeachingReportBlock | ActionsBlock | ChoicesBlock | NoticeBlock;
}

export interface MessageDoneSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "message_done";
  message: AssistantMessage;
}

export interface TurnDoneSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "turn_done";
  state: "running" | "completed" | "cancelled" | "failed" | "interrupted";
  conversation_revision: number;
}

export interface ErrorSseEvent {
  schema_version?: 1;
  turn_id: string;
  event_seq: number;
  emitted_at: string;
  event?: "error";
  error: AssistantError;
}

export interface ConversationCreateRequest {
  client_request_id: string;
  title?: string | null;
}

export interface ConversationCreated {
  conversation_id: string;
  revision: number;
  created_at: string;
}

export interface ConversationSummary {
  conversation_id: string;
  title: string;
  revision: number;
  created_at: string;
  updated_at: string;
}

export interface ConversationListResponse {
  items?: Array<ConversationSummary>;
  total: number;
  offset?: number;
  limit?: number;
}

export interface ActiveTurnInfo {
  turn_id: string;
  state: "running" | "completed" | "cancelled" | "failed" | "interrupted";
  created_at: string;
}

export interface ConversationDetailResponse {
  conversation_id: string;
  title: string;
  revision: number;
  created_at: string;
  updated_at: string;
  messages?: Array<AssistantMessage>;
  has_more?: boolean;
  active_turn?: ActiveTurnInfo | null;
}

export interface ModuleCapability {
  route_id: AssistantRouteId;
  available: boolean;
  disabled_reason?: string | null;
}

export interface AssistantCapabilities {
  schema_version?: 1;
  enabled: boolean;
  catalog_version: string;
  identity_mode: "guest" | "authenticated";
  conversation_enabled: boolean;
  model_available: boolean;
  modules?: Array<ModuleCapability>;
  tools?: Array<string>;
  action_kinds?: Array<string>;
  disabled_reasons?: Record<string, string>;
}

export interface GuideHistoryItem {
  role: "user" | "assistant";
  text: string;
}

export interface GuideRequest {
  schema_version?: 1;
  question: string;
  lang?: "zh" | "en";
  route_id?: AssistantRouteId | null;
  history?: Array<GuideHistoryItem>;
}

export interface GuideModuleEntry {
  route_id: AssistantRouteId;
  title: string;
  description: string;
}

export interface GuideResponse {
  schema_version?: 1;
  text: string;
  module_entries?: Array<GuideModuleEntry>;
  followups?: Array<string>;
}

export type AssistantErrorCode = "authentication_required" | "entity_not_found" | "conversation_not_found" | "conversation_changed" | "conversation_busy" | "conversation_full" | "scope_changed" | "revision_conflict" | "idempotency_conflict" | "action_in_progress" | "action_expired" | "draft_expired" | "target_changed" | "draft_already_consumed" | "invalid_context" | "invalid_target" | "rate_limited" | "concurrency_limit" | "capability_disabled" | "model_unavailable" | "source_unavailable" | "storage_unavailable" | "preview_stale" | "internal_error";

export interface ErrorBody {
  code: AssistantErrorCode;
  message: string;
  retryable?: boolean;
  request_id?: string;
}

export interface ErrorResponse {
  error: ErrorBody;
}

export type NavigationTarget = ModuleTarget | WorkspaceChatTarget | ChatSessionTarget | WorkspaceCoursesTarget | LessonTarget | ClassroomRunTarget | NoteTarget | LearningArchiveTarget | ConceptTarget | TaskTarget | TeachingProposalTarget | DashboardViewTarget | ChatMessageTarget | FileTarget | FileFolderTarget | TextbookTarget | AssessmentViewTarget | GoalTarget | WeekTaskTarget | MemoryPreferencesTarget | NoteRevisionTarget | ArchiveItemTarget | ProfileSectionTarget | SettingsSectionTarget | TeachingGuidanceTarget | DocsSectionTarget | AdminSectionTarget;

export type ScopeSelection = FollowPageScope | WorkspaceScope | AllWorkspacesScope;

export type AssistantActionPayload = NavigatePayload | OpenWorkspaceFormPayload | PrepareLessonPayload | ResumeLessonPayload | LaunchTaskPayload | HandoffChatPayload | HandoffNotePayload | OpenClassroomQuestionPayload | SetLocalPreferencePayload | StartWorkflowPayload | SubscriptionSubscribeInput | ManageSubscriptionPayload | ManageSubscriptionPayload | DomainWritePayload;

export type PageCommand = NavigateCommand | WorkspaceFormCommand | LessonFormCommand | ChatDraftCommand | NoteDraftCommand | ClassroomQuestionCommand;

export type AssistantDraftPrefill = LessonPrefill | ChatPrefill | NotePrefill | ClassroomQuestionPrefill;

export type AssistantBlock = MarkdownBlock | MetricsBlock | LearningReportBlock | TeachingReportBlock | ActionsBlock | ChoicesBlock | NoticeBlock;

export type AssistantSseEvent = SnapshotSseEvent | StatusSseEvent | TextDeltaSseEvent | BlockUpsertSseEvent | MessageDoneSseEvent | TurnDoneSseEvent | ErrorSseEvent;
