import type { PageStrings } from "@/lib/i18n-page";

/** /profile 我的画像 页面词条（页面级，全局词典兜底）。 */
export const STRINGS = {
  zh: {
    "profile.title": "我的画像",
    "profile.desc": "系统从每次学习互动中自动派生的学术与交互画像",
    "profile.lastActive": "最近活跃",
    "profile.events": "个学习事件",
    "profile.never": "尚未开始",

    "account.desc": "M0 账户 · 学段修改会同步学术画像",
    "account.edit": "编辑",
    "account.save": "保存",
    "account.saving": "保存中…",
    "account.cancel": "取消",
    "account.save.failed": "保存失败，请重试",
    "account.name": "姓名",
    "account.grade": "学段",
    "account.school": "学校",
    "account.subjects": "学科",
    "account.subjects.hint": "逗号分隔",
    "account.danger": "危险区",
    "account.ocrParallel": "教材 OCR 并行加速",
    "account.ocrParallel.desc": "扫描版教材逐页 OCR 分批并发处理，大图谱构建明显更快；若视觉模型 API 限流报错可关闭。",
    "account.ocrParallel.failed": "设置失败，请重试",
    "account.ttsSpeed": "朗读语速",
    "account.ttsSpeed.desc": "语音通话中老师朗读回答的语速（50%–150%），调整后下次拨号生效。",
    "account.ttsSpeed.failed": "设置失败，请重试",
    "account.delete": "注销账号",
    "account.delete.title": "注销账号 — 此操作不可撤销",
    "account.delete.desc": "注销后你将立即退出登录，无法再访问该账号的学习档案与历史记录（学习数据按审计策略保留但不可访问）。此操作不可撤销。",
    "account.delete.password": "输入密码以确认身份",
    "account.delete.confirm.hint": "请输入「注销」以确认",
    "account.delete.phrase": "注销",
    "account.delete.submit": "永久注销",
    "account.delete.deleting": "注销中…",
    "account.delete.wrongPassword": "密码错误，注销未执行",
    "account.delete.failed": "注销失败，请重试",

    "m2.title": "学术画像",
    "m2.desc": "学科掌握、目标与学习风格 · 由 M2 学生模型维护",
    "m2.bloom": "认知层级薄弱项",
    "m2.bloom.note": "来自布鲁姆认知档案（按作答聚合）；测评与练习会持续更新。",
    "m2.style": "学习风格",
    "m2.preference": "讲解偏好",
    "m2.depth": "讲解深度",
    "m2.pref.step_by_step": "循序渐进",
    "m2.pref.examples_first": "示例先行",
    "m2.pref.balanced": "均衡",
    "m2.depth.basic": "基础简明",
    "m2.depth.deep": "深入剖析",
    "m2.depth.adaptive": "自适应",
    "m2.goals": "学习目标",
    "m2.goals.empty": "尚未设置长期目标",
    "m2.goals.set": "去学习编排设置",
    "m2.goal.chain": "目标链",
    "m2.goal.deadline": "截止",
    "m2.goal.gaps": "待补概念",
    "m2.goal.manage": "在编排中管理目标与计划",
    "m2.goal.type.exam": "备考",
    "m2.goal.type.ability": "能力提升",
    "m2.goal.type.interest": "兴趣学习",
    "m2.strong": "优势点",
    "m2.weak": "待加强",
    "m2.note": "画像由学习事件自动派生，非表单填写。",
    "m2.sources": "数据来源：M2 学习事件（掌握/优劣势）· M8 交互反馈推断（讲解风格）· M9 编排（目标镜像）· L1 布鲁姆档案（层级弱项）。",
    "m8.sources": "数据来源：M8 交互智能 —— 由对话交互事件实时推断，写侧仅此一处。",
    "moti.sources": "数据来源：五源学习活动按日聚合（作答 / 讲解 / 编排 / 交互 / 评估）。",
    "src.m8infer": "M8 反馈推断",
    "src.m9": "M9 编排",
    "src.m2": "M2 掌握事件",
    "src.m8": "M8 交互智能",
    "src.l1": "L1 档案",

    "m8.title": "交互画像",
    "m8.desc": "语气、节奏等互动偏好 · 由 M8 交互智能维护",
    "m8.feedback": "近期反馈",
    "m8.signals": "互动信号",
    "m8.empty": "还没有足够互动数据，多聊几句就能看到你的交互画像了。",

    "moti.title": "学习激励",
    "moti.desc": "连续学习记录与里程碑",
    "moti.streak": "连续学习",
    "moti.active": "累计活跃",
    "moti.days": "天",
    "moti.next": "下一个里程碑",
    "moti.achieved": "已达成",

    "about.title": "系统如何理解我",
    "about.body":
      "M2 学生模型拥有学术讲解偏好（单真相源），M8 交互智能只拥有语气、节奏等交互维度并只读投影 M2。画像随每次对话自动更新，无需手动填写。",

    "err.load": "加载失败，请稍后重试",
    "disabled.m2": "学术画像已被环境开关关闭，当前不可用。",
    "disabled.m8": "交互画像已被环境开关关闭，当前不可用。",
    "empty.profile": "还没有学术画像",
    "empty.profile.desc": "开始一次对话后，系统会自动为你建立学术画像。",
  },
  en: {
    "profile.title": "My Profile",
    "profile.desc": "Academic and interaction profiles derived automatically from every learning session",
    "profile.lastActive": "Last active",
    "profile.events": "learning events",
    "profile.never": "Not yet",

    "account.desc": "M0 account · grade changes sync to the academic profile",
    "account.edit": "Edit",
    "account.save": "Save",
    "account.saving": "Saving…",
    "account.cancel": "Cancel",
    "account.save.failed": "Save failed — please retry",
    "account.name": "Name",
    "account.grade": "Grade",
    "account.school": "School",
    "account.subjects": "Subjects",
    "account.subjects.hint": "comma separated",
    "account.danger": "Danger zone",
    "account.ocrParallel": "Parallel textbook OCR",
    "account.ocrParallel.desc": "Scanned textbook pages are OCR'd in concurrent batches, so large graph builds finish much faster. Turn this off if your vision API rate-limits.",
    "account.ocrParallel.failed": "Failed to save — please retry",
    "account.ttsSpeed": "Speech rate",
    "account.ttsSpeed.desc": "How fast the tutor reads answers aloud during voice calls (50%–150%). Applies on the next call.",
    "account.ttsSpeed.failed": "Failed to save — please retry",
    "account.delete": "Delete account",
    "account.delete.title": "Delete account — this cannot be undone",
    "account.delete.desc": "You will be signed out immediately and lose access to this account's learning profile and history (learning data is retained for audit but inaccessible). This cannot be undone.",
    "account.delete.password": "Enter your password to confirm identity",
    "account.delete.confirm.hint": "Type \"DELETE\" to confirm",
    "account.delete.phrase": "DELETE",
    "account.delete.submit": "Delete permanently",
    "account.delete.deleting": "Deleting…",
    "account.delete.wrongPassword": "Incorrect password — account NOT deleted",
    "account.delete.failed": "Deletion failed — please retry",

    "m2.title": "Academic Profile",
    "m2.desc": "Subjects, goals and learning style · maintained by the M2 student model",
    "m2.bloom": "Cognitive-level weaknesses",
    "m2.bloom.note": "From the Bloom cognitive profile (aggregated over answers); kept fresh by assessments and practice.",
    "m2.style": "Learning style",
    "m2.preference": "Explanation preference",
    "m2.depth": "Explanation depth",
    "m2.pref.step_by_step": "Step by step",
    "m2.pref.examples_first": "Examples first",
    "m2.pref.balanced": "Balanced",
    "m2.depth.basic": "Basic",
    "m2.depth.deep": "In-depth",
    "m2.depth.adaptive": "Adaptive",
    "m2.goals": "Learning goals",
    "m2.goals.empty": "No long-term goal set yet",
    "m2.goals.set": "Set one in Orchestration",
    "m2.goal.chain": "Goal chain",
    "m2.goal.deadline": "Due",
    "m2.goal.gaps": "concepts to close",
    "m2.goal.manage": "Manage goal & plan in Orchestration",
    "m2.goal.type.exam": "Exam prep",
    "m2.goal.type.ability": "Ability",
    "m2.goal.type.interest": "Interest",
    "m2.strong": "Strengths",
    "m2.weak": "To improve",
    "m2.note": "Derived automatically from learning events — not a form you fill in.",
    "m2.sources": "Sources: M2 learning events (mastery/strengths) · M8 feedback inference (explanation style) · M9 orchestration (goal mirror) · L1 Bloom profile (level weaknesses).",
    "m8.sources": "Source: M8 UX intelligence — inferred live from interaction events; this is its only writer.",
    "moti.sources": "Source: daily union of five learning-activity ledgers (answers / teaching / orchestration / interaction / evaluation).",
    "src.m8infer": "inferred from M8 feedback",
    "src.m9": "M9 orchestration",
    "src.m2": "M2 mastery events",
    "src.m8": "M8 UX intelligence",
    "src.l1": "L1 profile",

    "m8.title": "Interaction Profile",
    "m8.desc": "Tone, pacing and other interaction preferences · maintained by M8 UX intelligence",
    "m8.feedback": "Recent feedback",
    "m8.signals": "Engagement signals",
    "m8.empty": "Not enough interactions yet — chat a bit and your interaction profile will appear here.",

    "moti.title": "Motivation",
    "moti.desc": "Streak and milestones",
    "moti.streak": "Streak",
    "moti.active": "Active days",
    "moti.days": "days",
    "moti.next": "Next milestone",
    "moti.achieved": "Achieved",

    "about.title": "How the system understands me",
    "about.body":
      "The M2 student model owns academic explanation preferences (single source of truth); M8 UX intelligence owns only interaction dimensions like tone and pacing, projecting M2 read-only. Your profile updates automatically with every conversation — nothing to fill in.",

    "err.load": "Failed to load — please try again",
    "disabled.m2": "The academic profile is disabled by an environment switch.",
    "disabled.m8": "The interaction profile is disabled by an environment switch.",
    "empty.profile": "No academic profile yet",
    "empty.profile.desc": "Start a conversation and the system will build your academic profile automatically.",
  },
} satisfies PageStrings;
