import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    title: "工具助手", intro: "把教学创作工具放在一起，为备课、辅导和测评提供可复用的成果。",
    image: "V4 AI 生图", imageIntro: "在情景配图中生成栅格教学图，也可以引用素材库。", worksheet: "组卷出题编译器", worksheetIntro: "批量生成、逐题编辑并跨设备保存试卷，学生版与教师版分别导出。", worksheetChat: "批量出题", illustration: "情景配图", illustrationIntro: "描述想呈现的情景，生成 SVG 或 V4 栅格教学图，再通过对话逐轮优化。",
    open: "开始配图", illustrationHint: "支持多轮对话、素材引用与版本回溯。", openWorksheet: "开始组卷", worksheetStepSetup: "设定范围", worksheetStepGenerate: "批量生成", worksheetStepExport: "审阅导出", worksheetHint: "统一纸张版式，逐题调整后导出学生版或教师版。", library: "教学素材库", libraryIntro: "浏览、管理可复用素材，或上传自己的 SVG。",
    lab: "模拟实验室", labIntro: "用器材、试剂和可回溯规则理解化学现象。", openLab: "进入实验台",
    labFeatOps: "器材操作", labFeatObserve: "现象观测", labFeatReport: "报告回溯",
    labHint: "首个主题为化学：预测检验、观察记录与回放分叉均已可用。",
    workspace: "配图工作台", backToTools: "返回工具助手", newSession: "新建配图", sessions: "配图会话", noSessions: "还没有配图会话",
    loading: "加载中…", loadFailed: "配图会话加载失败，请重试。", retry: "重试", delete: "删除会话", close: "关闭",
    deleteTitle: "删除配图会话", deleteDesc: "将删除这个会话及其配图版本。", cancel: "取消",
    unnamed: "新配图", mode: "配图方式", v1: "自由绘制", v2: "素材组合", v3: "素材辅助创作", v4: "AI 栅格生图",
    v1Desc: "V1 根据你的描述直接绘图。", v2Desc: "V2 按素材的参数和关系组合图示。", v3Desc: "V3 参考素材改造、组合并补画所需元素。", v4Desc: "V4 由服务端配置的生图模型生成栅格配图，模型名称无需在界面选择。",
    materials: "选择素材", autoMaterials: "未选择素材时，模型会提出需求并自动检索素材。",
    selectedMaterials: "已选素材", clearMaterials: "清空素材", removeMaterial: "移除素材", materialCount: "已选 %n 项素材", maxMaterials: "最多选择 12 项素材。",
    pickerTitle: "选择配图参考素材", builtin: "内置素材", public: "公有素材", private: "我的素材", search: "搜索素材",
    searchPlaceholder: "搜索名称、说明或别名", subject: "学科", family: "素材类型", allSubjects: "全部学科", allFamilies: "全部类型",
    materialLoading: "正在加载素材…", materialFailed: "素材加载失败，请重试。", materialEmpty: "没有找到匹配素材，试试其他搜索词或筛选。",
    applyMaterials: "使用所选素材", detail: "查看详情", selected: "已选择", select: "选择", materialDescription: "素材说明", materialVersion: "素材版本",
    message: "配图需求", placeholder: "描述情景、主体、关系和标注；已有配图时，直接说你希望怎样改进…",
    send: "生成配图", improve: "继续优化", sending: "提交中…", working: "正在配图", ready: "配图已完成", failed: "本轮配图未完成",
    user: "你的需求", assistant: "配图助手", startTitle: "让想法变成清晰的教学图示", startDesc: "从一个具体情景开始。生成后继续说明需要调整的布局、文字或细节，每一轮都会保存新版本。",
    example: "画出一个烧杯和温度计，标注杯中的水与温度计的位置。", useExample: "试试这个情景",
    preview: "配图成果", noPreview: "生成的配图会显示在这里。", revision: "版本 %n", revisions: "历史版本", latest: "最新版本", viewRevision: "查看版本",
    refineLatest: "继续优化将以最新版本为基础。", download: "下载配图", preparing: "准备需求", retrieving: "检索素材", composing: "设计图面", rendering: "渲染图面", reviewing: "审核图示",
    useAsBase: "以此版本继续优化", usingAsBase: "当前优化基础", observeStopped: "任务观察暂时中断，服务器可能仍在配图。", resume: "重新连接任务", chooseBase: "可选择任意历史版本作为优化基础。",
    busy: "这个会话已有配图任务，请等待完成。", conflict: "会话版本已更新，已重新加载，请重试。", requestFailed: "配图请求失败，请重试。",
    materialMissing: "所选素材已不可用，请重新选择素材。", materialConflict: "所选素材版本已变化，请重新选择素材。", sourceMissing: "所选基础版本已不可用，请重新加载会话并选择版本。", disabled: "配图功能暂未开启。",
    demo: "静态演示暂不包含配图会话。登录实际部署后可生成配图并多轮优化。",
    automatic: "自动检索素材", manual: "所选素材", firstVersion: "创建第一版", basedOn: "基于版本 %n 优化", finished: "已保存为版本 %n",
  },
  en: {
    title: "Tool assistants", intro: "Reusable teaching tools for lesson preparation, tutoring and assessment.",
    image: "V4 AI image studio", imageIntro: "Generate raster teaching images inside the illustration workspace with server-configured models.", worksheet: "Worksheet compiler", worksheetIntro: "Batch-generate, edit and sync a paper, then export student or teacher versions.", worksheetChat: "Batch generation", illustration: "Scene illustration", illustrationIntro: "Describe a scene, create an SVG or V4 raster teaching image, then refine it through conversation.",
    open: "Create an illustration", illustrationHint: "Support multi-turn refinement, material references and version history.", openWorksheet: "Start a worksheet", worksheetStepSetup: "Set scope", worksheetStepGenerate: "Generate", worksheetStepExport: "Review & export", worksheetHint: "Use one clear paper layout, edit each item and export student or teacher versions.", library: "Teaching materials", libraryIntro: "Browse and manage reusable components, or upload your own SVG.",
    lab: "Simulation lab", labIntro: "Understand chemistry through equipment, reagents and replayable rules.", openLab: "Enter the bench",
    labFeatOps: "Hands-on equipment", labFeatObserve: "Observation", labFeatReport: "Report & replay",
    labHint: "First subject: chemistry. Prediction checks, observation logs and replay forks included.",
    workspace: "Illustration workspace", backToTools: "Back to tool assistants", newSession: "New illustration", sessions: "Illustration sessions", noSessions: "No illustration sessions yet",
    loading: "Loading…", loadFailed: "Could not load illustration sessions. Please retry.", retry: "Retry", delete: "Delete session", close: "Close",
    deleteTitle: "Delete illustration session", deleteDesc: "This deletes the session and its illustration versions.", cancel: "Cancel",
    unnamed: "New illustration", mode: "Illustration mode", v1: "Draw freely", v2: "Assemble materials", v3: "Asset-assisted creation", v4: "AI raster image",
    v1Desc: "V1 draws directly from your description.", v2Desc: "V2 assembles components using their parameters and relationships.", v3Desc: "V3 adapts and combines references, and draws missing elements.", v4Desc: "V4 uses the server-configured image model; the model name is not selected in the UI.",
    materials: "Choose materials", autoMaterials: "Without a selection, the model requests and searches for suitable materials automatically.",
    selectedMaterials: "Selected materials", clearMaterials: "Clear materials", removeMaterial: "Remove material", materialCount: "%n materials selected", maxMaterials: "Choose up to 12 materials.",
    pickerTitle: "Choose illustration reference materials", builtin: "Built-in", public: "Public materials", private: "My materials", search: "Search materials",
    searchPlaceholder: "Search names, descriptions or aliases", subject: "Subject", family: "Material type", allSubjects: "All subjects", allFamilies: "All types",
    materialLoading: "Loading materials…", materialFailed: "Could not load materials. Please retry.", materialEmpty: "No matching materials. Try another search or filter.",
    applyMaterials: "Use selected materials", detail: "View details", selected: "Selected", select: "Select", materialDescription: "Material description", materialVersion: "Material version",
    message: "Illustration request", placeholder: "Describe the scene, objects, relationships and labels; for an existing illustration, explain what to improve…",
    send: "Generate illustration", improve: "Refine illustration", sending: "Submitting…", working: "Creating illustration", ready: "Illustration complete", failed: "This illustration could not be completed",
    user: "Your request", assistant: "Illustration assistant", startTitle: "Turn ideas into clear teaching diagrams", startDesc: "Start with a concrete scene. Refine its layout, wording or details in follow-up messages. Every completed turn saves a new version.",
    example: "Draw a beaker and a thermometer, and label the water and the thermometer's position.", useExample: "Try this scene",
    preview: "Illustration result", noPreview: "Your illustration will appear here.", revision: "Version %n", revisions: "Version history", latest: "Latest version", viewRevision: "View version",
    refineLatest: "Further refinements use the latest version.", download: "Download image", preparing: "Preparing requirements", retrieving: "Finding materials", composing: "Composing diagram", rendering: "Rendering diagram", reviewing: "Reviewing illustration",
    useAsBase: "Refine from this version", usingAsBase: "Current refinement base", observeStopped: "Observation was interrupted. The server may still be creating your illustration.", resume: "Reconnect to task", chooseBase: "You can choose any saved version as the refinement base.",
    busy: "This session already has a running illustration. Please wait.", conflict: "The session has a newer version. It has been reloaded; please retry.", requestFailed: "Illustration request failed. Please retry.",
    materialMissing: "A selected material is unavailable. Please choose your materials again.", materialConflict: "A selected material has a different version. Please select it again.", sourceMissing: "The selected base version is unavailable. Reload the session and choose a version.", disabled: "Illustrations are currently disabled.",
    demo: "The static demo does not contain illustration sessions. Sign in to a live deployment to generate and refine illustrations.",
    automatic: "Automatic material search", manual: "Selected materials", firstVersion: "Creating the first version", basedOn: "Refining version %n", finished: "Saved as version %n",
  },
};
