#!/usr/bin/env python3
"""从 backend/app/schemas/classroom.py 生成前端课堂 DTO 类型。

plan.md A01：schema 是唯一事实源，`frontend/src/lib/types-classroom.generated.ts`
由本脚本确定性生成（手写行为类型放 types-classroom.ts），CI 用 `--check`
比较生成结果，防止两份 DTO 漂移。

用法：
  python scripts/generate_classroom_types.py          # 生成/覆盖
  python scripts/generate_classroom_types.py --check  # 只比较，不一致退出 1
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "frontend" / "src" / "lib" / "types-classroom.generated.ts"

_REF_RE = re.compile(r"^#/(?:definitions|\$defs)/(.+)$")

HEADER = (
    "// AUTO-GENERATED by scripts/generate_classroom_types.py — DO NOT EDIT.\n"
    "// Source of truth: backend/app/schemas/classroom.py (plan.md §10/§14)\n"
    "// Regenerate with: python scripts/generate_classroom_types.py\n"
)


def _ref_name(ref: str) -> str:
    m = _REF_RE.match(ref)
    if not m:
        raise ValueError(f"无法解析 $ref: {ref}")
    return m.group(1)


def _ts_type(prop: dict) -> str:
    if "$ref" in prop:
        return _ref_name(prop["$ref"])
    if "oneOf" in prop:
        return " | ".join(_ts_type(sub) for sub in prop["oneOf"])
    if "anyOf" in prop:
        parts: list[str] = []
        for sub in prop["anyOf"]:
            t = _ts_type(sub)
            if t not in parts:
                parts.append(t)
        return " | ".join(parts)
    if "enum" in prop:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in prop["enum"])
    if "const" in prop:
        return json.dumps(prop["const"], ensure_ascii=False)
    t = prop.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in prop:
            return "[" + ", ".join(_ts_type(p) for p in prop["prefixItems"]) + "]"
        item = prop.get("items", {})
        return f"Array<{_ts_type(item)}>"
    if t == "object" or "additionalProperties" in prop:
        ap = prop.get("additionalProperties", True)
        if isinstance(ap, dict):
            return f"Record<string, {_ts_type(ap)}>"
        return "Record<string, unknown>"
    return "unknown"


def _render_model(name: str, defn: dict) -> str:
    if "enum" in defn:
        values = " | ".join(json.dumps(v, ensure_ascii=False) for v in defn["enum"])
        return f"export type {name} = {values};"
    if "oneOf" in defn or "anyOf" in defn:
        return f"export type {name} = {_ts_type(defn)};"
    props = defn.get("properties", {})
    required = set(defn.get("required", []))
    lines = [f"export interface {name} {{"]
    for fname, fprop in props.items():
        opt = "" if fname in required else "?"
        lines.append(f"  {fname}{opt}: {_ts_type(fprop)};")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    sys.path.insert(0, str(ROOT / "backend"))
    import pydantic

    from app.schemas import classroom as sc

    models = []
    for model_name in sc.PUBLIC_TYPE_MODELS:
        model = getattr(sc, model_name, None)
        if model is None:
            raise ValueError(f"PUBLIC_TYPE_MODELS 引用了不存在的模型: {model_name}")
        models.append(model)
    namespace = pydantic.create_model(
        "_ClassroomTypeNamespace", **{m.__name__: (m, ...) for m in models})
    schema = namespace.model_json_schema(ref_template="#/definitions/{model}")
    defs = schema.get("$defs", {})

    blocks = [HEADER]
    for model in models:
        if model.__name__ not in defs:
            raise ValueError(f"模型 {model.__name__} 未出现在 JSON schema defs 中")
        blocks.append(_render_model(model.__name__, defs[model.__name__]))
    for alias, members in sc.PUBLIC_TYPE_UNIONS.items():
        missing = [m for m in members if m not in defs]
        if missing:
            raise ValueError(f"联合类型 {alias} 引用了未导出的模型: {missing}")
        blocks.append(f"export type {alias} = {' | '.join(members)};")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="只比较生成结果与现有文件，不写入")
    args = parser.parse_args()

    content = generate()
    if args.check:
        if not TARGET.exists():
            print(f"[typegen] 缺少生成文件: {TARGET}", file=sys.stderr)
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current != content:
            print(f"[typegen] 生成结果与 {TARGET} 不一致，请重新运行生成脚本",
                  file=sys.stderr)
            return 1
        print(f"[typegen] OK: {TARGET} 与 schema 一致")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"[typegen] 已生成 {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
