// /docs 使用文档页词条（全员读；管理员可页内编辑）。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "docs.editingLocale": "编辑 {lang} 版本",
    "docs.title": "使用手册",
    "docs.desc": "从一本教材到一次新的理解。找到适合你的入口，让学习自然地继续。",
    "docs.startMaterials": "准备材料",
    "docs.startMaterialsDesc": "选一本教材，建立学习的起点。",
    "docs.startChat": "问一个问题",
    "docs.startChatDesc": "从困惑出发，一步步理解。",
    "docs.startCourse": "开始一堂课",
    "docs.startCourseDesc": "把章节与主题变成连贯的课程。",
    "docs.toc": "本页导览",
    "docs.edit": "编辑",
    "docs.preview": "预览",
    "docs.source": "编辑源码",
    "docs.save": "保存",
    "docs.saving": "保存中…",
    "docs.cancel": "取消",
    "docs.saved": "已保存",
    "docs.loadFail": "文档加载失败，请稍后重试。",
    "docs.saveFail": "保存失败，请确认你是管理员后重试。",
    "docs.updated": "最后更新",
    "docs.updatedBy": "由",
    "docs.empty": "（文档为空）",
    "docs.ph": "在此输入 Markdown 文档内容…",
    "docs.tabManual": "使用手册",
    "docs.tabShow": "演示手册",
    "docs.showTitle": "Next Tutor Agent 项目展示",
    "deep.sectionMissing": "未找到该文档小节。",
  },
  en: {
    "docs.editingLocale": "Editing {lang} version",
    "docs.title": "User guide",
    "docs.desc": "From a textbook to a new understanding. Find your starting point and keep learning.",
    "docs.startMaterials": "Choose materials",
    "docs.startMaterialsDesc": "Start with a textbook of your own.",
    "docs.startChat": "Ask a question",
    "docs.startChatDesc": "Work toward understanding, step by step.",
    "docs.startCourse": "Start a lesson",
    "docs.startCourseDesc": "Turn a chapter or topic into a course.",
    "docs.toc": "On this page",
    "docs.edit": "Edit",
    "docs.preview": "Preview",
    "docs.source": "Edit source",
    "docs.save": "Save",
    "docs.saving": "Saving…",
    "docs.cancel": "Cancel",
    "docs.saved": "Saved",
    "docs.loadFail": "Failed to load the document — please retry.",
    "docs.saveFail": "Failed to save — confirm you are an admin and retry.",
    "docs.updated": "Last updated",
    "docs.updatedBy": "by",
    "docs.empty": "(empty document)",
    "docs.ph": "Type the Markdown document here…",
    "docs.tabManual": "Manual",
    "docs.tabShow": "Show Deck",
    "docs.showTitle": "Next Tutor Agent show deck",
    "deep.sectionMissing": "Docs section not found.",
  },
} satisfies PageStrings;
