// 学习助手面板文案（plan.md §3/§14.1，A06）。中英对照。
const zh = {
  errorPreview: "预览读取失败",
  errorAction: "操作失败，请重试",
  errorUndo: "撤销失败，请稍后重试",
  errorCapabilities: "能力查询失败",
  errorConversationCreate: "会话创建失败",
  errorConversationRead: "会话读取失败",
  errorSend: "发送失败，请稍后重试",
  errorAnswer: "回答失败",
  previewEmpty: "（空）",
  settingsLengthShort: "短",
  settingsLengthStandard: "标准",
  settingsLengthDetailed: "详细",
  settingsToneNeutral: "平实",
  settingsToneEncouraging: "鼓励",
  voiceStopRecording: "停止录入",
  voiceHold: "按住说话",
  voiceStopReading: "停止朗读",
  voiceReadLatest: "朗读最新回答",
  launcherTooltip: "学习助手 · Ctrl/Cmd+Shift+K",
  panelTitle: "学习助手",
  historyButton: "历史会话",
  expandButton: "放大",
  collapseButton: "收起",
  shrinkButton: "恢复标准尺寸",
  closeButton: "收起助手",
  scopeFollowPage: "跟随当前页面",
  scopeAllWorkspaces: "全部学习区",
  scopeWorkspace: "学习区",
  scopeSeparator: " / ",
  welcome: "我能帮你找功能、继续课程、回顾学习。",
  quickIntro: "这个网站能帮我做什么？",
  quickStart: "从哪里开始学习？",
  quickCourse: "打开备课上课",
  quickRecent: "最近学得怎么样？",
  inputPlaceholder: "问我功能、课程，或最近的学习情况……",
  quoteChip: "引用",
  quoteRemove: "移除引用",
  send: "发送",
  stop: "停止",
  stopped: "已停止",
  newContent: "新内容",
  connectionLost: "连接已中断，点击恢复",
  reconnecting: "正在重新连接……",
  historyTitle: "历史会话",
  historyEmpty: "还没有历史会话",
  historyBack: "返回对话",
  newConversation: "新对话",
  deleteConversation: "删除会话",
  deleteConfirm: "删除该会话？其中的动作与草稿将一并失效。",
  loadMore: "加载更早消息",
  noMore: "已经是全部消息了",
  unreadDot: "有新回复",
  running: "正在处理",
  needsLogin: "登录后即可使用学习助手",
  disabled: "学习助手当前未开放",
  modelUnavailable: "助手服务暂不可用，稍后再试",
  statusMap: {
    understanding: "正在理解你的问题",
    reading: "正在读取学习记录",
    composing: "正在组织回答",
  } as Record<string, string>,
  actionPrimary: "立即打开",
  previewViewChanges: "查看变更",
  previewLoading: "正在生成预览……",
  previewConfirm: "确认执行",
  previewReject: "取消",
  previewWorking: "正在处理……",
  previewReversible: "可撤销",
  previewNotReversible: "执行后不可自动撤销",
  previewTtl: "确认 10 分钟内有效",
  voiceReading: "朗读中…",
  previewExpired: "预览已过期",
  previewStaleHint: "预览已过期或参数已变化，请返回重新查看变更。",
  actionUndo: "撤销",
  actionUndoBusy: "正在撤销……",
  actionUndone: "已撤销",
  choicesPrompt: "请选择：",
  viewSources: (n: number) => `查看 ${n} 条依据`,
  metricsUnavailable: "暂无数据",
  knownMinimumPrefix: "至少记录到",
  noticeInfo: "提示",
  noticeWarning: "注意",
  noticeError: "出错了",
  turnInterrupted: "连接中断，可点击重试",
  retryTurn: "重试",
  tasksButton: "办理事项",
  tasksTitle: "办理事项",
  tasksBack: "返回对话",
  tasksEmpty: "暂无进行中的事项",
  tasksGroupRunning: "进行中",
  tasksGroupWaiting: "等待我处理",
  tasksGroupDone: "已完成",
  taskSteps: (done: number, total: number) => `${done}/${total} 步骤`,
  taskCurrentStep: "当前步骤",
  taskStartedAt: "开始于",
  taskCancel: "取消事项",
  taskCancelling: "正在取消……",
  taskApprove: "批准计划",
  taskStart: "开始执行",
  taskRetryStep: "重试这一步",
  taskResume: "继续",
  taskViewResult: "查看结果",
  taskOpenTarget: "打开",
  taskRefresh: "刷新",
  taskStateMap: {
    draft: "待确认",
    awaiting_approval: "待开始",
    queued: "排队中",
    running: "执行中",
    waiting_domain_job: "等待后台任务",
    paused_for_user: "等待你处理",
    succeeded: "已完成",
    partially_succeeded: "部分完成",
    failed: "未完成",
    cancelled: "已取消",
    interrupted: "已中断",
  } as Record<string, string>,
  taskStepStateMap: {
    pending: "未开始",
    ready: "就绪",
    running: "执行中",
    waiting: "等待中",
    succeeded: "已完成",
    failed: "失败",
    skipped: "已跳过",
    cancelled: "已取消",
  } as Record<string, string>,
  taskPlanWillChange: "将创建或修改",
  taskPlanUserInvolvement: "需要你参与",
  taskErrorHint: "上一步失败：",
  actionCreateWorkflow: "创建办理事项",
  actionOpenTasks: "查看办理事项",
  inboxButton: "收件箱",
  inboxTitle: "收件箱",
  inboxBack: "返回对话",
  inboxEmpty: "暂无通知",
  inboxUnreadDot: "有未读通知",
  inboxMarkRead: "标为已读",
  inboxDismiss: "忽略",
  inboxDismissMute: "忽略并不再提醒此课程",
  inboxOpenTarget: "查看",
  inboxReportWindow: "统计窗口",
  inboxReportDelete: "删除简报",
  inboxReportDeleted: "简报已删除",
  inboxLoading: "加载中……",
  settingsTitle: "助手设置",
  settingsResponseLength: "回答长度",
  settingsTone: "回答语气",
  settingsDefaultScope: "默认查询范围",
  settingsScopeFollowPage: "跟随页面",
  settingsScopeAll: "全部学习区",
  settingsProactive: "主动服务总开关",
  settingsProactiveHint: "关闭后不再生成任何主动提醒；订阅保留，可随时重开。",
  settingsSave: "保存",
  settingsSaved: "已保存",
  settingsConflict: "设置已被其他页面更新，请刷新后重试。",
  settingsSubscriptions: "订阅管理",
  settingsSubKind: {
    weekly_brief: "每周学习简报",
    daily_tasks: "每日任务提醒",
    due_reviews: "笔记复习到期",
    unfinished_course: "未完成课程提醒",
  } as Record<string, string>,
  settingsSubTime: "提醒时间",
  settingsSubWeekdays: "提醒日",
  settingsSubEnabled: "启用",
  settingsSubUnsubscribe: "退订",
  settingsSubNextRun: "下次运行",
  settingsSubCreate: "添加订阅",
  settingsSchedulerOff: "主动服务调度未开启，订阅暂不投递。",
  settingsViewInbox: "查看最近投递",
  weekdayShort: ["一", "二", "三", "四", "五", "六", "日"] as string[],
};

export type AssistantStrings = typeof zh;

const en: AssistantStrings = {
  errorPreview: "Failed to load preview",
  errorAction: "Action failed. Please try again.",
  errorUndo: "Could not undo. Please try again.",
  errorCapabilities: "Could not load available features",
  errorConversationCreate: "Could not create conversation",
  errorConversationRead: "Could not load conversation",
  errorSend: "Could not send. Please try again.",
  errorAnswer: "Could not generate an answer",
  previewEmpty: "(empty)",
  settingsLengthShort: "Short",
  settingsLengthStandard: "Standard",
  settingsLengthDetailed: "Detailed",
  settingsToneNeutral: "Neutral",
  settingsToneEncouraging: "Encouraging",
  voiceStopRecording: "Stop recording",
  voiceHold: "Hold to speak",
  voiceStopReading: "Stop reading",
  voiceReadLatest: "Read latest reply",
  launcherTooltip: "Study Assistant · Ctrl/Cmd+Shift+K",
  panelTitle: "Study Assistant",
  historyButton: "History",
  expandButton: "Expand",
  collapseButton: "Collapse",
  shrinkButton: "Restore size",
  closeButton: "Collapse assistant",
  scopeFollowPage: "Follow page",
  scopeAllWorkspaces: "All workspaces",
  scopeWorkspace: "Workspace",
  scopeSeparator: " / ",
  welcome: "I can find features, resume courses, or review your learning.",
  quickIntro: "What can this site do for me?",
  quickStart: "Where should I start?",
  quickCourse: "Open Courses",
  quickRecent: "How did my learning go?",
  inputPlaceholder: "Ask about features, courses, or recent learning…",
  quoteChip: "Quoted",
  quoteRemove: "Remove quote",
  send: "Send",
  stop: "Stop",
  stopped: "Stopped",
  newContent: "New content",
  connectionLost: "Connection lost — click to resume",
  reconnecting: "Reconnecting…",
  historyTitle: "Conversations",
  historyEmpty: "No conversations yet",
  historyBack: "Back to chat",
  newConversation: "New chat",
  deleteConversation: "Delete",
  deleteConfirm: "Delete this conversation? Its actions and drafts expire too.",
  loadMore: "Load earlier messages",
  noMore: "All messages loaded",
  unreadDot: "New reply",
  running: "Working",
  needsLogin: "Sign in to use the Study Assistant",
  disabled: "The Study Assistant is not available now",
  modelUnavailable: "Assistant service unavailable, try later",
  statusMap: {
    understanding: "Understanding your question",
    reading: "Reading learning records",
    composing: "Composing the answer",
  },
  actionPrimary: "Open now",
  previewViewChanges: "Review changes",
  previewLoading: "Building preview…",
  previewConfirm: "Confirm and run",
  previewReject: "Cancel",
  previewWorking: "Working…",
  previewReversible: "Undo available",
  previewNotReversible: "Cannot be auto-undone",
  previewTtl: "Confirmation valid for 10 minutes",
  voiceReading: "Reading…",
  previewExpired: "Preview expired",
  previewStaleHint: "The preview expired or its parameters changed. Go back and review changes again.",
  actionUndo: "Undo",
  actionUndoBusy: "Undoing…",
  actionUndone: "Undone",
  choicesPrompt: "Choose one:",
  viewSources: (n: number) => `View ${n} sources`,
  metricsUnavailable: "No data",
  knownMinimumPrefix: "At least",
  noticeInfo: "Info",
  noticeWarning: "Note",
  noticeError: "Error",
  turnInterrupted: "Interrupted — retry available",
  retryTurn: "Retry",
  tasksButton: "Tasks",
  tasksTitle: "Tasks",
  tasksBack: "Back to chat",
  tasksEmpty: "No tasks in progress",
  tasksGroupRunning: "In progress",
  tasksGroupWaiting: "Waiting for you",
  tasksGroupDone: "Finished",
  taskSteps: (done: number, total: number) => `${done}/${total} steps`,
  taskCurrentStep: "Current step",
  taskStartedAt: "Started",
  taskCancel: "Cancel task",
  taskCancelling: "Cancelling…",
  taskApprove: "Approve plan",
  taskStart: "Start",
  taskRetryStep: "Retry this step",
  taskResume: "Resume",
  taskViewResult: "View results",
  taskOpenTarget: "Open",
  taskRefresh: "Refresh",
  taskStateMap: {
    draft: "To confirm",
    awaiting_approval: "Ready to start",
    queued: "Queued",
    running: "Running",
    waiting_domain_job: "Waiting for background job",
    paused_for_user: "Waiting for you",
    succeeded: "Completed",
    partially_succeeded: "Partially completed",
    failed: "Failed",
    cancelled: "Cancelled",
    interrupted: "Interrupted",
  },
  taskStepStateMap: {
    pending: "Not started",
    ready: "Ready",
    running: "Running",
    waiting: "Waiting",
    succeeded: "Done",
    failed: "Failed",
    skipped: "Skipped",
    cancelled: "Cancelled",
  },
  taskPlanWillChange: "Will create or modify",
  taskPlanUserInvolvement: "Needs you",
  taskErrorHint: "Last step failed: ",
  actionCreateWorkflow: "Create task",
  actionOpenTasks: "View tasks",
  inboxButton: "Inbox",
  inboxTitle: "Inbox",
  inboxBack: "Back to chat",
  inboxEmpty: "No notifications",
  inboxUnreadDot: "Unread notifications",
  inboxMarkRead: "Mark read",
  inboxDismiss: "Dismiss",
  inboxDismissMute: "Dismiss and mute this course",
  inboxOpenTarget: "Open",
  inboxReportWindow: "Statistics window",
  inboxReportDelete: "Delete brief",
  inboxReportDeleted: "Brief deleted",
  inboxLoading: "Loading…",
  settingsTitle: "Assistant settings",
  settingsResponseLength: "Answer length",
  settingsTone: "Tone",
  settingsDefaultScope: "Default scope",
  settingsScopeFollowPage: "Follow page",
  settingsScopeAll: "All workspaces",
  settingsProactive: "Proactive service",
  settingsProactiveHint: "When off, no proactive reminders are generated; subscriptions are kept.",
  settingsSave: "Save",
  settingsSaved: "Saved",
  settingsConflict: "Settings were updated elsewhere, refresh and retry.",
  settingsSubscriptions: "Subscriptions",
  settingsSubKind: {
    weekly_brief: "Weekly learning brief",
    daily_tasks: "Daily tasks",
    due_reviews: "Note reviews due",
    unfinished_course: "Unfinished course",
  },
  settingsSubTime: "Remind at",
  settingsSubWeekdays: "Days",
  settingsSubEnabled: "Enabled",
  settingsSubUnsubscribe: "Unsubscribe",
  settingsSubNextRun: "Next run",
  settingsSubCreate: "Add subscription",
  settingsSchedulerOff: "Proactive scheduling is off; subscriptions pause.",
  settingsViewInbox: "View recent deliveries",
  weekdayShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
};

export const STRINGS: Record<"zh" | "en", AssistantStrings> = { zh, en };

export function stringsFor(lang: "zh" | "en"): AssistantStrings {
  return STRINGS[lang] ?? STRINGS.zh;
}
