import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "account.title": "账户资料", "account.subtitle": "你的个人资料与账户信息",
    "account.menu": "我的账户", "account.guest": "游客", "account.notLoggedIn": "尚未登录",
    "account.login": "登录 / 注册", "account.loginHint": "登录后查看和管理你的账户信息。",
    "account.role.admin": "管理员", "account.role.user": "普通账户",
    "account.personal": "个人资料", "account.details": "账户信息", "account.username": "用户名",
    "account.email": "邮箱", "account.id": "账户 ID", "account.created": "注册时间",
    "account.lastLogin": "最近登录", "account.copy": "复制账户 ID", "account.copied": "已复制",
    "account.copyFailed": "复制失败，请手动复制", "account.empty": "未填写", "account.noDate": "暂无记录",
    "settings.desc": "调整你的学习体验与个人偏好",
    "settings.general": "通用", "settings.learning": "学习与回答", "settings.voice": "语音与课堂",
    "settings.assistant": "助手", "settings.processing": "资料处理", "settings.account": "账户与数据", "settings.about": "关于",
    "settings.local": "这些偏好保存在当前浏览器，即时生效。",
    "settings.gradeHint": "学段保存到你的账户，并同步用于学习画像与新对话。已有对话保留各自学段，可在对话输入栏单独调整。",
    "settings.guestGradeHint": "默认学段保存在当前浏览器，用于新对话；已有对话可在输入栏单独调整。",
    "settings.gradeLocation": "教学学段在设置中调整：",
    "settings.saving": "正在保存…",
    "settings.model.localVoice": "本地语音模型", "settings.model.cloudVoice": "云端语音模型",
    "settings.model.enabled": "已启用", "settings.model.disabled": "未启用",
    "settings.model.configured": "已配置", "settings.model.unconfigured": "未配置",
    "settings.model.autoVoice": "自动语音", "settings.model.localFirst": "本地优先",
    "avatar.upload": "上传头像", "avatar.remove": "移除头像", "avatar.crop": "裁剪头像",
    "avatar.hint": "拖动图片并调整缩放，也可用下方滑杆定位。保存为 256 × 256 像素，仅供你的账户使用。",
    "avatar.invalid": "请选择 5 MB 以内、2000 万像素以内的 PNG、JPEG 或 WebP 图片。",
    "avatar.preview": "头像裁剪预览", "avatar.zoom": "缩放", "avatar.horizontal": "水平位置", "avatar.vertical": "垂直位置",
    "avatar.reset": "重置裁剪", "avatar.save": "保存头像", "avatar.cancel": "取消",
    "settings.loginHint": "登录后可保存这些账户偏好。",
    "settings.disabled": "此功能当前未启用。", "settings.loading": "正在加载…", "settings.loadFailed": "加载失败，请重试",
    "settings.saved": "已保存", "settings.unsaved": "有尚未保存的修改，离开将放弃这些修改。继续吗？",
    "settings.retry": "重试", "settings.saveFailed": "保存失败，请重试",
    "settings.updated": "设置已更新", "settings.help": "说明：{label}",
    "settings.language.hint": "切换界面显示语言，保存在当前浏览器；回答语言可在「学习与回答」中单独设置。",
    "settings.language.zh.hint": "使用中文显示菜单、按钮和界面说明。",
    "settings.language.en.hint": "使用英文显示菜单、按钮和界面说明。",
    "settings.theme.hint": "调整界面配色，选择后立即生效并保存在当前浏览器。",
    "settings.theme.system.hint": "随操作系统的浅色或深色外观自动切换。",
    "settings.theme.light.hint": "始终使用浅色界面。",
    "settings.theme.dark.hint": "始终使用深色界面。",
    "settings.font.hint": "调整界面文字大小，选择后立即生效并保存在当前浏览器。",
    "settings.font.sm.hint": "使用默认字号，界面更紧凑。",
    "settings.font.md.hint": "将文字放大到默认字号的 125%。",
    "settings.font.lg.hint": "将文字放大到默认字号的 150%。",
    "settings.font.xl.hint": "将文字放大到默认字号的 175%。",
    "settings.answer.hint": "设置老师回答时使用的语言，不影响界面语言。",
    "settings.answer.auto.hint": "根据问题内容自动选择回答语言。",
    "settings.answer.zh.hint": "优先使用中文回答。",
    "settings.answer.en.hint": "优先使用英文回答。",
    "settings.grade.auto.hint": "不预设学段，由老师根据问题和资料调整讲解深度。",
    "settings.grade.primary.hint": "新对话按小学阶段组织讲解与练习。",
    "settings.grade.middle.hint": "新对话按初中阶段组织讲解与练习。",
    "settings.grade.high.hint": "新对话按高中阶段组织讲解与练习。",
    "settings.grade.undergrad.hint": "新对话按本科阶段组织讲解与练习。",
    "settings.voice.auto.hint": "优先使用本地语音；本地不可用时选择可用的云端音色。",
    "settings.voice.cloud.hint": "使用云端语音朗读课堂内容，需要云端语音服务可用。",
    "settings.voice.local.hint": "使用本地语音模型朗读课堂内容，需要本地语音服务可用。",
    "settings.voice.silent.hint": "只显示课堂讲稿，不生成朗读音频。",
    "settings.voice.voice.hint": "选择新建课堂默认使用的音色；可选音色随语音来源变化。",
    "settings.voice.fallback.hint": "云端朗读失败时尝试本地语音，让课堂继续播放；需要本地语音服务可用。",
    "settings.voice.save.hint": "将课堂语音来源、音色和回退偏好保存到账户，供新建课堂使用。",
    "settings.retry.hint": "重新加载刚才未能获取的信息。",
    "settings.speed.retry.hint": "重新保存刚才调整的朗读语速。",
    "account.illustrationMode": "默认配图方式",
    "account.illustrationMode.v1": "旧版模型生成",
    "account.illustrationMode.v2": "最新素材库",
    "account.illustrationMode.desc": "V1 保留旧版模型自行绘图；V2 使用最新素材库组合。出题中心可以按单次测评覆盖。",
    "account.illustrationMode.failed": "配图方式保存失败，请重试。",
    "settings.model.main.hint": "负责理解问题、生成回答与教学内容的主要模型。",
    "settings.model.localVoice.hint": "显示当前本地朗读模型、启用状态及音色。",
    "settings.model.cloudVoice.hint": "显示当前云端朗读服务的配置状态和可用音色。",
    "settings.model.autoVoice.hint": "自动语音优先使用本地服务，本地不可用时使用可用的云端服务。",
    "settings.delete.password.hint": "验证当前账户密码，避免他人误删你的账户。",
    "settings.delete.confirm.hint": "输入指定确认文字后才能执行永久注销。",
    "settings.delete.cancel.hint": "关闭确认窗口，保留账户和数据。",
    "settings.assistant.length.hint": "控制站内助手回答的篇幅：短更精炼，标准保持适中，详细提供更多解释。",
    "settings.assistant.tone.hint": "控制站内助手的表达语气：平实更直接，鼓励更注重正向反馈。",
    "settings.assistant.scope.hint": "跟随页面时优先查询当前学习区；全部学习区时可跨学习区查询。",
    "settings.assistant.subscriptions.hint": "按类型和本地时间设置定期提醒；启用主动服务且调度可用时才会投递。",
    "settings.assistant.kind.hint": "选择提醒内容：每周学习简报、每日任务、到期笔记复习或未完成课程。",
    "settings.assistant.time.hint": "按当前浏览器所在时区，在指定本地时间生成订阅提醒。",
    "settings.assistant.enabled.hint": "暂停或恢复这条订阅；暂停后保留订阅设置。",
    "settings.assistant.unsubscribe.hint": "删除这条订阅，停止其后续提醒。",
    "settings.assistant.create.hint": "使用所选提醒类型和时间创建一条订阅。",
    "settings.assistant.inbox.hint": "打开助手收件箱，查看最近生成的简报与提醒。",
  },
  en: {
    "account.title": "Account details", "account.subtitle": "Your personal and account information",
    "account.menu": "My account", "account.guest": "Guest", "account.notLoggedIn": "Not signed in",
    "account.login": "Log in / Register", "account.loginHint": "Sign in to view and manage your account.",
    "account.role.admin": "Administrator", "account.role.user": "Personal account",
    "account.personal": "Personal details", "account.details": "Account information", "account.username": "Username",
    "account.email": "Email", "account.id": "Account ID", "account.created": "Registered on",
    "account.lastLogin": "Last login", "account.copy": "Copy account ID", "account.copied": "Copied",
    "account.copyFailed": "Copy failed. Please copy manually.", "account.empty": "Not provided", "account.noDate": "No record",
    "settings.desc": "Adjust your learning experience and preferences",
    "settings.general": "General", "settings.learning": "Learning & answers", "settings.voice": "Voice & classroom",
    "settings.assistant": "Assistant", "settings.processing": "Document processing", "settings.account": "Account & data", "settings.about": "About",
    "settings.local": "These preferences are saved in this browser and apply immediately.",
    "settings.gradeHint": "Your level is saved to your account and used for your learning profile and new chats. Existing chats keep their own level, adjustable in the chat input.",
    "settings.guestGradeHint": "The default level is saved in this browser for new chats. Existing chats can be adjusted in the chat input.",
    "settings.gradeLocation": "Adjust your teaching level in settings:",
    "settings.saving": "Saving…",
    "settings.model.localVoice": "Local voice model", "settings.model.cloudVoice": "Cloud voice model",
    "settings.model.enabled": "Enabled", "settings.model.disabled": "Disabled",
    "settings.model.configured": "Configured", "settings.model.unconfigured": "Not configured",
    "settings.model.autoVoice": "Automatic voice", "settings.model.localFirst": "Local first",
    "avatar.upload": "Upload avatar", "avatar.remove": "Remove avatar", "avatar.crop": "Crop avatar",
    "avatar.hint": "Drag and zoom the image, or position it with the sliders. Saved as 256 × 256 pixels for your account only.",
    "avatar.invalid": "Choose a PNG, JPEG or WebP image up to 5 MB and 20 megapixels.",
    "avatar.preview": "Avatar crop preview", "avatar.zoom": "Zoom", "avatar.horizontal": "Horizontal", "avatar.vertical": "Vertical",
    "avatar.reset": "Reset crop", "avatar.save": "Save avatar", "avatar.cancel": "Cancel",
    "settings.loginHint": "Sign in to save these account preferences.",
    "settings.disabled": "This feature is currently disabled.", "settings.loading": "Loading…", "settings.loadFailed": "Could not load. Please retry.",
    "settings.saved": "Saved", "settings.unsaved": "You have unsaved changes. Leave and discard them?",
    "settings.retry": "Retry", "settings.saveFailed": "Could not save. Please retry.",
    "settings.updated": "Settings updated", "settings.help": "Help: {label}",
    "settings.language.hint": "Change the interface language in this browser. Set the answer language separately under Learning & answers.",
    "settings.language.zh.hint": "Display menus, buttons and interface descriptions in Chinese.",
    "settings.language.en.hint": "Display menus, buttons and interface descriptions in English.",
    "settings.theme.hint": "Change the interface colors immediately and save the choice in this browser.",
    "settings.theme.system.hint": "Automatically follow your operating system's light or dark appearance.",
    "settings.theme.light.hint": "Always use the light interface.",
    "settings.theme.dark.hint": "Always use the dark interface.",
    "settings.font.hint": "Change interface text size immediately and save the choice in this browser.",
    "settings.font.sm.hint": "Use the default text size for a compact interface.",
    "settings.font.md.hint": "Scale text to 125% of the default size.",
    "settings.font.lg.hint": "Scale text to 150% of the default size.",
    "settings.font.xl.hint": "Scale text to 175% of the default size.",
    "settings.answer.hint": "Choose the tutor's answer language without changing the interface language.",
    "settings.answer.auto.hint": "Choose the answer language automatically based on the question.",
    "settings.answer.zh.hint": "Prefer answering in Chinese.",
    "settings.answer.en.hint": "Prefer answering in English.",
    "settings.grade.auto.hint": "Let the tutor adapt the explanation depth to the question and materials without a preset level.",
    "settings.grade.primary.hint": "Use primary school explanations and exercises in new chats.",
    "settings.grade.middle.hint": "Use middle school explanations and exercises in new chats.",
    "settings.grade.high.hint": "Use high school explanations and exercises in new chats.",
    "settings.grade.undergrad.hint": "Use undergraduate explanations and exercises in new chats.",
    "settings.voice.auto.hint": "Prefer local speech; choose an available cloud voice when local speech is unavailable.",
    "settings.voice.cloud.hint": "Read lessons with cloud speech. Requires an available cloud speech service.",
    "settings.voice.local.hint": "Read lessons with a local speech model. Requires an available local speech service.",
    "settings.voice.silent.hint": "Display the lesson script without generating narration audio.",
    "settings.voice.voice.hint": "Choose the default voice for new lessons. Available voices depend on the speech source.",
    "settings.voice.fallback.hint": "Try local speech if cloud narration fails so the lesson can continue. Requires an available local speech service.",
    "settings.voice.save.hint": "Save the speech source, voice and fallback preferences to your account for new lessons.",
    "settings.retry.hint": "Retry loading the information that could not be fetched.",
    "settings.speed.retry.hint": "Retry saving your selected speech rate.",
    "account.illustrationMode": "Default illustration version",
    "account.illustrationMode.v1": "Legacy model generation",
    "account.illustrationMode.v2": "Latest material library",
    "account.illustrationMode.desc": "V1 keeps the legacy model-led drawing path; V2 uses the latest material library. The assessment center can override it per run.",
    "account.illustrationMode.failed": "Could not save the illustration version. Please retry.",
    "settings.model.main.hint": "The main model used to understand questions and generate answers and teaching content.",
    "settings.model.localVoice.hint": "Show the local narration model, its enabled state and voice.",
    "settings.model.cloudVoice.hint": "Show cloud narration configuration and available voices.",
    "settings.model.autoVoice.hint": "Automatic speech prefers the local service and uses an available cloud service if local speech is unavailable.",
    "settings.delete.password.hint": "Verify your current account password to prevent someone else from deleting your account.",
    "settings.delete.confirm.hint": "Enter the required confirmation text to enable permanent account deletion.",
    "settings.delete.cancel.hint": "Close this confirmation and keep your account and data.",
    "settings.assistant.length.hint": "Control the site assistant's answer length: short is concise, standard is moderate, and detailed includes more explanation.",
    "settings.assistant.tone.hint": "Choose the site assistant's tone: neutral is direct, while encouraging emphasizes positive feedback.",
    "settings.assistant.scope.hint": "Follow page prioritizes the current workspace; all workspaces allows queries across workspaces.",
    "settings.assistant.subscriptions.hint": "Schedule reminders by type and local time. Delivery requires proactive service and scheduling to be enabled.",
    "settings.assistant.kind.hint": "Choose weekly learning briefs, daily tasks, due note reviews or unfinished lesson reminders.",
    "settings.assistant.time.hint": "Generate subscription reminders at this local time in the browser's current timezone.",
    "settings.assistant.enabled.hint": "Pause or resume this subscription while keeping its settings.",
    "settings.assistant.unsubscribe.hint": "Delete this subscription and stop its future reminders.",
    "settings.assistant.create.hint": "Create a subscription with the selected reminder type and time.",
    "settings.assistant.inbox.hint": "Open the assistant inbox to see recent briefs and reminders.",
  },
} satisfies PageStrings;
