// /plan 学习计划页（M3 教学引擎）的页面级词条。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "page.title": "学习计划",
    "page.desc": "M3 教学引擎 · 六模式状态机驱动的个性化学习路径",
    "mode.title": "教学模式状态机",
    "mode.desc": "六种模式随学习进程切换，高亮为最近一次教学的当前模式",
    "focus.introduction": "从零建立第一印象：用生活实例引出概念，不堆术语。",
    "focus.explanation": "系统拆解概念结构，配合例题讲清「为什么」。",
    "focus.remediation": "先定位错因、重建直觉，再针对性巩固，不只给答案。",
    "focus.practice": "以练促学：分层题目训练，即时反馈、及时纠正。",
    "focus.review": "回顾已学内容，激活记忆、查漏补缺，对抗遗忘曲线。",
    "focus.challenge": "拔高拓展：综合题与开放问题，冲击更高掌握度。",
    "focus.none": "暂无教学记录，当前模式将在首次学习后确定。",
    "difficulty.label": "动态难度",
    "difficulty.desc": "按近期表现自动调节（1–5）",
    "next.title": "接下来学什么",
    "next.desc": "前置已满足、尚未掌握的概念",
    "next.go": "去学习",
    "review.title": "该复习什么",
    "review.desc": "掌握度中等、近期未巩固的概念",
    "review.go": "去复习",
    "list.empty": "暂无推荐",
    "log.title": "教学日志",
    "log.desc": "按概念分组的跨轮教学记忆，点击展开时间线",
    "log.entries": "条记录",
    "outcome.engaged": "已讲授",
    "outcome.unknown": "未评估",
    "empty.title": "暂无教学记录",
    "empty.desc": "开始一段学习对话后，教学引擎会在此记录每个概念的模式切换与结果。",
    "disabled.title": "教学引擎已关闭",
    "disabled.desc": "M3 教学引擎被环境开关（智能层配置）关闭，学习计划暂不可用。",
    "error.load": "学习计划加载失败，请确认后端服务已启动。",
    "q.learn": "讲一下",
    "q.review": "复习一下",
  },
  en: {
    "page.title": "Learning Plan",
    "page.desc": "M3 Teaching Engine · a personalized path driven by a six-mode state machine",
    "mode.title": "Teaching Mode State Machine",
    "mode.desc": "Six modes switch with learning progress; the highlighted one is the most recent",
    "focus.introduction": "Build a first impression from scratch: introduce the concept with real-life examples, no jargon.",
    "focus.explanation": "Systematically break down the concept, with worked examples that explain the “why”.",
    "focus.remediation": "Locate the root misconception and rebuild intuition first — never just hand over the answer.",
    "focus.practice": "Learn by doing: tiered exercises with instant feedback and timely correction.",
    "focus.review": "Revisit what was learned, reactivate memory and fill gaps against the forgetting curve.",
    "focus.challenge": "Stretch further: composite and open problems to push mastery higher.",
    "focus.none": "No teaching record yet — the current mode will be set after your first session.",
    "difficulty.label": "Adaptive Difficulty",
    "difficulty.desc": "Auto-tuned from recent performance (1–5)",
    "next.title": "Learn Next",
    "next.desc": "Prerequisites met, not yet mastered",
    "next.go": "Learn",
    "review.title": "Time to Review",
    "review.desc": "Middling mastery, not consolidated recently",
    "review.go": "Review",
    "list.empty": "No recommendations yet",
    "log.title": "Teaching Log",
    "log.desc": "Cross-turn teaching memory grouped by concept; click to expand the timeline",
    "log.entries": "entries",
    "outcome.engaged": "Engaged",
    "outcome.unknown": "Not assessed",
    "empty.title": "No teaching records yet",
    "empty.desc": "Once you start a learning conversation, the engine records each concept's mode switches and outcomes here.",
    "disabled.title": "Teaching Engine Disabled",
    "disabled.desc": "The M3 teaching engine is turned off by an environment switch (intelligence-layer config); the learning plan is unavailable.",
    "error.load": "Failed to load the learning plan. Please make sure the backend is running.",
    "q.learn": "Explain ",
    "q.review": "Review ",
  },
} satisfies PageStrings;
