"""Repository protocols the identity domain consumes.

Split by ownership (accounts / tenants / sessions / audit) so later domains
copy the shape instead of growing one god-interface. Implementations may be
SQLAlchemy (enterprise), file-backed (migration window), or test doubles.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from .records import (AccountRecord, AuditEventRecord, AuthSessionRecord,
                      CredentialRecord, MembershipRecord, RefreshTokenRecord,
                      TenantRecord)


class RepositoryError(Exception):
    """Base class for storage-level failures surfaced to the domain."""


class DuplicateEmailError(RepositoryError):
    """Raised when creating an account with an email that already exists."""


@runtime_checkable
class AccountRepository(Protocol):
    async def create_account(self, account: AccountRecord,
                             credential: CredentialRecord | None = None,
                             ) -> AccountRecord:
        """Insert a user (and optionally its initial credential row).
        Raises DuplicateEmailError when the email is taken."""
        ...

    async def get_account_by_email(self, email: str) -> AccountRecord | None: ...
    async def get_account_by_id(self, user_id: str) -> AccountRecord | None: ...
    async def update_account(self, account: AccountRecord) -> AccountRecord: ...
    async def bump_token_version(self, user_id: str) -> bool: ...
    async def list_accounts(self) -> list[AccountRecord]: ...
    async def delete_account(self, user_id: str) -> bool: ...
    async def get_password_credential(self, user_id: str) -> CredentialRecord | None: ...
    async def create_credential(self, credential: CredentialRecord) -> CredentialRecord:
        """Insert a credential row (kind-scoped per user)."""
        ...
    async def update_password_credential(self, credential: CredentialRecord) -> None: ...


@runtime_checkable
class TenantRepository(Protocol):
    async def create_tenant(self, tenant: TenantRecord) -> TenantRecord: ...
    async def get_tenant(self, tenant_id: str) -> TenantRecord | None: ...
    async def create_membership(self, membership: MembershipRecord) -> MembershipRecord: ...
    async def get_membership(self, tenant_id: str, user_id: str) -> MembershipRecord | None: ...
    async def list_memberships_for_user(self, user_id: str) -> list[MembershipRecord]: ...
    async def set_active_tenant(self, user_id: str, tenant_id: str) -> None: ...


@runtime_checkable
class SessionRepository(Protocol):
    async def create_session(self, session: AuthSessionRecord,
                             refresh_token: RefreshTokenRecord) -> AuthSessionRecord:
        """Create a refresh-session family with its first (active) token."""
        ...

    async def get_session(self, session_id: str) -> AuthSessionRecord | None: ...
    async def list_sessions_for_user(self, user_id: str) -> list[AuthSessionRecord]: ...
    async def revoke_session(self, session_id: str, reason: str) -> bool: ...
    async def find_refresh_token(self, token_hash: str) -> RefreshTokenRecord | None: ...
    async def rotate_refresh_token(self, old: RefreshTokenRecord,
                                   replacement: RefreshTokenRecord) -> None:
        """Atomically mark ``old`` rotated and insert ``replacement``.
        Implementations must fail if ``old`` was already rotated."""
        ...

    async def revoke_session_tokens(self, session_id: str) -> None: ...


@runtime_checkable
class AuditRepository(Protocol):
    async def record_event(self, event: AuditEventRecord) -> None: ...
    async def list_events(self, *, user_id: str | None = None,
                          limit: int = 100) -> list[AuditEventRecord]: ...
