// /insights 页面级词条（M7 评估与改进智能）。
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS = {
  zh: {
    "ins.title": "系统洞察",
    "ins.subtitle": "M7 评估与改进智能 · 改进顾问层",
    "ins.observer":
      "M7 是纯观察者：observe → diagnose → propose。批准与部署由人工在此确认，智能层不会自行修改教学行为。",
    "ins.stat.turns": "总教学轮次",
    "ins.stat.evaluated": "已评估轮次",
    "ins.stat.gain": "平均学习增量",
    "ins.stat.pending": "待审批提案",
    "ins.stat.pending.foot": "需要人工确认",
    "ins.stat.gain.foot": "掌握度 Δ（评估前后）",
    "ins.context.title": "上下文与模型预算",
    "ins.context.desc": "当前窗口、工具投影、压缩收益与恢复统计",
    "ins.context.pressure.success": "压力正常",
    "ins.context.pressure.warning": "有软阈值压力",
    "ins.context.pressure.danger": "触及硬阈值",
    "ins.context.window": "上下文窗口",
    "ins.context.avgInput": "平均输入",
    "ins.context.avgOutput": "平均输出",
    "ins.context.saved": "估算节省",
    "ins.context.tokens": "tokens",
    "ins.context.profile": "运行档案",
    "ins.context.projection": "工具投影节省",
    "ins.context.recovery": "恢复 / 回退",
    "ins.context.channels": "思考 / 答案通道",
    "ins.fail.title": "失败诊断分布",
    "ins.fail.desc": "trace_analyzer 对已评估轮次的七类归因",
    "ins.fail.empty": "暂无已评估轮次，完成几轮学习后这里会出现诊断分布。",
    "ins.strategy.title": "策略效果排名",
    "ins.strategy.desc": "按平均成功率排序（mode × subject）",
    "ins.strategy.empty": "暂无策略统计数据。",
    "ins.strategy.samples": "次",
    "ins.strategy.gain": "增益",
    "ins.proposals.title": "教学指导提案（人工确认门）",
    "ins.proposals.desc": "LLM 顾问每积累 15 条教学轮次生成 1 条教学指导提案；人工批准并应用后，它进入下方「生效中的教学指导」作用于后续每一轮教学。",
    "ins.proposals.empty": "暂无提案。每积累 15 条教学轮次，顾问会综合评估证据并生成 1 条教学指导提案。",
    "ins.proposals.approve": "批准",
    "ins.proposals.reject": "拒绝",
    "ins.proposals.apply": "应用为教学指导",
    "ins.proposals.confidence": "置信度",
    "ins.proposals.evidence": "条证据",
    "ins.proposals.scope": "适用范围",
    "ins.proposals.caution": "注意",
    "ins.proposals.impact": "已影响最近",
    "ins.proposals.impactUnknown": "影响轮数未知",
    "ins.guidance.title": "生效中的教学指导",
    "ins.guidance.desc": "已应用提案转化的教学指导，每轮教学自动生效；吊销后立即回滚，教学行为恢复原状。",
    "ins.guidance.empty": "暂无生效中的教学指导。提案被批准并应用后会出现在这里。",
    "ins.guidance.active": "生效中",
    "ins.guidance.appliedAt": "应用于",
    "ins.guidance.source": "来自提案",
    "ins.guidance.revoke": "吊销",
    "ins.error.revoke": "吊销教学指导失败，请重试。",
    "ins.status.proposed": "待审批",
    "ins.status.approved": "已批准",
    "ins.status.applied": "已应用",
    "ins.status.rejected": "已拒绝",
    "ins.target.prompt": "提示词",
    "ins.target.policy": "策略规则",
    "ins.target.strategy": "教学策略",
    "ins.target.guidance": "教学指导",
    "ins.traces.title": "教学轮次黑盒 TurnTrace",
    "ins.traces.desc": "最近 50 轮追加式评估记录，点击行展开诊断细节",
    "ins.traces.empty": "暂无评估记录，开始一轮对话后这里会出现黑盒轨迹。",
    "ins.col.time": "时间",
    "ins.col.concept": "概念",
    "ins.col.subject": "学科",
    "ins.col.mode": "模式",
    "ins.col.outcome": "结果",
    "ins.col.gain": "学习增益",
    "ins.col.failure": "失败类型",
    "ins.trace.cause": "失败原因",
    "ins.trace.intent": "意图",
    "ins.trace.tools": "工具调用",
    "ins.trace.tokens": "Tokens",
    "ins.trace.duration": "耗时",
    "ins.trace.resume": "恢复会话",
    "ins.failure.none": "无失败",
    "ins.failure.teaching_depth_mismatch": "讲解深度不匹配",
    "ins.failure.prerequisite_missing": "前置知识缺失",
    "ins.failure.retrieval_miss": "知识检索未命中",
    "ins.failure.assessment_too_hard": "测评难度过高",
    "ins.failure.strategy_mismatch": "教学策略不适配",
    "ins.failure.no_assessment": "缺少收尾检测",
    "ins.outcome.engaged": "积极参与",
    "ins.error.load": "评估数据加载失败，请确认后端服务已启动。",
    "ins.error.patch": "提案状态更新失败，请重试。",
    "ins.disabled": "M7 评估智能已被环境开关关闭。",
  },
  en: {
    "ins.title": "Insights",
    "ins.subtitle": "M7 Evaluation & Improvement · advisor layer",
    "ins.observer":
      "M7 is a pure observer: observe → diagnose → propose. Approve & deploy are confirmed by a human here — the agent never changes teaching behavior on its own.",
    "ins.stat.turns": "Total turns",
    "ins.stat.evaluated": "Evaluated turns",
    "ins.stat.gain": "Avg learning gain",
    "ins.stat.pending": "Pending proposals",
    "ins.stat.pending.foot": "awaiting human review",
    "ins.stat.gain.foot": "mastery Δ (before → after)",
    "ins.context.title": "Context & model budget",
    "ins.context.desc": "Window, tool projection, compaction savings and recovery",
    "ins.context.pressure.success": "Normal pressure",
    "ins.context.pressure.warning": "Soft pressure",
    "ins.context.pressure.danger": "Hard threshold",
    "ins.context.window": "Context window",
    "ins.context.avgInput": "Avg input",
    "ins.context.avgOutput": "Avg output",
    "ins.context.saved": "Estimated saved",
    "ins.context.tokens": "tokens",
    "ins.context.profile": "Runtime profile",
    "ins.context.projection": "Tool projection saved",
    "ins.context.recovery": "Recovery / fallback",
    "ins.context.channels": "Reasoning / answer channels",
    "ins.fail.title": "Failure diagnosis",
    "ins.fail.desc": "Seven-way attribution over evaluated turns by trace_analyzer",
    "ins.fail.empty": "No evaluated turns yet — finish a few sessions and the diagnosis will appear.",
    "ins.strategy.title": "Strategy effectiveness",
    "ins.strategy.desc": "Ranked by average success rate (mode × subject)",
    "ins.strategy.empty": "No strategy statistics yet.",
    "ins.strategy.samples": "samples",
    "ins.strategy.gain": "gain",
    "ins.proposals.title": "Teaching guidance proposals (human gate)",
    "ins.proposals.desc": "Every 15 teaching turns the LLM advisor drafts 1 guidance proposal; once approved and applied here it enters the active guidance below and shapes every subsequent turn.",
    "ins.proposals.empty": "No proposals yet. Every 15 teaching turns the advisor weighs the evidence and drafts 1 guidance proposal.",
    "ins.proposals.approve": "Approve",
    "ins.proposals.reject": "Reject",
    "ins.proposals.apply": "Apply as guidance",
    "ins.proposals.confidence": "Confidence",
    "ins.proposals.evidence": "evidence",
    "ins.proposals.scope": "Applies to",
    "ins.proposals.caution": "Caution",
    "ins.proposals.impact": "Impacted last",
    "ins.proposals.impactUnknown": "Impact unknown",
    "ins.guidance.title": "Active teaching guidance",
    "ins.guidance.desc": "Guidance deployed from applied proposals — effective on every turn; revoking rolls teaching behavior back instantly.",
    "ins.guidance.empty": "No active guidance. Approved and applied proposals will appear here.",
    "ins.guidance.active": "Active",
    "ins.guidance.appliedAt": "Applied",
    "ins.guidance.source": "From proposal",
    "ins.guidance.revoke": "Revoke",
    "ins.error.revoke": "Failed to revoke the guidance — please retry.",
    "ins.status.proposed": "Proposed",
    "ins.status.approved": "Approved",
    "ins.status.applied": "Applied",
    "ins.status.rejected": "Rejected",
    "ins.target.prompt": "Prompt",
    "ins.target.policy": "Policy",
    "ins.target.strategy": "Strategy",
    "ins.target.guidance": "Teaching guidance",
    "ins.traces.title": "TurnTrace black box",
    "ins.traces.desc": "Latest 50 append-only evaluation records — click a row for diagnostics",
    "ins.traces.empty": "No traces yet — start a chat and the black-box records will appear.",
    "ins.col.time": "Time",
    "ins.col.concept": "Concept",
    "ins.col.subject": "Subject",
    "ins.col.mode": "Mode",
    "ins.col.outcome": "Outcome",
    "ins.col.gain": "Gain",
    "ins.col.failure": "Failure type",
    "ins.trace.cause": "Failure cause",
    "ins.trace.intent": "Intent",
    "ins.trace.tools": "Tool calls",
    "ins.trace.tokens": "Tokens",
    "ins.trace.duration": "Duration",
    "ins.trace.resume": "Resume session",
    "ins.failure.none": "None",
    "ins.failure.teaching_depth_mismatch": "Depth mismatch",
    "ins.failure.prerequisite_missing": "Prerequisite missing",
    "ins.failure.retrieval_miss": "Retrieval miss",
    "ins.failure.assessment_too_hard": "Assessment too hard",
    "ins.failure.strategy_mismatch": "Strategy mismatch",
    "ins.failure.no_assessment": "No closing assessment",
    "ins.outcome.engaged": "Engaged",
    "ins.error.load": "Failed to load evaluation data — check that the backend is running.",
    "ins.error.patch": "Failed to update proposal status — please retry.",
    "ins.disabled": "The M7 evaluation intelligence is disabled by an environment switch.",
  },
} satisfies PageStrings;
