/**
 * 化学实验台 3D（新）页面词条。纯前端娱乐玩具文案——不出现评分/目标/指导。
 */
import type { PageStrings } from "@/lib/i18n-page";

export const STRINGS: PageStrings = {
  zh: {
    "chem3d.back": "返回",
    "chem3d.backToCatalog": "返回关卡目录",
    "chem3d.stageMissing": "关卡不存在",
    "chem3d.stageMissingHint": "这个关卡不在目录里，请重新选择。",
    "chem3d.webglFailed": "当前浏览器不支持 WebGL2",
    "chem3d.webglFailedHint": "化学实验台需要 WebGL2 才能显示立体场景；请换用支持的浏览器或设备。",
    "chem3d.contextLost": "图形上下文中断，正在尝试恢复…",
    "chem3d.loading": "正在搭建实验台…",
    "chem3d.auto": "AUTO",
    "chem3d.save": "保存",
    "chem3d.open": "打开",
    "chem3d.reset": "重置",
    "chem3d.resetCamera": "视角",
    "chem3d.more": "更多",
    "chem3d.delete": "删除",
    "chem3d.cancel": "取消",
    "chem3d.tube": "软管",
    "chem3d.hint.firstVisit": "拖动仪器摆放 · 点接口接导管 · 或按 AUTO 一键拼好",
    "chem3d.hint.portBusy": "这个接口已被占用",
    "chem3d.hint.portNotConnectable": "请连接到管口",
    "chem3d.hint.limitReached": "台面已经放满啦",
    "chem3d.hint.mountNotAllowed": "这个器材不适合夹在这里",
    "chem3d.hint.autoFailed": "预装装置模板校验失败，已保留当前场景",
    "chem3d.toast.saved": "已保存到本机",
    "chem3d.toast.opened": "已打开本地存档",
    "chem3d.toast.tooSaves": "本地存档已满（12 个），请先删除旧的",
    "chem3d.toast.tooLarge": "这份场景太大，无法保存",
    "chem3d.toast.quota": "浏览器本地存储不可用，保存失败",
    "chem3d.toast.notFound": "找不到这份存档",
    "chem3d.toast.badSave": "存档已损坏，无法打开",
    "chem3d.autoConfirmTitle": "用预装装置替换当前摆放？",
    "chem3d.autoConfirmDesc": "AUTO 会载入这关的完整预组装装置；当前台面的器材、接线和液体都会被替换。",
    "chem3d.autoConfirmYes": "替换",
    "chem3d.resetConfirmTitle": "重置这一关？",
    "chem3d.resetConfirmDesc": "台面会恢复到进入关卡时的初始摆放；未保存的改动将丢失。",
    "chem3d.resetConfirmYes": "重置",
    "chem3d.exitConfirmTitle": "离开实验台？",
    "chem3d.exitConfirmDesc": "有未保存的改动；离开后将无法找回（可先保存到本机）。",
    "chem3d.exitConfirmYes": "离开",
    "chem3d.loadConfirmTitle": "打开这份存档？",
    "chem3d.loadConfirmDesc": "当前台面有未保存的改动，打开存档会替换当前摆放。",
    "chem3d.loadConfirmYes": "打开",
    "chem3d.savesTitle": "本机存档",
    "chem3d.savesEmpty": "还没有本机存档；点顶栏“保存”创建第一份。",
    "chem3d.act.addLiquid": "加入演示液",
    "chem3d.act.empty": "倒空",
    "chem3d.act.ignite": "点火",
    "chem3d.act.extinguish": "熄灭",
    "chem3d.act.valveOpen": "打开阀门",
    "chem3d.act.valveClose": "关闭阀门",
    "chem3d.act.powerOn": "开启",
    "chem3d.act.powerOff": "关闭",
    "chem3d.act.turn": "转动",
    "chem3d.act.rotate": "转动方向",
    "chem3d.act.duplicate": "复制一件",
    "chem3d.act.remove": "移除",
    "chem3d.act.disconnect": "拆开",
    "chem3d.act.pulse": "脉冲",
  },
  en: {
    "chem3d.back": "Back",
    "chem3d.backToCatalog": "Back to stages",
    "chem3d.stageMissing": "Stage not found",
    "chem3d.stageMissingHint": "This stage is not in the catalog. Please pick another one.",
    "chem3d.webglFailed": "WebGL2 is not available",
    "chem3d.webglFailedHint": "The chemistry bench needs WebGL2 to render its 3D scene. Try a browser that supports it.",
    "chem3d.contextLost": "Graphics context lost, trying to recover…",
    "chem3d.loading": "Setting up the bench…",
    "chem3d.auto": "AUTO",
    "chem3d.save": "Save",
    "chem3d.open": "Open",
    "chem3d.reset": "Reset",
    "chem3d.resetCamera": "View",
    "chem3d.more": "More",
    "chem3d.delete": "Delete",
    "chem3d.cancel": "Cancel",
    "chem3d.tube": "Tube",
    "chem3d.hint.firstVisit": "Drag equipment · click ports to connect tubes · or press AUTO",
    "chem3d.hint.portBusy": "That port is already in use",
    "chem3d.hint.portNotConnectable": "Please connect to a tube port",
    "chem3d.hint.limitReached": "The bench is full",
    "chem3d.hint.mountNotAllowed": "This piece does not fit that clamp",
    "chem3d.hint.autoFailed": "The pre-assembled template failed validation; your scene was kept",
    "chem3d.toast.saved": "Saved to this browser",
    "chem3d.toast.opened": "Local save opened",
    "chem3d.toast.tooSaves": "Local saves are full (12) — delete one first",
    "chem3d.toast.tooLarge": "This scene is too large to save",
    "chem3d.toast.quota": "Browser storage unavailable; save failed",
    "chem3d.toast.notFound": "Save not found",
    "chem3d.toast.badSave": "This save is damaged and cannot be opened",
    "chem3d.autoConfirmTitle": "Replace the bench with the pre-assembled rig?",
    "chem3d.autoConfirmDesc": "AUTO loads this stage's fully assembled apparatus; everything currently on the bench will be replaced.",
    "chem3d.autoConfirmYes": "Replace",
    "chem3d.resetConfirmTitle": "Reset this stage?",
    "chem3d.resetConfirmDesc": "The bench returns to its starting layout; unsaved changes will be lost.",
    "chem3d.resetConfirmYes": "Reset",
    "chem3d.exitConfirmTitle": "Leave the bench?",
    "chem3d.exitConfirmDesc": "You have unsaved changes; they cannot be recovered after leaving (save locally first).",
    "chem3d.exitConfirmYes": "Leave",
    "chem3d.loadConfirmTitle": "Open this save?",
    "chem3d.loadConfirmDesc": "The bench has unsaved changes; opening the save replaces the current layout.",
    "chem3d.loadConfirmYes": "Open",
    "chem3d.savesTitle": "Local saves",
    "chem3d.savesEmpty": "No local saves yet — press Save in the top bar to create one.",
    "chem3d.act.addLiquid": "Add demo liquid",
    "chem3d.act.empty": "Empty",
    "chem3d.act.ignite": "Light",
    "chem3d.act.extinguish": "Blow out",
    "chem3d.act.valveOpen": "Open valve",
    "chem3d.act.valveClose": "Close valve",
    "chem3d.act.powerOn": "Power on",
    "chem3d.act.powerOff": "Power off",
    "chem3d.act.turn": "Turn",
    "chem3d.act.rotate": "Rotate",
    "chem3d.act.duplicate": "Duplicate",
    "chem3d.act.remove": "Remove",
    "chem3d.act.disconnect": "Disconnect",
    "chem3d.act.pulse": "Pulse",
  },
};
