// AUTO-GENERATED by scripts/generate_classroom_types.py — DO NOT EDIT.
// Source of truth: backend/app/schemas/classroom.py (plan.md §10/§14)
// Regenerate with: python scripts/generate_classroom_types.py


export type ClassroomErrorCode = "classroom_disabled" | "source_not_ready" | "source_not_found" | "source_changed" | "research_unavailable" | "freshness_unverified" | "image_unavailable" | "content_invalid" | "layout_overflow" | "renderer_unavailable" | "budget_exceeded" | "quota_exceeded" | "generation_failed" | "job_cancelled" | "revision_conflict" | "lease_conflict" | "scope_changed" | "audio_busy" | "tts_unavailable" | "voice_unavailable" | "export_expired" | "storage_unavailable" | "damaged" | "idempotency_conflict";

export type SourcePolicy = "strict_textbook" | "textbook_plus" | "web_topic";

export type ResearchTimeliness = "basic" | "recent_year" | "recent_month";

export type ImageDensity = "none" | "balanced" | "rich";

export type CheckpointDensity = "none" | "light" | "standard";

export type LessonLanguage = "zh" | "en";

export type SlideLayout = "title" | "key_points" | "image_explain" | "compare" | "derivation" | "worked_example" | "timeline" | "checkpoint" | "summary";

export type SegmentRole = "motivation" | "explain" | "derive" | "example" | "misconception" | "transition" | "summary";

export type TransitionKind = "auto" | "manual";

export type CalloutTone = "note" | "warning" | "summary";

export type ImageFit = "contain" | "cover";

export type SourceKind = "textbook" | "workspace_file" | "session_file" | "web";

export type ClaimKind = "textbook_fact" | "web_fact" | "author_explanation" | "constructed_example";

export type ObjectiveEvidenceStatus = "supported" | "partial" | "uncovered";

export type AssetRole = "scene" | "object" | "process" | "diagram" | "data" | "decoration";

export type AssetStatus = "ready" | "unavailable";

export type AssetProvider = "pexels" | "pixabay" | "upload";

export type LessonLifecycle = "active" | "archiving" | "archived" | "purging";

export type JobState = "queued" | "running" | "awaiting_outline" | "needs_input" | "succeeded" | "failed" | "cancelled";

export type JobPhase = "resolve_sources" | "research" | "outline" | "visual_assets" | "author_slides" | "checkpoints" | "review" | "render" | "publish";

export type RunStatus = "active" | "paused" | "completed" | "ended";

export type AudioKind = "narration" | "qa" | "feedback";

export type AudioClipState = "pending" | "ready" | "failed";

export type ExportFormat = "html_zip" | "notes_md";

export type ExportState = "queued" | "succeeded" | "failed" | "expired";

export type CheckpointKind = "reflect" | "question";

export type VoicePolicy = "auto" | "cloud" | "local" | "silent";

export type StartMode = "automatic" | "outline_first";

export type RunStartMode = "resume_or_create" | "restart";

export type ProgressAction = "progress" | "pause" | "complete" | "end";

export type CheckpointRunState = "pending" | "answered" | "skipped";

export type LessonListStatus = "generating" | "ready" | "needs_attention" | "failed";

export type ImageSearchProvider = "pexels" | "pixabay";

export type VisualRole = "scene" | "object" | "process" | "diagram" | "data" | "decoration";

export type DiagramDirection = "horizontal" | "vertical";

export type RefreshScope = "missing" | "all";

export type Severity = "blocker" | "major" | "minor";

export interface SpanText {
  kind?: "text";
  text: string;
}

export interface SpanEmphasis {
  kind?: "emphasis";
  text: string;
}

export interface SpanMath {
  kind?: "math";
  latex: string;
  spoken: string;
}

export interface FlowNode {
  id: string;
  label: string;
}

export interface FlowEdge {
  from: string;
  to: string;
  label?: string | null;
}

export interface FlowDiagram {
  type?: "flow";
  direction?: DiagramDirection;
  nodes: Array<FlowNode>;
  edges?: Array<FlowEdge>;
  alt: string;
}

export interface PlotSeries {
  label: string;
  points: Array<[number, number]>;
}

export interface CartesianPlot {
  type?: "cartesian_plot";
  x_label: string;
  y_label: string;
  x_range: [number, number];
  y_range: [number, number];
  series: Array<PlotSeries>;
  source_ids?: Array<string>;
  constructed?: boolean;
  alt: string;
}

export interface ForceBody {
  id: string;
  shape: "point" | "box";
  x: number;
  y: number;
  label: string;
}

export interface ForceArrow {
  body_id: string;
  dx: number;
  dy: number;
  label: string;
}

export interface ForceDiagram {
  type?: "force_diagram";
  bodies: Array<ForceBody>;
  arrows?: Array<ForceArrow>;
  source_ids?: Array<string>;
  constructed?: boolean;
  alt: string;
}

export interface ParagraphBlock {
  kind?: "paragraph";
  id: string;
  spans: Array<SpanText | SpanEmphasis | SpanMath>;
}

export interface BulletsBlock {
  kind?: "bullets";
  id: string;
  items: Array<Array<SpanText | SpanEmphasis | SpanMath>>;
}

export interface FormulaBlock {
  kind?: "formula";
  id: string;
  latex: string;
  spoken: string;
  label?: string | null;
}

export interface ImageBlock {
  kind?: "image";
  id: string;
  asset_id: string;
  alt: string;
  caption: string;
  fit?: ImageFit;
}

export interface TableBlock {
  kind?: "table";
  id: string;
  headers: Array<string>;
  rows: Array<Array<string>>;
  source_ids?: Array<string>;
  constructed?: boolean;
}

export interface StepItem {
  label: string;
  spans: Array<SpanText | SpanEmphasis | SpanMath>;
}

export interface StepsBlock {
  kind?: "steps";
  id: string;
  steps: Array<StepItem>;
}

export interface DiagramBlock {
  kind?: "diagram";
  id: string;
  diagram: FlowDiagram | CartesianPlot | ForceDiagram;
}

export interface CheckpointBlock {
  kind?: "checkpoint";
  id: string;
  checkpoint_id: string;
}

export interface CalloutBlock {
  kind?: "callout";
  id: string;
  tone?: CalloutTone;
  spans: Array<SpanText | SpanEmphasis | SpanMath>;
}

export interface TeachingClaim {
  claim_id: string;
  text: string;
  kind: ClaimKind;
  block_ids?: Array<string>;
  segment_ids?: Array<string>;
  source_ids?: Array<string>;
  as_of?: string | null;
}

export interface NarrationSegment {
  segment_id: string;
  role: SegmentRole;
  display_text: string;
  spoken_text: string;
  show_block_ids?: Array<string>;
  focus_block_ids?: Array<string>;
  pause_after_ms?: number;
  source_ids?: Array<string>;
  estimated_ms?: number;
}

export interface SlideSpec {
  slide_id: string;
  order: number;
  title: string;
  learning_objective_ids?: Array<string>;
  layout: SlideLayout;
  blocks: Array<ParagraphBlock | BulletsBlock | FormulaBlock | ImageBlock | TableBlock | StepsBlock | DiagramBlock | CheckpointBlock | CalloutBlock>;
  segments: Array<NarrationSegment>;
  claims?: Array<TeachingClaim>;
  source_ids?: Array<string>;
  transition?: TransitionKind;
  estimated_seconds?: number;
}

export interface Objective {
  objective_id: string;
  text: string;
  evidence_status?: ObjectiveEvidenceStatus;
}

export interface GlossaryEntry {
  term: string;
  definition: string;
  spoken_hint?: string;
}

export interface CheckpointTemplate {
  checkpoint_id: string;
  slide_id: string;
  kind: CheckpointKind;
  prompt: string;
  verified_question_template?: Record<string, unknown> | null;
  reflection_seconds?: number | null;
  optional?: boolean;
}

export interface OutlinePage {
  order: number;
  title: string;
  layout: SlideLayout;
  objective_ids?: Array<string>;
  budget_seconds?: number;
  key_points?: Array<string>;
  visual_intent?: VisualIntent | null;
}

export interface OutlinePlan {
  objectives: Array<Objective>;
  pages: Array<OutlinePage>;
  glossary?: Array<GlossaryEntry>;
  scope_note?: string;
  uncovered_note?: string;
  total_budget_seconds?: number;
}

export interface VisualIntent {
  role: VisualRole;
  purpose: string;
  required_objects?: Array<string>;
  exclude?: Array<string>;
  orientation?: "landscape" | "portrait" | "square" | null;
  query_terms?: Array<string>;
  alt?: string;
}

export interface FileLocator {
  kind?: "file";
  namespace: string;
  file_id: string;
  chunk_ids: Array<string>;
  page?: number | null;
  printed_page?: string | null;
  section_path?: Array<string>;
  content_hash: string;
}

export interface WebLocator {
  kind?: "web";
  url: string;
  canonical_url: string;
  domain: string;
  publisher?: string | null;
  retrieved_at: string;
}

export interface SourceRecord {
  source_id: string;
  kind: SourceKind;
  title: string;
  locator: FileLocator | WebLocator;
  excerpt?: string;
  excerpt_hash: string;
  retrieved_at: string;
  published_at?: string | null;
  as_of?: string | null;
  verification?: Record<string, unknown>;
}

export interface AssetProvenance {
  provider: AssetProvider;
  provider_asset_id?: string;
  source_url?: string;
  creator?: string;
  creator_url?: string;
  license_url?: string;
  fetched_at: string;
}

export interface AssetRecord {
  asset_id: string;
  sha256: string;
  mime: "image/jpeg" | "image/png" | "image/webp";
  width: number;
  height: number;
  provenance: AssetProvenance;
  alt: string;
  caption?: string;
  role: AssetRole;
  bytes: number;
  status?: AssetStatus;
}

export interface ChapterSelection {
  section_path?: Array<string>;
  title: string;
}

export interface SourceFileSelection {
  file_id: string;
  chapters?: Array<ChapterSelection>;
}

export interface ExtraSessionSelection {
  session_id: string;
  attachment_file_ids?: Array<string>;
}

export interface SourceSelection {
  files?: Array<SourceFileSelection>;
  extra_sessions?: Array<ExtraSessionSelection>;
}

export interface ResearchBrief {
  enabled?: boolean;
  timeliness?: ResearchTimeliness;
}

export interface VoicePreferences {
  policy?: VoicePolicy;
  voice_id?: string;
  allow_local_fallback?: boolean;
  playback_speed?: number;
}

export interface LessonBrief {
  topic: string;
  goals?: Array<string>;
  source_selection?: SourceSelection;
  source_policy?: SourcePolicy;
  research?: ResearchBrief;
  duration_minutes?: 5 | 10 | 15 | 20 | 30;
  page_plan?: "auto" | "4_6" | "6_9" | "8_12" | "10_15" | "14_20";
  language?: LessonLanguage;
  grade?: string;
  pedagogy_id?: "concept_deep@1" | "worked_example@1" | "exam_review@1" | "case_inquiry@1" | "frontier_briefing@1";
  theme_id?: "academic_clear@1" | "chalk_focus@1" | "visual_story@1" | "lab_notebook@1" | "gentle_beginner@1";
  image_density?: ImageDensity;
  checkpoint_density?: CheckpointDensity;
  voice_preferences?: VoicePreferences;
  custom_requirements?: string;
}

export interface ReviewIssue {
  code: string;
  severity?: Severity;
  slide_id?: string | null;
  field_path?: string | null;
  reason: string;
}

export interface ReviewReport {
  issues?: Array<ReviewIssue>;
  summary?: string;
}

export interface LessonRevision {
  revision: number;
  schema_version?: 1;
  brief: LessonBrief;
  source_snapshot?: Array<SourceRecord>;
  slides: Array<SlideSpec>;
  checkpoint_templates?: Array<CheckpointTemplate>;
  objectives: Array<Objective>;
  glossary?: Array<GlossaryEntry>;
  assets?: Array<AssetRecord>;
  renderer_version?: string;
  prompt_versions?: Record<string, string>;
  review_report?: ReviewReport | null;
  content_hash: string;
  created_at: string;
}

export interface Lesson {
  lesson_id: string;
  owner_id: string;
  workspace_id: string;
  title: string;
  created_at: string;
  updated_at: string;
  latest_ready_revision?: number | null;
  published_revisions?: Array<number>;
  next_revision?: number;
  latest_job_id?: string | null;
  lifecycle?: LessonLifecycle;
}

export interface JobBudget {
  llm_calls_used?: number;
  llm_input_tokens_used?: number;
  llm_output_tokens_used?: number;
  search_calls_used?: number;
  extract_calls_used?: number;
  image_searches_used?: number;
  image_downloads_used?: number;
  tts_chars_used?: number;
  active_seconds_used?: number;
  unknown_external_outcomes?: number;
}

export interface GenerationJob {
  job_id: string;
  owner_id: string;
  workspace_id: string;
  lesson_id: string;
  base_revision?: number | null;
  target_revision: number;
  state?: JobState;
  phase?: JobPhase | null;
  state_revision?: number;
  brief_hash: string;
  stage_inputs?: Record<string, string>;
  artifacts?: Record<string, string>;
  budget?: JobBudget;
  attempts?: number;
  recovery_count?: number;
  cancel_requested?: boolean;
  last_error?: string | null;
  next_retry_at?: string | null;
  epoch?: number;
  start_mode?: StartMode;
  operation?: EditContentOperation | ChangeThemeOperation | RegenerateSlideOperation | ReplaceImageOperation | RefreshResearchOperation | null;
  created_at: string;
  updated_at: string;
}

export interface JobPreviewResponse {
  state: JobState;
  phase: JobPhase | null;
  slides?: Array<SlideSpec>;
  outline?: OutlinePlan | null;
  html?: string | null;
}

export interface Cursor {
  slide_id: string;
  segment_id: string;
  chunk_index?: number;
  offset_ms?: number;
  last_completed_segment_id?: string | null;
}

export interface LeaseInfo {
  client_id: string;
  lease_epoch: number;
  expires_at: string;
  heartbeat_at: string;
}

export interface RunCheckpointRef {
  checkpoint_id: string;
  slide_id: string;
  kind: CheckpointKind;
  question_ref?: string | null;
  state?: CheckpointRunState;
  assistance_events?: Array<string>;
}

export interface AudioProfile {
  policy?: VoicePolicy;
  provider?: string;
  voice_id?: string;
  language?: LessonLanguage;
  allow_local_fallback?: boolean;
  playback_speed?: number;
  version?: number;
}

export interface RunAnnotation {
  annotation_id: string;
  slide_id: string;
  segment_id?: string | null;
  user_text?: string;
  auto_excerpt?: string;
  created_at: string;
}

export interface ClassroomRun {
  run_id: string;
  owner_id: string;
  workspace_id: string;
  lesson_id: string;
  lesson_revision: number;
  content_hash: string;
  status?: RunStatus;
  state_revision?: number;
  cursor: Cursor;
  cursor_slide_order?: number;
  resume_anchor?: Cursor | null;
  checkpoint_refs?: Array<RunCheckpointRef>;
  audio_profile?: AudioProfile;
  audio_profile_version_note?: string;
  qa_session_id?: string | null;
  lease?: LeaseInfo | null;
  visited_slides?: Array<string>;
  listened_segments?: Array<string>;
  skipped_slides?: Array<string>;
  audio_refs?: Record<string, string>;
  tts_local_locked?: boolean;
  tts_fallback_notified?: boolean;
  tts_chars_used?: number;
  progress_event_ids?: Array<string>;
  annotations?: Array<RunAnnotation>;
  completed_kind?: "listened" | "browsed" | "";
  created_at: string;
  updated_at: string;
  ended_at?: string | null;
}

export interface AudioClip {
  clip_id: string;
  owner_id: string;
  lesson_id: string;
  revision: number;
  kind: AudioKind;
  content_ref?: Record<string, string>;
  segment_id?: string | null;
  chunk_index?: number;
  synthesis_key: string;
  provider?: string;
  voice_id?: string;
  language?: LessonLanguage;
  sample_rate?: number;
  sample_count?: number;
  bytes?: number;
  sha256?: string | null;
  state?: AudioClipState;
  error?: string | null;
}

export interface ExportJob {
  job_id: string;
  owner_id: string;
  lesson_id: string;
  revision: number;
  format: ExportFormat;
  state?: ExportState;
  artifact_id?: string | null;
  created_at: string;
  expires_at: string;
}

export interface ReplaceSlideChange {
  op?: "replace_slide";
  slide_id: string;
  slide: SlideSpec;
}

export interface DeleteSlideChange {
  op?: "delete_slide";
  slide_id: string;
}

export interface ReorderSlidesChange {
  op?: "reorder_slides";
  page_ids: Array<string>;
}

export interface EditContentOperation {
  op?: "edit_content";
  changes: Array<ReplaceSlideChange | DeleteSlideChange | ReorderSlidesChange>;
}

export interface ChangeThemeOperation {
  op?: "change_theme";
  theme_id: "academic_clear@1" | "chalk_focus@1" | "visual_story@1" | "lab_notebook@1" | "gentle_beginner@1";
}

export interface RegenerateSlideOperation {
  op?: "regenerate_slide";
  slide_id: string;
  instruction?: string;
}

export interface ReplaceImageOperation {
  op?: "replace_image";
  slide_id: string;
  block_id: string;
  candidate_id?: string | null;
  asset_id?: string | null;
}

export interface RefreshResearchOperation {
  op?: "refresh_research";
  scope?: RefreshScope;
}

export interface ErrorBody {
  code: ClassroomErrorCode;
  message: string;
  retryable?: boolean;
  phase?: JobPhase | null;
  request_id?: string;
}

export interface ErrorResponse {
  error: ErrorBody;
}

export interface SourcePublic {
  source_id: string;
  kind: SourceKind;
  title: string;
  status?: "available" | "revoked";
  namespace?: string;
  section_path?: Array<string>;
  page?: number | null;
  printed_page?: string | null;
  url?: string | null;
  domain?: string | null;
  publisher?: string | null;
  published_at?: string | null;
  as_of?: string | null;
  retrieved_at: string;
}

export interface AssetPublic {
  asset_id: string;
  mime: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
  role: AssetRole;
  status: AssetStatus;
  provider: AssetProvider;
  creator?: string;
  source_url?: string;
  license_url?: string;
}

export interface CheckpointPublic {
  checkpoint_id: string;
  slide_id: string;
  kind: CheckpointKind;
  prompt: string;
  reflection_seconds?: number | null;
  optional?: boolean;
  question?: Record<string, unknown> | null;
  run_state?: CheckpointRunState | null;
}

export interface BriefPublic {
  topic: string;
  goals: Array<string>;
  source_policy: SourcePolicy;
  duration_minutes: number;
  language: LessonLanguage;
  grade: string;
  pedagogy_id: string;
  theme_id: string;
  image_density: ImageDensity;
  checkpoint_density: CheckpointDensity;
  research_enabled: boolean;
  research_timeliness: ResearchTimeliness;
  custom_requirements?: string;
}

export interface RevisionPublic {
  revision: number;
  schema_version: number;
  brief: BriefPublic;
  slides: Array<SlideSpec>;
  objectives: Array<Objective>;
  glossary: Array<GlossaryEntry>;
  source_records: Array<SourcePublic>;
  assets: Array<AssetPublic>;
  checkpoints: Array<CheckpointPublic>;
  renderer_version: string;
  content_hash: string;
  created_at: string;
  estimated_total_seconds?: number;
}

export interface JobProgress {
  completed_slides?: number;
  total_slides?: number;
}

export interface JobPublic {
  job_id: string;
  lesson_id: string;
  state: JobState;
  phase: JobPhase | null;
  state_revision: number;
  progress: JobProgress;
  warnings?: Array<string>;
  last_error?: string | null;
  cancel_requested?: boolean;
  start_mode: StartMode;
  created_at: string;
  updated_at: string;
  next_actions?: Array<string>;
}

export interface LessonBriefProgress {
  brief: BriefPublic;
  progress: JobProgress;
  phase: JobPhase | null;
  state: JobState;
}

export interface RunPublic {
  run_id: string;
  lesson_id: string;
  lesson_revision: number;
  status: RunStatus;
  state_revision: number;
  cursor: Cursor;
  cursor_slide_order?: number;
  resume_anchor?: Cursor | null;
  audio_profile: AudioProfile;
  qa_session_id?: string | null;
  visited_slide_count?: number;
  completed_kind?: string;
  created_at: string;
  updated_at: string;
}

export interface LessonListStatusExtra {
  chapter_label?: string;
  slide_count?: number;
  active_job_count?: number;
  last_run?: RunPublic | null;
}

export interface LessonSummaryPublic {
  lesson_id: string;
  workspace_id: string;
  title: string;
  status: LessonListStatus;
  latest_ready_revision: number | null;
  latest_job?: JobPublic | null;
  brief?: BriefPublic | null;
  extra?: LessonListStatusExtra;
  updated_at: string;
}

export interface ResumeCardPublic {
  lesson_id: string;
  workspace_id: string;
  title: string;
  slide_count?: number;
  run: RunPublic;
}

export interface LessonDetailPublic {
  lesson_id: string;
  workspace_id: string;
  title: string;
  lifecycle: LessonLifecycle;
  latest_ready_revision: number | null;
  published_revisions: Array<number>;
  latest_job?: JobPublic | null;
  revision?: RevisionPublic | null;
  pending?: LessonBriefProgress | null;
  recent_run?: RunPublic | null;
}

export interface RevisionListItem {
  revision: number;
  created_at: string;
  source_changed?: boolean;
  available?: boolean;
}

export interface RevisionListResponse {
  items: Array<RevisionListItem>;
  total: number;
  page: number;
  page_size: number;
}

export interface LessonListResponse {
  items: Array<LessonSummaryPublic>;
  total: number;
  page: number;
  page_size: number;
  resume?: ResumeCardPublic | null;
}

export interface RendererCapability {
  available?: boolean;
  reason?: string;
  renderer_version?: string;
}

export interface ServiceCapability {
  configured?: boolean;
  available?: boolean;
  reason?: string;
}

export interface VoiceInfo {
  voice_id: string;
  language: string;
  display_name: string;
}

export interface TtsCapability {
  configured?: boolean;
  available?: boolean;
  reason?: string;
  policy?: VoicePolicy;
  local_enabled?: boolean;
  voices?: Array<VoiceInfo>;
}

export interface ClassroomLimits {
  max_pages: number;
  max_duration_minutes: number;
  max_published_revisions: number;
  max_image_searches: number;
  max_images: number;
  daily_tts_chars: number;
  generation_daily_limit: number;
  audio_cache_mb: number;
}

export interface ClassroomCapabilities {
  enabled?: boolean;
  allow_guest?: boolean;
  renderer: RendererCapability;
  research: ServiceCapability;
  images: ServiceCapability;
  tts: TtsCapability;
  limits: ClassroomLimits;
}

export interface PedagogyTemplateInfo {
  pedagogy_id: string;
  name_zh: string;
  name_en: string;
  description_zh: string;
  description_en: string;
  version: string;
}

export interface ThemeTemplateInfo {
  theme_id: string;
  name_zh: string;
  name_en: string;
  description_zh: string;
  description_en: string;
  version: string;
}

export interface TemplateDefaults {
  duration_minutes?: number;
  language?: LessonLanguage;
  pedagogy_id?: string;
  theme_id?: string;
  image_density?: ImageDensity;
  checkpoint_density?: CheckpointDensity;
  source_policy?: SourcePolicy;
}

export interface ClassroomTemplates {
  pedagogy: Array<PedagogyTemplateInfo>;
  themes: Array<ThemeTemplateInfo>;
  defaults: TemplateDefaults;
}

export interface CreateLessonRequest {
  brief: LessonBrief;
  start_mode?: StartMode;
}

export interface CreateLessonResponse {
  lesson_id: string;
  job_id: string;
  target_revision: number;
  status_url: string;
  events_url: string;
}

export interface CreateRevisionRequest {
  base_revision: number;
  operation: EditContentOperation | ChangeThemeOperation | RegenerateSlideOperation | ReplaceImageOperation | RefreshResearchOperation;
}

export interface CreateRevisionResponse {
  lesson_id: string;
  job_id: string;
  revision: number;
  status_url: string;
  events_url: string;
}

export interface JobSnapshotEvent {
  job_id: string;
  state_revision: number;
  state: JobState;
  phase: JobPhase | null;
  completed_slides?: number;
  total_slides?: number;
  warnings?: Array<string>;
}

export interface CancelJobRequest {
  expected_state_revision: number;
}

export interface RetryJobRequest {
  expected_state_revision: number;
}

export interface OutlinePatchRequest {
  expected_state_revision: number;
  outline: OutlinePlan;
}

export interface BriefPatchRequest {
  expected_state_revision: number;
  brief_patch: LessonBrief;
}

export interface ContinueJobRequest {
  expected_state_revision: number;
}

export interface RevisionOpRequest {
  base_revision: number;
  operation: EditContentOperation | ChangeThemeOperation | RegenerateSlideOperation | ReplaceImageOperation | RefreshResearchOperation;
}

export interface ImageSearchRequest {
  lesson_id: string;
  visual_intent: VisualIntent;
  provider?: ImageSearchProvider | null;
}

export interface ImageCandidate {
  candidate_id: string;
  provider: AssetProvider;
  provider_asset_id: string;
  thumbnail_url?: string;
  width?: number;
  height?: number;
  creator?: string;
  source_url?: string;
  license_url?: string;
}

export interface ImageSearchResponse {
  candidates?: Array<ImageCandidate>;
}

export interface AssetUploadResponse {
  asset: AssetPublic;
}

export interface CreateRunRequest {
  lesson_revision?: number | null;
  mode?: RunStartMode;
  voice_preferences?: VoicePreferences | null;
}

export interface RunCreateResponse {
  run_id: string;
  lesson_revision: number;
  status: RunStatus;
  resumed?: boolean;
}

export interface LeaseAcquireRequest {
  client_id: string;
  takeover?: boolean;
}

export interface LeaseRenewRequest {
  client_id: string;
  lease_epoch: number;
}

export interface LeaseResponse {
  lease_epoch: number;
  expires_at: string;
}

export interface ProgressRequest {
  expected_state_revision: number;
  client_event_id: string;
  client_seq: number;
  lease_epoch: number;
  action: ProgressAction;
  cursor?: Cursor | null;
  played_segment_ids?: Array<string>;
  skipped_slide_ids?: Array<string>;
}

export interface ProgressResponse {
  state_revision: number;
}

export interface AudioRequest {
  segment_ids: Array<string>;
  lease_epoch: number;
}

export interface ClipStatus {
  clip_id: string;
  state: AudioClipState;
  status_url: string;
  content_url?: string | null;
}

export interface AudioResponse {
  clips?: Array<ClipStatus>;
}

export interface AudioProfileRequest {
  expected_state_revision: number;
  voice_preferences: VoicePreferences;
}

export interface QaSessionResponse {
  session_id: string;
}

export interface QaAudioRequest {
  reply_message_id: string;
  lease_epoch: number;
}

export interface CheckpointSubmitRequest {
  question_ref: string;
  student_answer: string;
  idempotency_key: string;
  expected_scope_revision?: string | null;
}

export interface RunNoteRequest {
  slide_id: string;
  segment_id?: string | null;
  user_text?: string;
}

export interface RunNoteResponse {
  annotation_id: string;
}

export interface SaveNoteRequest {
  title?: string | null;
  include_user_notes?: boolean;
}

export interface SaveNoteResponse {
  note_id: string;
}

export interface ClassroomSummaryCheckpoint {
  checkpoint_id: string;
  slide_id: string;
  kind: CheckpointKind;
  state: CheckpointRunState;
}

export interface ClassroomSummaryQuestion {
  question_ref: string;
  state: string;
  pending_evaluation?: boolean;
}

export interface ClassroomSummary {
  run_id: string;
  lesson_id: string;
  lesson_revision: number;
  visited_slide_count: number;
  listened_segment_count: number;
  question_count: number;
  checkpoints: Array<ClassroomSummaryCheckpoint>;
  questions: Array<ClassroomSummaryQuestion>;
  annotations: Array<RunAnnotation>;
  completed_kind?: string;
  ask_follow_up_available?: boolean;
}

export interface ExportCreateRequest {
  revision: number;
  format: ExportFormat;
}

export interface ExportCreateResponse {
  export_id: string;
  status_url: string;
  content_url?: string | null;
}

export interface VoicePreviewRequest {
  language?: LessonLanguage;
  voice_preferences: VoicePreferences;
}

export interface VoicePreviewResponse {
  clip_id: string;
  content_url: string;
}

export interface OperationStatus {
  operation_id: string;
  kind: string;
  state?: "pending" | "running" | "succeeded" | "failed";
  created_at: string;
  updated_at: string;
  result?: Record<string, unknown>;
  error?: string | null;
}

export type InlineSpan = SpanText | SpanEmphasis | SpanMath;

export type DiagramSpec = FlowDiagram | CartesianPlot | ForceDiagram;

export type SlideBlock = ParagraphBlock | BulletsBlock | FormulaBlock | ImageBlock | TableBlock | StepsBlock | DiagramBlock | CheckpointBlock | CalloutBlock;

export type SourceLocator = FileLocator | WebLocator;

export type EditChange = ReplaceSlideChange | DeleteSlideChange | ReorderSlidesChange;

export type RevisionOperation = EditContentOperation | ChangeThemeOperation | RegenerateSlideOperation | ReplaceImageOperation | RefreshResearchOperation;
